### ISSUE TITLE
BUG: Bluespace Technician uniform's display a character examine instead of item description

### ISSUE THREAD

**Issue by Snypehunter007** [DS-13-Dev-Team/DS13-1.0#102]
#### Description of issue

- When you spawn a Bluespace Technician in and try to examine their uniform it displays what you are currently wearing, instead of the uniform's description.

**When you first examine the uniform:**
![BST git pt1](https://user-images.githubusercontent.com/42020765/75755459-a7813c00-5cfc-11ea-99bc-6a4ea165d58c.PNG)

**After taking off the uniform and examining it again:**
![BST git pt2](https://user-images.githubusercontent.com/42020765/75755568-ddbebb80-5cfc-11ea-93a8-f2ac17d6349d.PNG)

#### Steps to reproduce 

1. Spawn a BST.
2. Examine the uniform.

**Comment by boskoramen** [comment]
Cannot reproduce this bug.

**Comment by Afya212** [comment]
Unable to replicate as well.

**Comment by Snypehunter007** [comment]
I'm still getting it. Spawn in as a BST, take off any item you are wearing, and examine it.

**Comment by NanakoAC** [comment]
Unable to reproduce.

Not saying we don't believe you,. but it'd be nice to see a video of this in action

**Comment by Snypehunter007** [comment]
Lion, Aetsuki, and. . .someone else, IDR who, saw me do it on a Discord
stream when we testing stuff. I'll try to get a video in a few days.

**Comment by DTraitor** [comment]
Managed to reproduce.
You should use "Examine" from interaction list instead of shift+click

**Comment by DTraitor** [comment]
Happens to any part of bst clothing

**Comment by Snypehunter007** [comment]
Another note, this only happens with the Bluespace Tech, not the Engineer, despite them both wearing the same uniform.
