### ISSUE TITLE
Suggestion R&D changes

### ISSUE THREAD

**Issue by Icedcabbage** [DS-13-Dev-Team/DS13-1.0#1022]
#### Suggestion:
Add High-Velocity Pulse Ammo at a high cost. This combination of a high cost should be Diamonds, Steel, Plasteel as Diamonds and Plasteel is rather hard to get. 15 thousand steel, 15 thousand plasteel, 5 thousand diamonds is what I suggest for the cost values. Keep in mind that normal pulse rounds only cost 15 thousand steel and 15 thousand plasteel is perfect because a regular stack of plasteel only carries 10 sheets which transform into 20 thousand plasteel when put inside the protolathe. These amounts can be raised or lowered as you see fit. Lion requested I put this suggestion the github.

**Comment by Icedcabbage** [comment]
> #### Suggestion:
> Add High-Velocity Pulse Ammo at a high cost. This combination of a high cost should be Diamonds, Steel, Plasteel as Diamonds and Plasteel is rather hard to get. 15 thousand steel, 15 thousand plasteel, 5 thousand diamonds is what I suggest for the cost values. Keep in mind that normal pulse rounds only cost 15 thousand steel and 15 thousand plasteel is perfect because a regular stack of plasteel only carries 10 sheets which transform into 20 thousand plasteel when put inside the protolathe thus they will only be able to make one with one regular stack of plasteel. These amounts can be raised or lowered as you see fit. Lion requested I put this suggestion the github.
> 
> #### What do you think it'd add: I think this will add another high tech item Science can produce in small numbers for a extreme cost. Lion already plans on adding this but I thought I should put my thoughts down on the cost values of it.

**Comment by JakeDaBoss** [comment]
Useful info for me, thanks.

I'll look into it, going up on the next round of merging.
