### ISSUE TITLE
[BUG] Necros without any degree of night-vision get dunked in darkness.

### ISSUE THREAD

**Issue by Ketrai** [DS-13-Dev-Team/DS13-1.0#1027]
#### Description of issue:
It's pitch black.

#### Difference between expected and actual behavior:
To be able to see just a little, please?

#### Steps to reproduce:
Be slasher.
Become maint dweller.
Throw a temper tantrum, smash some lights.
End up being an involuntary void dweller.

**Comment by NanakoAC** [comment]
this is the byond darkness system, should be fixable with the see_in_dark var
