### ISSUE TITLE
General Necro Balance

### ISSUE THREAD

**Issue by MarshalRed** [DS-13-Dev-Team/DS13-1.0#1051]
#### Issue: What the general populace thinks the issue of necros is.
>Spitter/Puker doing lazer damage with spits instead of bio
>Slasher charge is a near 100% chance to disarm AND stun
>Enhanced slasher can 1-hit delimb with a charge, Regardless of RIG.
>Marker always starts with /400/ biomass. This is enough to spawn in 2 pukers and an enhanced.
>Security RIGs do not have nearly enough armour, and Pulse rifle is useless in its current state.
>No RIG has enough armour value to justify the slowdown caused by ALWAYS having the suit out when its on. Combined with corruption, There is a 0% chance to run away from  anything. 
>The RIG slowdown means that leapers are now very powerful, because their leap is a guarenteed 3 second stun + disarm. Combine this with some good maw placement and the Gallop ability, and Humans can get stunned, dragged away from help, and Maw'd before they can get unstunned. Throw in a spitter, and thats a 100% chance of death.

This is a issue I am posting because alot of people view necros as being too powerful right now. I know changes are on the way for some of these issues but I am stil posting.

**Comment by Ketrai** [comment]
Voidsuits and rigs have 100% bio resistance. This type of resistance is used for diseases, and obviously isn't meant to block spit damage 100%. Meanwhile lazer damage is more varied,  and existing suits armor and rigs are balanced with it in mind. On average burn armors are lower as burns can't break bones, and are easier to treat.

**Comment by Ketrai** [comment]
Normal slashers are extremely easy to kill with ranged weaponry. The pulse rifle has already been buffed with faster bullets. A lot of people are just using the gun without aiming or standing still, then complain about it missing. You can also use corners to make the charge entirely useless, or shoot a slasher's legs to interrupt it.
