### ISSUE TITLE
Should be removed

### ISSUE THREAD

**Issue by Greg-Joffer** [DS-13-Dev-Team/DS13-1.0#1055]
Right I make this point because it is dumb the fact that I can open a firesuit locker and boom RIOT RIG like why?

The riot RiG is added to be the CSO personal thing right? so why can you find it in maints? thats a dumb feature get it outta here.

**Comment by ghost** [comment]
It's inherently a part of the random loot system that can spawn different RIGs and is probably in the system either by accident or as a bug. But even if crew did manage to find extras it's not exactly the end of the world.

**Comment by Greg-Joffer** [comment]
Okay I get that but, the whole deal is I could say hypothetically go around all the fire suit lockers and maints until I get the gear I need to basically robust people who were just doing their jobs, but the point of it being a limited item and one a high ranking Sec officer gets is that no one is supposed to have it except him and put everyone that's not him and a slight or major disadvantage.

**Comment by Greg-Joffer** [comment]
Look what I'm saying is remove riot and sec RiGs from the random RIG roulette in firelockers not to get rid of the other stuff just those two rigs overall.

**Comment by NanakoAC** [comment]
its a pretty uncommon item, and that's reflected by it having a much lower weight in the random rig pool. Nothing about its design was ever intended to be a once-only thing though. Giving it to the chief of security seemed a good way to give sec one guaranteed, but it's not a command privilege thing intended for his sole use, 

Perhaps that one should be moved to the armory, we just can't do mapping changes at this exact moment while lion's tram overhaul is pending, so i had to add it to the contents of an existing locker, hence the CSEC

**Comment by Snypehunter007** [comment]
@Greg-Joffer As a warning for the future, please follow the issue format or your issue might be closed immediately.

That said, it is pretty ridiculous, and this has been marked as an accepted suggestion.

**Comment by Greg-Joffer** [comment]
dog I just saw you do it
 but sure I'll follow the format next time
