### ISSUE TITLE
[SUGGESTION] Remove/Rework shrapnel

### ISSUE THREAD

**Issue by Survivor23** [DS-13-Dev-Team/DS13-1.0#1068]
#### Suggestion: 

Remove shrapnel, or make it possible to remove it yourself.

#### What do you think it'd add: 

Shrapnel is one of the larger pains for humans. A lurker can hit you once from off screen with a spine shrapnel, and instantly cripple you for the rest of the game if there are no doctors to remove it. Making it so that humans can remove the shrapnel themselves by ripping it out, letting you splint the affected limbs, or flat out removing the mechanic would seriously improve QoL for the flow of the game. No one wants to be crippled by something from off screen.

**Comment by Evankhell561** [comment]
this issue was supposed to be closed when this #1277 pr was marged.
