### ISSUE TITLE
Access of heads

### ISSUE THREAD

**Issue by Terror4000rus** [DS-13-Dev-Team/DS13-1.0#1070]
The Captain doesn't has access to the kitchen and the bartender's room, by code. That's not funny.
The First Lieutenant doesn't has access to them too, but the rank is also represents as the head of service department, which makes no sense with such issue.

**Comment by Terror4000rus** [comment]
I know that's not a game about traitors vs crew, but about crew vs aliens, but could someone with degree of power to change such gameplay things do something with it or tell that this is intended?

**Comment by JakeDaBoss** [comment]
Will fix this.

**Comment by JakeDaBoss** [comment]
@KeRSedChaplain all yours.
