### ISSUE TITLE
Laser pickaxe destroys reinforced walls in 6-7 hits

### ISSUE THREAD

**Issue by Terror4000rus** [DS-13-Dev-Team/DS13-1.0#1073]
Topic
You don't need tools or C4s - just politely ask a miner (or be one) for it and then break into the armory after 3 broken walls during emergency.
It's actually a usefull tool agains necromorphs and for breaking airlocks (and for a moment, maybe the last one after fire axe to do it  without special tools), but maybe reduce its damage just a bit or make reinforced walls stronger?

**Comment by ghost** [comment]
Reinforcing wall strength is going to be a major part of our balancing overhaul, so maybe we'll get a head start on that.
