### ISSUE TITLE
[SUGGESTION] Acceptable atmosphere pressure on Aegis VII

### ISSUE THREAD

**Issue by Terror4000rus** [DS-13-Dev-Team/DS13-1.0#1075]
It's cannonicly true, that at least atmosphere pressure at the colony is at enough condition to stay there without voidsuit. Right now, we have vacuum-like asteroid.
Maybe make it like 84.7 kPa or so? Breathable or not - it's other question.
### Why it is better
There are many posters with Ishimura's mining crew, as well as dead corpses at mining deck in the first game. It would just add immersiveness to gameplay.
I know they had some sort of light RIGs during the obelisk's extraction, but it still doesn't looks like space suit. Just a working suit with panoramic helmet.
### Gameplay
I actually don't want to remove planet cracker's only reliable source of armor. Maybe just resprite the voidsuit and remove its space proofness?

**Comment by Survivor23** [comment]
Yeah, in the games they had some basic protective equipment such as specialized gas masks and all that. Only time the miners had Hardsuits were in the movies, plus the DS1 miner rigs.

**Comment by NanakoAC** [comment]
this is planned, we just have lots of other things going on.

it'll be reworked to use the exoplanet system when i get around to it

**Comment by Survivor23** [comment]
Beast

**Comment by MarshalRed** [comment]
Is this being worked on?

**Comment by ghost** [comment]
@Snypehunter007 @Ketrai Please confirm if this is resolved or not.

**Comment by DTraitor** [comment]
We added atmosphere to "Aegis" outpost a while ago
