### ISSUE TITLE
[ISSUE] Item durability is hard to gauge

### ISSUE THREAD

**Issue by Ketrai** [DS-13-Dev-Team/DS13-1.0#1081]
There is no way to tell how much durability an item has. Some sort of overlay and examine message could help.

**Comment by JakeDaBoss** [comment]
This already exists.

Item will commonly say "close to breaking" if heavily damaged.

Though what are you referring to?

**Comment by Ketrai** [comment]
It'd be nice if the item itself showed a square around it dictating it's durability. Or an outline. Yellow when damaged, red when close to breaking.
