### ISSUE TITLE
HUNTER feedback thread

### ISSUE THREAD

**Issue by Ketrai** [DS-13-Dev-Team/DS13-1.0#1082]
#### Suggestion:
- notes.
- hunter can charge whilst lacking many limbs, perhaps stop charge when a leg is missing, or both arms.
- add an examine detail encouraging people to avoid fighting it without fire.
- the hunter seems to regenerate lasting damage pretty quick. Perhaps lower the amount regenerated.
- the hunter already has a crowd control ability that does pretty great damage. Perhaps lower normal slash damage, considering it's almost a strong in raw combat power as an ubermorph, which does 25 damage. Whilst the hunter does 24.

**Comment by Survivor23** [comment]
All of these changes seem good, but the main problem with the Hunter is the lack of an efficient way to fight it, due to the Flamethrower being incredibly buggy. If the flamer was fixed, it would seriously help balance it out a bit.

**Comment by NanakoAC** [comment]
generally agreed with ketrai on all points, and will be implementing those changes.

In addition, mobs with >1 tile reach, are going to have 1 less reach while lying down
