### ISSUE TITLE
Humans - Night vision and other items to fight with darkness

### ISSUE THREAD

**Issue by Terror4000rus** [DS-13-Dev-Team/DS13-1.0#1085]
I decided to check the firefighter's RIG in code and discovered for myself, it has night vision and the launcher with illumination grenades.

The question to think about - how much darkness and broken lighting should affect on game of survivors?
With night vision, security and firefighter RIGs wearers (I didn't check other) can ignore lack of lighting at all.
And even more - the grenade launcher can light up almost the whole screen for some time.

My opinion - night vision and the launcher are harmful for experience.
I just want to know the server's position about it.

**Comment by Terror4000rus** [comment]
There are also mounted flashers as modules (they were removed from R&D and security lockers, as I remember).

**Comment by RuneQuester** [comment]
Most people using a firesuit RIG probably dont have spare illumination grenades, and light is rarely a concern anway.

**Comment by NanakoAC** [comment]
Night vision is a bit overpowered, but illumination grenades are finite and good

**Comment by Terror4000rus** [comment]
> Night vision is a bit overpowered, but illumination grenades are finite and good

So all night vision items have to be removed?
And what about meson goggles/modules?

**Comment by NanakoAC** [comment]
> So all night vision items have to be removed?

that is definitely not what i said.
Philosophy here is to improve, not remove. We don't just delete things that are too powerful, they get adapted to fit better

**Comment by Terror4000rus** [comment]
> that is definitely not what i said.
> Philosophy here is to improve, not remove. We don't just delete things that are too powerful, they get adapted to fit better

Removed from map and access before rework, I mean.
Like flashbangs.
