### ISSUE TITLE
Walls are not rendered when looking down from upper to lower levels with open_area turf.

### ISSUE THREAD

**Issue by JakeDaBoss** [DS-13-Dev-Team/DS13-1.0#1096]
Walls are not rendered when "looking down". This happens when the "open area" turf is placed over areas that have walls on the upper levels. As a result, walls that would appear fine on the lower level, appear as plating on the lower level when looking from the upper one.

**Comment by Snypehunter007** [comment]
Fixed via Z-Mimic #1433
