### ISSUE TITLE
Grab Combat is non-functional

### ISSUE THREAD

**Issue by JakeDaBoss** [DS-13-Dev-Team/DS13-1.0#1103]
#### Description of issue:
The act of grab combat (slitting of throats, covering of eyes, mouth and so forth) is completely non-functional. Originally reported by BoringCommunist.

#### Difference between expected and actual behavior:
This should work.

#### Steps to reproduce:
* Grab a human by the chest.
* Change to mouth/eyes.
* Try on any intent by clicking on their body.
* It tries to perform the same action, or none at all.

**Comment by NanakoAC** [comment]
fixed
