### ISSUE TITLE
Signals using leave-necromorph-horde to ghost, find out player locations, and join back.

### ISSUE THREAD

**Issue by JakeDaBoss** [DS-13-Dev-Team/DS13-1.0#1105]
#### Description of issue:
This has been happening for a while now, and us moderators/admins have no manner of finding out who did that, making it a virtually unpunishable rule offense. Signals leave the necromorph horde to gain unobstructed view, then rejoin to relay said information.

#### Difference between expected and actual behavior:
Signals should not be able to do that. As far as a solution goes, though, I have nothing.

#### Steps to reproduce:
No reliable way to reproduce.

**Comment by ghost** [comment]
Being enforced by mods, will need a tool to log these exits more properly down the line.
