### ISSUE TITLE
Open Space construction non-functional.

### ISSUE THREAD

**Issue by JakeDaBoss** [DS-13-Dev-Team/DS13-1.0#1110]
#### Description of issue:
When players attempt to fix floor breaches (open space leading to the lower level), they cannot place lattices. If admin-spawned, lattices cannot be placed on with floor tiles. I have a feeling this has to do with the underplating @NanakoAC ported a while back.

#### Difference between expected and actual behavior:
Clicking rods on open space should make lattice.
Clicking lattice with floor panels in hand, should make plating or underplating.

#### Steps to reproduce:
Destroy floor.
Try to reconstruct floor.

**Comment by JakeDaBoss** [comment]
Description of issue : Can't place lattices or rebuild open holes on upper decks

Difference between expected and actual behavior : You should be able to repair holes in the floor, probably.

Steps to reproduce : Make a hole in the floor then try to build over it via metal rods/floor tiles(?)

Prior reported by Bapldap as well on September 22nd, 2020.

**Comment by DTraitor** [comment]
It was fixed in lighting rework PR
