### ISSUE TITLE
Kiss of Death erroneous tile selection causes cooldown, instead of valid mob

### ISSUE THREAD

**Issue by JakeDaBoss** [DS-13-Dev-Team/DS13-1.0#1113]
Description of issue:
Kiss of Death goes on cooldown if you happen to click on a empty tile by mistake, it's kind of annoying since you have to pixel hunt a bit as Tripod when you want to click on people

Difference between expected and actual behavior:
Control+Shift Clicking on empty tiles don't use Kiss of death, hence it doesn't go on cooldown
Currently, clicking on anything causes Kiss of Death to go on cooldown

Steps to reproduce:
1- Be Tripod
2- Control+Shift click any tile
3- Do it again
4- Kiss of Death is on cooldown

**Comment by Evankhell561** [comment]
I think this has already been fixed.
