### ISSUE TITLE
Shrapnel too small to pull out of body. (Yank out object verb)

### ISSUE THREAD

**Issue by JakeDaBoss** [DS-13-Dev-Team/DS13-1.0#1115]
Description of issue: Cyst Projectile Shrapnel is too small to be pulled out of your body

Difference between expected and actual behavior: The cyst biomass shrapnel is too small to be pulled out. I'm not sure if it's intented or not, but, it's a bit too punishing to be just hit by a cyst and have your entire game be stuck in crit cause the doctors have no idea how to get it out and you, yourself can't pull it out.

Steps to reproduce: 

1: Sit in front of cyst
2: Get shot by it and have a fragment imbeded 
3: Try to pull it out
4: It's too small

**Comment by Evankhell561** [comment]
it was possibly fixed in this pr: #1277
