### ISSUE TITLE
Medical PDA won't scan people on tables/beds

### ISSUE THREAD

**Issue by JakeDaBoss** [DS-13-Dev-Team/DS13-1.0#1121]
#### Description of issue:
The medical PDA won't scan people on tables or beds. In conjunction, using a stethoscope or penlight on them also does not work.

#### Difference between expected and actual behavior:
This should work for people who are on tables or beds.

#### Steps to reproduce:
Stand on table/bed, try these actions on yourself.

**Comment by Evankhell561** [comment]
I cannot reproduce the problem.
![image](https://user-images.githubusercontent.com/49106866/108613289-bc188180-73f0-11eb-8265-98f5763d0f9d.png)
