### ISSUE TITLE
RIG Toggling issues

### ISSUE THREAD

**Issue by JakeDaBoss** [DS-13-Dev-Team/DS13-1.0#1122]
Description of issue: Cannot toggle parts of RIG, reason unknown, which can be bad if medical are tending to patient, the air tank also automatically turns itself off if one manages to 'awaken' during this.

Difference between expected and actual behavior: Should be able to

Steps to reproduce: Unknown, pending investigation, most likely has to do with wound state.

**Comment by ghost** [comment]
Non-issue now that we have RIG retractors.
