### ISSUE TITLE
Metal foam grenades containing biological acid

### ISSUE THREAD

**Issue by JakeDaBoss** [DS-13-Dev-Team/DS13-1.0#1124]
Description: metal foam grenades filled with biological acid 

Difference between what actually supposed to get in the grenades

Steps to reproduce: arm a metal foam grenade and set it on the ground. I did it with a grenade in engineering storage

**Comment by Evankhell561** [comment]
![image](https://user-images.githubusercontent.com/49106866/106071949-8ccf6700-6107-11eb-8e68-24685c4fae20.png)
