### ISSUE TITLE
Uncommon instance where abilities go into negative cooldown states with no recovery

### ISSUE THREAD

**Issue by JakeDaBoss** [DS-13-Dev-Team/DS13-1.0#1125]
Description of issue: When I was a normal Slasher, I used the charge shortcut against a guy with a polyacid spray bottle. As soon as I clicked charge, the charge entered a permanent cooldown where I wasn't allowed to charge as it said I was already charging. This did the same to my dodge.

Difference between expected and actual behavior: I should've been able to execute the charge but again it said I was already charging when I had been moving around like normal instead of the dashing movement of a charge.

Steps to reproduce: First, use the charge shortcut and then be struck by polyacid during a lagspike.

**Comment by NanakoAC** [comment]
Most likely caused by #766
