### ISSUE TITLE
Reconnect causes Unitologist to lose their antagHUD overlay.

### ISSUE THREAD

**Issue by JakeDaBoss** [DS-13-Dev-Team/DS13-1.0#1126]
Scenario: This was on the bootleg server so take it with a grain of salt but I was a unitoligist and I had my little symbol over my character to let me know I was a Uni and over my other Uni buds. which is normal yes?

Issue: well due to the server sometimes reconnecting me I rejoined and no longer had the symbol over my sprite or any of my other unitoligist friends. I still had access to my notes, but am unsure whether the other Unis couldn't see my symbol

Apparently this issue has also occurred on official

**Comment by ghost** [comment]
It comes back very quick after.
