### ISSUE TITLE
Leaper's automatic camera alignment is broken

### ISSUE THREAD

**Issue by JakeDaBoss** [DS-13-Dev-Team/DS13-1.0#1130]
Description of issue: leapers automatic camera is beyond fucked 

Difference between expected and actual behavior: being able to play a necromorph and control it easily should be a given but the automatic camera movement panning to whichever direction you moved to completely screws over any ability to hit or fight any human 

Steps to reproduce: play as a leaper and experience the absolute pisspoor camera

**Comment by ghost** [comment]
We'll need to tweak the extended camera to be something more toggle-able in the near future.

**Comment by ghost** [comment]
I believe this is fixed with a recent PR.
