### ISSUE TITLE
Divider limbs counted as antagonist in check-antagonists.

### ISSUE THREAD

**Issue by JakeDaBoss** [DS-13-Dev-Team/DS13-1.0#1131]
Description of issue: Divider limbs are counted as antagonist

Difference between expected and actual behavior:
They should not be counted as antagonist

Steps to reproduce: Have a divider separate And then check antag panel https://cdn.discordapp.com/attachments/506375004745760768/757415628670894211/unknown.png

**Comment by NanakoAC** [comment]
working as intended, they're players playing as an antagonistic creature
