### ISSUE TITLE
Linegun shoots through solids

### ISSUE THREAD

**Issue by JakeDaBoss** [DS-13-Dev-Team/DS13-1.0#1146]
Description of issue: Weapon bug for the Linegun.

Difference between expected and actual behavior: The Linegun should probably shoot in a straight-ish arc forward, and not through solid objects without breaking them. Instead, it can shoot through glass windows perfectly fine in-game. I've seen survivors kill necromorphs that way.

Steps to reproduce: Shoot the Linegun through a window, probably on a tile bordering the window.

**Comment by JakeDaBoss** [comment]
Additional report by EugeneShev (Pufferfish Eating A Carrot)

If I recall properly, cutters still pass through transparent objects, but recently I've figured it also ignored machines and whatnot. Not that they're not transparent, I just suspected it would work more like a laser that still hits the machinery. I certainly remember a line gun passing through the fridge, at least.

**Comment by Snypehunter007** [comment]
Duplicate of #1026.

Closing.
