### ISSUE TITLE
Turret not firing on lurkers if set to non-crew.

### ISSUE THREAD

**Issue by JakeDaBoss** [DS-13-Dev-Team/DS13-1.0#1151]
#### Description of issue:
turret set to non crew not firing on two lukrers infront of it not sure if its a bug or not

#### Difference between expected and actual behavior:
Turret should fire on Lurkers.

**Comment by Evankhell561** [comment]
I can't reproduce this.
![image](https://user-images.githubusercontent.com/49106866/107689608-536f2d80-6ca9-11eb-8f63-1308b9792c9c.png)
![image](https://user-images.githubusercontent.com/49106866/107689593-4ce0b600-6ca9-11eb-90c6-41d209d00157.png)
![image](https://user-images.githubusercontent.com/49106866/107689617-5833e180-6ca9-11eb-8682-8d792d3dc1c2.png)
