### ISSUE TITLE
Exec Shuttle blast doors button non-functional

### ISSUE THREAD

**Issue by JakeDaBoss** [DS-13-Dev-Team/DS13-1.0#1153]
description: Executive shuttle blast doors button doesn't work
difference: I expected to see the blast doors close when the button was pressed, but nothing happened when I did
steps to reproduce: 1. Go to the executive shuttle's bridge 2. Push the button 3. Observe the lack of movement from the blast doors

**Comment by JeserTheFox** [comment]
Tested, works fine. I suppose fix was already merged.

**Comment by JakeDaBoss** [comment]
#1181 fixed this.
