### ISSUE TITLE
Meddle is too.. Meddlesome.

### ISSUE THREAD

**Issue by JakeDaBoss** [DS-13-Dev-Team/DS13-1.0#1159]
#### Description of issue:
signals using meddle to open doors works on blast doors which has a number of very, very disastrous possibilities

Can also be used on Reactor blastdoors.

#### Difference between expected and actual behavior:
Should not be possible, or at least disabled near sensitive equipment.

**Comment by JeserTheFox** [comment]
Meddle for doors is completely disable right now, so this one is irrelevant.
