### ISSUE TITLE
Morgue inner button non-functional

### ISSUE THREAD

**Issue by JakeDaBoss** [DS-13-Dev-Team/DS13-1.0#1165]
Description of issue: the inside of the morgue button wont work
Difference between expected and actual behavior: it should work but it dont
Steps to reproduce: go inside the morgue and try to close it

**Comment by Evankhell561** [comment]
![image](https://user-images.githubusercontent.com/49106866/106789212-42dc0900-6652-11eb-9ba0-d4f4dafd5ada.png)

**Comment by Evankhell561** [comment]
![image](https://user-images.githubusercontent.com/49106866/106789240-4bccda80-6652-11eb-90fa-1374ca05d523.png)

**Comment by Evankhell561** [comment]
it seems that this bug has already been fixed.
