### ISSUE TITLE
Necrochat doubling

### ISSUE THREAD

**Issue by JakeDaBoss** [DS-13-Dev-Team/DS13-1.0#1169]
#### Description of issue:
necrochat is doubled sometimes, perhaps this has to do with the bug where humans are able to view necrochat?

#### Difference between expected and actual behavior:
This should not happen, but can't reproduce.

**Comment by JakeDaBoss** [comment]
Description of issue: Necrochat pops up when im as surv
Turned hide and show off and on and it still shows up


Difference between expected and actual behavior:
Muh fucking imersion man


Steps to reproduce:
latejoin, get necrochat

**Comment by ghost** [comment]
We're aware of this issue as a whole and it's listed in other issues, consolidating for posterity.
