### ISSUE TITLE
Uncommon bug for some players in spawning or entering server

### ISSUE THREAD

**Issue by JakeDaBoss** [DS-13-Dev-Team/DS13-1.0#1170]
#### Description of issue:
Joined the server, was immediately without any warning forced to observe as a random invisible ghost with a name not in my character list/slots. Respawning was allowed instantly via the OOC tab however, I was unable to observe, or rejoin the game at all, despite attempting reconnects  as well.

#### Difference between expected and actual behavior:
This should not happen.

**Comment by ghost** [comment]
As it cannot be reproduced, we're closing this for now on the assumption the error was client-side.
