### ISSUE TITLE
Necro body evac causes player to be placed as a ghost, not as a signal.

### ISSUE THREAD

**Issue by JakeDaBoss** [DS-13-Dev-Team/DS13-1.0#1171]
#### Description of issue:
When I evaced a necro body, it kicked me out of necro into ghost, and made me rejoin necros, in like 4 seconds. (I play with EU lag debuff.)

#### Difference between expected and actual behavior:
Player should be put back in Necrosignal.

**Comment by ghost** [comment]
Cannot reproduce, closing for now.
