### ISSUE TITLE
Uncommon bug playing as Hunter causing duplication or inheritance of other necromorph abilities

### ISSUE THREAD

**Issue by JakeDaBoss** [DS-13-Dev-Team/DS13-1.0#1172]
#### Description of issue:
Another perhaps EU glitch. Playing as hunter, and divider I had abilities activate without me interacting with them. Regenerate, hook thing and divide.
It always happened after I got hit by another sprite (bullet, just hit by and object flying etc.)

#### Difference between expected and actual behavior:
Should not happen.

**Comment by ghost** [comment]
Hasn't been an issue in recent weeks, closing for now.
