### ISSUE TITLE
Crew can see scrying.

### ISSUE THREAD

**Issue by JakeDaBoss** [DS-13-Dev-Team/DS13-1.0#1173]
#### Description of issue:
Crew can see where signals/marker are scrying. Dunno if that's suppose to be.

#### Difference between expected and actual behavior:
Should this be possible? @NanakoAC

**Comment by NanakoAC** [comment]
intentional, the goal was to give people a feeling of being watched. And when they know they're being watched, they may do more interesting things, roleplay better.

It's a matter for debate, but i believe the feature as is, is a net gain for gameplay and interaction
