### ISSUE TITLE
Suspension Field Generator non-functional.

### ISSUE THREAD

**Issue by JakeDaBoss** [DS-13-Dev-Team/DS13-1.0#1176]
#### Description of issue:
none of the buttons work on the suspension field generator in xenoarch. it doesn't turn on, lock, refresh, or close

#### Difference between expected and actual behavior:
Should work.

**Comment by Evankhell561** [comment]
This is not a bug because the problem is that the generator has no power. maybe a little feedback will help clarify this. In any case, it is not a bug.

**Comment by JakeDaBoss** [comment]
@Evankhell561 
I did some testing on this part.

These are freshly spawned, with a cell inside of them that should be fully charged.

**Comment by Evankhell561** [comment]
> @Evankhell561
> I did some testing on this part.
> 
> These are freshly spawned, with a cell inside of them that should be fully charged.

I'll investigate then.
