### ISSUE TITLE
Tripod tongue lash does nothing.

### ISSUE THREAD

**Issue by JakeDaBoss** [DS-13-Dev-Team/DS13-1.0#1178]
Description of issue: Tripod tongue lash does nothing when used

Difference between expected and actual behavior: Expected tongue lash do have any form of effect, it's current effect seems to only be creating a weakpoint to target

Steps to reproduce: (1) become a tripod (2) middle click on a human (3) observe the chat log not producing anything new, and if the target has a RIG, observe no change to the health strip

**Comment by NanakoAC** [comment]
fixed yesterday
