### ISSUE TITLE
Suit storage Pulse rifle bug

### ISSUE THREAD

**Issue by Greg-Joffer** [DS-13-Dev-Team/DS13-1.0#1197]
Description of issue: so you put the pulse rifle in the suit storage but you can still fire it which isnt helpful when you try interact with consoles laptops throwing oxy candles. 

Difference between expected and actual behavior: I dont shoot people with the wepon in suit storage, currently I do.

Steps to reproduce: Put a pulse rifle in your suit storage and click around you I dont know if this effects the grenade laucher mode yet.

**Comment by NanakoAC** [comment]
fixed by jade yesterday
