### ISSUE TITLE
BUG: Barricades & IV stands have no collision

### ISSUE THREAD

**Issue by Snypehunter007** [DS-13-Dev-Team/DS13-1.0#120]
#### Description of issue

- Barricades currently have no collision, so you can merely walk over them, negating the purpose of it being a barricade.
- IV stands have a similar problem.

#### Steps to reproduce 
1. Go to the Abandoned Hydroponics section.
2. Walk over a barricade.
3. Go to medical.
4. Walk over IV stands.

**Comment by NanakoAC** [comment]
They do have collision
https://i.imgur.com/b0o2vWU.gif

You may have seen a leaper jumping over one, i believe that's the only current way for necros to bypass barricades without breaking them.
If you saw someone walking through one, then i'm not sure what happened, cannot reproduce.

IV stands are not supposed to have collision. I searched the history as far back as it goes, january 2018, they have never had collision in this codebase
You may have seen them with collision on other servers, i've seen that too.  But it was a terrible design. Serving no good purpose, and often causing pointless medical accidents as someone bumps into one. I see nothing to gain from adding collision to them, the current state seems most ideal

**Comment by Snypehunter007** [comment]
> 
> 
> They do have collision
> https://i.imgur.com/b0o2vWU.gif
> 
> You may have seen a leaper jumping over one, i believe that's the only current way for necros to bypass barricades without breaking them.
> If you saw someone walking through one, then i'm not sure what happened, cannot reproduce.
> 
> IV stands are not supposed to have collision. I searched the history as far back as it goes, january 2018, they have never had collision in this codebase
> You may have seen them with collision on other servers, i've seen that too. But it was a terrible design. Serving no good purpose, and often causing pointless medical accidents as someone bumps into one. I see nothing to gain from adding collision to them, the current state seems most ideal

Huh, odd, I just tested it as well. I saw six of seven people go into Hydroponics through those same barricades during the test and they commented on it.

It looks really bizarre if there is no collision with IV stands and it doesn't really make sense that a standing, large pole and attached bags has no collision.

**Comment by NanakoAC** [comment]
discussed in discord months ago, working as intended, barricades do have collision, IV stands don't and shouldn't
