### ISSUE TITLE
Suggestion-Add RIG construction to Science

### ISSUE THREAD

**Issue by Icedcabbage** [DS-13-Dev-Team/DS13-1.0#1221]
#### Suggestion:
Add a machine to Research that allows the production of RIG frames where once constructed you could add RIG circuits that you make from the Circuit Imprinter, wires, and batteries and the like to produce a working RIG, these RIG frames and circuits could be expensive to produce depending on what kind of RIG you are making, for example an EVA RIG or Fire RIG would be cheaper to make than an Engineering RIG.

#### What do you think it'd add:
This will Science to produce RIGs for themselves and others and give a use to all the modules R&D can already make. I was also told by Lion that this not being added yet is an oversight. (atleast he thinks it is)

**Comment by ghost** [comment]
This would be viable if we didn't already have intentions to make the Stores and Cash Persistence a major part. Too many avenues for creating RIGs could cause major imbalances in gameplay. It's on the table, though. Just not for now.
