### ISSUE TITLE
Necromorph fake name adjustments.

### ISSUE THREAD

**Issue by JakeDaBoss** [DS-13-Dev-Team/DS13-1.0#1224]
Description of issue: Necromorphs with ID have their... Real_name at ID's name field.
Difference between expected and actual behavior: Not real name. Better just add showflake ID which doesn't change its owner name to don't create things like Slasher 325 (as Armando Brown)
Steps to reproduce: Examine a necromorph with ID card. Check the ID.

**Comment by ghost** [comment]
Will be relevant later on with the implementation of the Infector, closing for now.
