### ISSUE TITLE
Exploder's pustule no longer explodes on launch

### ISSUE THREAD

**Issue by JakeDaBoss** [DS-13-Dev-Team/DS13-1.0#1237]
Description of issue: Necromorph exploder, amputate the explosive pustule and try to use the Kinesis Module to throw and make an explosion - It doesn't work and the explosive pustule doesn't explode for some strange reason. If you just take an explosive pustule and throw it with a simple hand, it explodes.

Difference between expected and actual behavior: I was expecting to use the Kinesis Module and take an explosive pustule to throw it and it explodes. But, it doesn't explode! For a strange reason, to make the explosive pustule explode. You just need to take it in your hand and throw it so that it explodes.

Steps to reproduce: Use the Kinesis Module on the explosive pustule to throw it, and watch it not even explode.

**Comment by DTraitor** [comment]
Couldn't reproduce
