### ISSUE TITLE
Suggestion: Add a Emergency Lighting Button on bridge

### ISSUE THREAD

**Issue by Thegodemperorofmankind11** [DS-13-Dev-Team/DS13-1.0#1258]
#### Suggestion:
Add a red light button on the bridge, to trigger Emergency Lighting across the ship, according to the people on discord its really atmospheric, but it is tied to a power outage.

#### What do you think it'd add:
It would add to the atmosphere, as said by ThatOneDude, and other people on the discord, As the lights, Really adds to the feeling of an emergency, As the ship is switching to this emergency lighting, as people are dying it just seems good for the atmosphere, HOWEVER, depending on the captain, It could be abused, (People turning it off and on.) but that's a price to pay.

**Comment by ghost** [comment]
We'll be adding an overall better system for emergency lighting in the future.
