### ISSUE TITLE
Bug: Crossbow deals absurd amount of damage

### ISSUE THREAD

**Issue by Icedcabbage** [DS-13-Dev-Team/DS13-1.0#1267]
#### Description of issue:
The crossbow can deal absurd amounts of damage if it hits. It can deal enough damage to instantly kill a leaper at 110 health and I imagine it can all T1s in one shot, and maybe T2s in one shot if they get lucky RNG on the hit.

#### Difference between expected and actual behavior:
Since the crossbow is a makeshift weapon that anyone get their hands on with some wood and wire. It shouldn't deal this much damage. I expect it to deal a good amount of damage but it shouldn't be able to instant kill T1 necros from any range.

#### Steps to reproduce:
Make the Crossbow, load it with a metal rod, fire it at a T1 necromorph aiming for the limbs.

**Comment by MarshalRed** [comment]
It requires 5 wood, 3 metal rods, 5 wire, 3 plastic, 5 wire again, screwdriver, and a power cell to complete. It also takes a good 10 seconds to reload. Not as overpowered as he says. It basically does nothing to higher tier necros. I do agree it should not instantly kill a necro from one hit.

**Comment by JeserTheFox** [comment]
I would like to know how exactly you manage to one hit xenos. It does indeed deal a ton of damage to limbs, allowing you to take off arm from most necros in one hit and 3 for brute, but I didn't manage to one shot kill anyone with it.
