### ISSUE TITLE
Suggestion: Add skill level caps to each role

### ISSUE THREAD

**Issue by Icedcabbage** [DS-13-Dev-Team/DS13-1.0#1273]
#### Suggestion:
Add skill caps to each role, what this means is that for example a Planet Cracker might have their CQC and Weapons skill capped at 'Trained' so they can spend skill points to upgrade to 'Trained' but no further.

#### What do you think it'd add: 
This will help encourage skill points to be spent in skills that their role uses instead of all going towards maxing out CQC and Weapons skill. it will also stop role like Botanist from being able to have Master in CQC or a high weapons skill which doesn't really make sense.

**Comment by Snypehunter007** [comment]
@Icedcabbage This system already exists, it is mostly just an oversight on my part when I was re-defining skills that I didn't think of skills caps for most roles.

So, I'll tentatively mark this as accepted.
