### ISSUE TITLE
Suggestion: Add more surgeries

### ISSUE THREAD

**Issue by reklaw9** [DS-13-Dev-Team/DS13-1.0#1282]
#### Suggestion:
(NOTE: **not a coder** or anything like that, im just making a suggestion)
Add more surgeries, some examples 

Experienced surgical skill:
"Skin Grafting Surgery" heals 20 units of burn damage:  Scalpel>scalpel>cautery
"Suturing" Heals 5 to 10 units of brute damage and stops bleeding: hemostat>cautery

 Master surgical skill:
"external bone healing" Causes extreme pain but instantly fixes a bone: Bonesetter/wrench
"advanced suturing" can stop arterial bleedings and heals 10-20 of brute damage: Hemostat>cautery

#### What do you think it'd add:
Skin Grafiting and suturing adds a way to heal limbs fast without chemicals  
External bone healing and Advanced suturing gives surgeons/SMOs a "advantage" over normal doctors, surgeons currently only have the advantage of being able to do surgery and doing surgery faster and with a bigger success rate

**Comment by JakeDaBoss** [comment]
> #### Suggestion:
> (NOTE: **not a coder** or anything like that, im just making a suggestion)
> Add more surgeries, some examples
> 
> Experienced surgical skill:
> "Skin Grafting Surgery" heals 20 units of burn damage: Scalpel>scalpel>cautery
> "Suturing" Heals 5 to 10 units of brute damage and stops bleeding: hemostat>cautery
> 
> Master surgical skill:
> "external bone healing" Causes extreme pain but instantly fixes a bone: Bonesetter/wrench
> "advanced suturing" can stop arterial bleedings and heals 10-20 of brute damage: Hemostat>cautery
> 
> #### What do you think it'd add:
> Skin Grafiting and suturing adds a way to heal limbs fast without chemicals
> External bone healing and Advanced suturing gives surgeons/SMOs a "advantage" over normal doctors, surgeons currently only have the advantage of being able to do surgery and doing surgery faster and with a bigger success rate

Some of these seem more like ghetto surgery, and I like it. Maybe I'll be able to look into it.

**Comment by NanakoAC** [comment]
these seem a bit unfitting with the theme. They probably wouldn't be bad, but a lot of medicine in this universe is high tech
magic healing chemicals, zero g treatment rooms
automated laser scalpels, eyeball needle machines
and whatever that huge machine in ishimura's medical department was

These wouldn't be wholly out of place nor inherently bad, but if work were to be done on medical i feel like some of the above examples would be a better use of dev time in realising the vision of the dead space universe

TL:dr, i'm neutral about this

**Comment by ghost** [comment]
Suturing and the Bone Healing would be the only things I'd consider adding, and even then, I would categorize this as low priority.
