### ISSUE TITLE
BUG: most roles are able to have "master" on surgical skill, while doctors can't

### ISSUE THREAD

**Issue by reklaw9** [DS-13-Dev-Team/DS13-1.0#1283]
#### Description of issue:
A doctor can only have Experienced surgical skill, while a BARTENDER can have master surgical skill

#### Difference between expected and actual behavior:
Surgeons and SMOs being the only role able to have master surgery

Doctors are the only people on the entire ship that can't have master surgical skill

**Comment by JakeDaBoss** [comment]
> #### Description of issue:
> A doctor can only have Experienced surgical skill, while a BARTENDER can have master surgical skill
> 
> #### Difference between expected and actual behavior:
> Surgeons and SMOs being the only role able to have master surgery
> 
> Doctors are the only people on the entire ship that can't have master surgical skill
> 
> #### Steps to reproduce:

Known issue. Related issue: #1273

**Comment by Snypehunter007** [comment]
Hm, I suppose this was an oversight on my part when redefining skills. I'll fix that.

This is an intentional choice though, to not have doctors able to do max level surgery.
