### ISSUE TITLE
Aegis VII Atmospherics

### ISSUE THREAD

**Issue by JakeDaBoss** [DS-13-Dev-Team/DS13-1.0#1293]
#### Description of issue:
Aegis VII has no atmospherics currently, operating as if it were in a vacuum.

#### Difference between expected and actual behavior:
Contrary to lore is how it currently operates. The plan is thus:
* Introduce new atmospherics that offers a stable pressure and oxygen rate.
* RIGs will remain to be necessary during some rounds. The temperature will vary from room-temperate 20-24C, to much higher which will cause overheating.
* Introduce a manner of gauging what's going on with Aegis each new round. (Round-start announcement including this information? Unknown.)
* Perhaps introduce a new, mapped weather station on the Aegis colony.

#### Intricate mapping changes:
* Storm shutters on all exterior windows. (Also, add more exterior windows.)
* New, remote station for weather monitoring (atmos station, basically, until a later, more meteorological purpose can be coded).
* Increase map size by 50-100 tiles across the board. (Bigger cave systems, more Marker spawns, etc.)
* Area changes to permanently make the colony lit up. (Look into exoplanet system, to see if sunlight emulation is present.)

#### Hopeful to introduce:
* Dust storms as a random map event. (Overlay sprites needed (Reminiscent of CM's weather module that causes freezing storms. Dust in light, medium and heavy variant overlays). Can be singularly coded for this map.)

**Comment by NanakoAC** [comment]
aegis should also not be dark (unless its nighttime there)

Before anything is done with mapping on this front, look into the baycode exoplanet system. its designed for this sort of thing and using it would be the best approach

**Comment by JakeDaBoss** [comment]
> aegis should also not be dark (unless its nighttime there)
> 
> Before anything is done with mapping on this front, look into the baycode exoplanet system. its designed for this sort of thing and using it would be the best approach

Correct, thank you. Though I can easily fix the darkness issue by disabling modular lighting iirc. That is, if a system doesn't already exist to emulate sunlight in exoplanets.

**Comment by NanakoAC** [comment]
i believe its highly likely that a sunlight system does exist, and we should use it. Bay's exoplanet system is designed for torch exploring the galaxy and landing on various planets, it'll be good for the planets in our universe, Aegis VII and Tau Volantis. I know it handles temperature and atmospheric composition, and i've seen planets with different lighting levels

Of course it will almost certainly need a bit of work to adapt to our needs, but it'll still be a strong foundation
