### ISSUE TITLE
Suggestion for limb based combat.

### ISSUE THREAD

**Issue by Greg-Joffer** [DS-13-Dev-Team/DS13-1.0#1301]
Suggestion- Make it so targeting groins on slashers, spitters, pukers, twitchers, enhaced slashers and the Hunter takes off both legs like targeting a groin on a human does.

What do I think this will add?

well necros have very high target priorities on the arm and head as the most common places necros aim to delib but necros can mutli delimb if they aim for the grion. I think the same should be applicable to the necros.

I talked to lion about it he said it was an oversight or bug.

**Comment by NanakoAC** [comment]
lion is incorrect here, this is by design. necromorphs don't have a groin, they use a simplified system of six limbs
