### ISSUE TITLE
Tool callback error

### ISSUE THREAD

**Issue by NanakoAC** [DS-13-Dev-Team/DS13-1.0#1324]
[10:03:19] Runtime in callbacks.dm, line 40: undefined proc or verb /obj/item/weapon/tool_modification/productivity/ratchet/work in progress(). 
proc name: Invoke (/datum/callback/proc/Invoke)
usr: Dawson Keyes (/mob/living/carbon/human) ([0x3000088]) (the deck) (50,134,3) (/turf/simulated/floor/tiled) (dawsonkeyes)
usr.loc: The deck (/turf/simulated/floor/tiled) ([0x101df0f]) (50,134,3) (/area/ishimura/lower/cargo/bay)
src: /datum/callback (/datum/callback)
call stack:
/datum/callback (/datum/callback): Invoke(Dawson Keyes (/mob/living/carbon/human), the combi driver (/obj/item/weapon/tool/screwdriver/combi_driver), 10)
do after(Dawson Keyes (/mob/living/carbon/human), 90, the combi driver (/obj/item/weapon/tool/screwdriver/combi_driver), 1, 1, 45, 0, 0, /datum/callback (/datum/callback), 10)
the ratcheting mechanism (/obj/item/weapon/tool_modification/productivity/ratchet): use tool extended(Dawson Keyes (/mob/living/carbon/human), the combi driver (/obj/item/weapon/tool/screwdriver/combi_driver), 90, null, 35, "construction", 110, 'sound/items/Ratchet.ogg', 25, /datum/callback (/datum/callback), 10)
the ratcheting mechanism (/obj/item/weapon/tool_modification/productivity/ratchet): use tool(Dawson Keyes (/mob/living/carbon/human), the combi driver (/obj/item/weapon/tool/screwdriver/combi_driver), 90, null, 35, "construction", 110, 'sound/items/Ratchet.ogg', 25, null, 10)
the ratcheting mechanism (/obj/item/weapon/tool_modification/productivity/ratchet): apply(the combi driver (/obj/item/weapon/tool/screwdriver/combi_driver), Dawson Keyes (/mob/living/carbon/human))
the ratcheting mechanism (/obj/item/weapon/tool_modification/productivity/ratchet): try apply(the combi driver (/obj/item/weapon/tool/screwdriver/combi_driver), Dawson Keyes (/mob/living/carbon/human))
the ratcheting mechanism (/obj/item/weapon/tool_modification/productivity/ratchet): afterattack(the combi driver (/obj/item/weapon/tool/screwdriver/combi_driver), Dawson Keyes (/mob/living/carbon/human), 1, "icon-x=22;icon-y=21;left=1;scr...")
Dawson Keyes (/mob/living/carbon/human): LeftClickOn(the combi driver (/obj/item/weapon/tool/screwdriver/combi_driver), "icon-x=22;icon-y=21;left=1;scr...")
Dawson Keyes (/mob/living/carbon/human): ClickOn(the combi driver (/obj/item/weapon/tool/screwdriver/combi_driver), "icon-x=22;icon-y=21;left=1;scr...")
/datum/click_handler/default (/datum/click_handler/default): OnClick(the combi driver (/obj/item/weapon/tool/screwdriver/combi_driver), "icon-x=22;icon-y=21;left=1;scr...")
the combi driver (/obj/item/weapon/tool/screwdriver/combi_driver): Click(null, "mapwindow.map", "icon-x=22;icon-y=21;left=1;scr...")

**Comment by Evankhell561** [comment]
this problem has already been solved.
