### ISSUE TITLE
Suggestion:Give doctors and surgeons access to maint

### ISSUE THREAD

**Issue by reklaw9** [DS-13-Dev-Team/DS13-1.0#1333]
#### Suggestion:
Give doctors and surgeons access to maint

#### What do you think it'd add:
a easier route to injured patients to doctors and surgeons (because surgeons have to act like First Responders sometimes)

**Comment by Snypehunter007** [comment]
No, medical personnel shouldn't have default access to maintenance outside of the maintenance connections attached to their department.

If it is a real emergency, you can have Bridge Staff grant maintenance access to everyone in a pinch.

Locking.
