### ISSUE TITLE
Bug: spawn points that you cannot escape from

### ISSUE THREAD

**Issue by reklaw9** [DS-13-Dev-Team/DS13-1.0#1339]
#### Description of issue:
if you set spawn to maint, you can spawn in locked rooms that you cannot possibly escape from if you do not have access

#### Difference between expected and actual behavior:
spawning in a room with no access to maint, but still not being locked in a place forever

spawning in a room and being locked in it
#### Steps to reproduce:
set spawn to maint, spawn and theres a chance that you will spawn on some place that you cannot escape from

**Comment by NanakoAC** [comment]
There are ways around this. You can call for help over the radio, and almost any door can be broken open with repeated hits, use whatever is around as a weapon
