### ISSUE TITLE
SOME BUGS: Certain Jobs are forced to waste points on certain skills needed for their job

### ISSUE THREAD

**Issue by reklaw9** [DS-13-Dev-Team/DS13-1.0#1365]
#### Description of issue:
1:surgeons have to waste one of their points in complex devices for robotic organ surgery 
2: surgeons also need athletics for when they need to pull patients in and out of medbay if theres no doctor/SMO

**Comment by Snypehunter007** [comment]
Most of this will be adjusted, to some extent, aside from number three, since we're having some discussion on that one more than just about skills.

**Comment by reklaw9** [comment]
one bug left, updated list of bugs

**Comment by reklaw9** [comment]
updated again

**Comment by reklaw9** [comment]
welp
