### ISSUE TITLE
SUGGESTION: give ID editing access to some heads and change how ID editing works

### ISSUE THREAD

**Issue by reklaw9** [DS-13-Dev-Team/DS13-1.0#1378]
####Suggestion:
Give the SMO, FL, Captain and Chief Security Officer ID editing access and make Editing access only be able to give access IF the "operator" has the certain access (Example, a SMO can only give access that he has to other people, meaning that he cannot give all access to anyone), i think that we already have the updated code with the "Give access if operator has access" thing, but im just putting it here incase we don't have it yet

####What do you think it'd add:
Having one or two persons with ID access is too dangerous, if one of them is killed and their IDs vanish nobody else can update IDs, Both SMO and CSO should have ID editing access for certain things (example: SMO Demoting someone who went crazy or revoking their access for the moment and the CSO removing a officer's access to the armory for safety).

The "Operator can only give access that they have to the ID that they have" thing is for safety just so people don't commit All Access.

**Comment by Snypehunter007** [comment]
Talked this over with West and we're not going to do this. Captain was intentionally and deliberately chosen as the only one to be able to change ID access for a reason to empower the role or finding the Captain's ID if they were to die to Necros.

Locking.
