### ISSUE TITLE
Suggestion:a big suggestion about comms restriction and etc.

### ISSUE THREAD

**Issue by reklaw9** [DS-13-Dev-Team/DS13-1.0#1388]
#### Suggestion:
Add a "Comms Officer" job, which needs to communicate what is happening between command, security, civilians and CEC.
Remove radios from Bartenders, botanists and chefs. 

Make miners, scientists and supply only able to talk in their own channel (EXAMPLE: miners only being able to talk in the mining channel).

Add a "Emergency Radio" which is a connection between the user and a Channel that Security and Medical have access to, make it a PDA thing so security actually needs to check their PDA.

Add a "Miss Use of Communications" and "causing panic" to the EarthGov Law "Book" in the wiki for when heads are being complete retards and causing extreme panic in civilians because "i CaN dO ThaT, Me uR BoSS?!". 

Remove the "SolNet Relay Chat Client" or make it only able to "sustain" 3 persons in one channel.
#### What do you think it'd add:
A job which has the sole job of talking to the station, explaining orders, communicating informations ("someone died in X place" and etc), repairing comms and Communicating to CEC using fax machines.

A Reason for civilians to talk with eachother more and for command to interact more with civilians.

The ability for command and Unitologists/EarthGov to lie to other people (Example 1: Captain says that everything is fine to the civilians, but alerts security and medical about the necros) (Example 2: unitologists say that command is lying about something, but command isn't)

A reason for Command/Chiefs/Heads to exist  (if i can talk directly to the captain or to a security officer in the radio, why would i need to talk with my boss which could be lying to me about what really is happening in the ship?)

**Comment by ghost** [comment]
We're working on test PRs similar to this already.
