### ISSUE TITLE
Bug: Necros can (sometimes) start with 2 offscreen brutes and multiple slashers (also marker starts with about 1500 "total" mass collected

### ISSUE THREAD

**Issue by Thegodemperorofmankind11** [DS-13-Dev-Team/DS13-1.0#1392]
#### Description of issue:
Necros can on occasion (it's not that rare I've seen it about 2 times per test.) the Necros can hear snoring from a brute (and some slashers.) these are located in the corner of the map in space at 7,7,1 (least for the round I was making this report.) the signals can posses these necros and move them on to the Ishimura by dogging or charging. (screenshots.)

#### Difference between expected and actual behavior:
Necros have multiple T3 round start and can spawn more.
![OH NO](https://user-images.githubusercontent.com/72474452/115971482-a33b6200-a540-11eb-8084-5af3a95f6c85.png)
![funny brute](https://user-images.githubusercontent.com/72474452/115971496-acc4ca00-a540-11eb-9115-6c97f1e4d2a5.png)
Also, this happens when there are NO admins on or moderators.

#### Steps to reproduce:
Unknown, however, if you hear Snoring that means that they have spawned.

**Comment by Thegodemperorofmankind11** [comment]
![Oh god](https://user-images.githubusercontent.com/72474452/115971576-13e27e80-a541-11eb-80d1-862fdaf80ff2.png)

**Comment by NanakoAC** [comment]
this is caused by things being briefly spawned to take pictures and read values for various menus, they should be deleted and not affect biomass. deinitely bug, will look into it
