### ISSUE TITLE
Bug: Non-ASCII symbols are not correctly displayed

### ISSUE THREAD

**Issue by Doster-d** [DS-13-Dev-Team/DS13-1.0#1425]
#### Description of issue:
Players can't typing non-ASCII symbols in admin help.
Players can't normally communicate in chat because sanitize procs break message

#### Difference between expected and actual behavior:
For say:
expected: Привет, мир!
actual: [broken character]ривет, мир!
For admin help:
expected: [admin_thing_to_take/close_ticket]: Как менять руки?
actual: [admin_thing_to_take/close_ticket]: [void]

#### Steps to reproduce:
1. Press F3
2. Enter message that contains non-ASCII symbols, ex. Привет, мир!
3. See broken message in chat

1. Press F1 -> any category
2. Enter message that contains non-ASCII symbols, ex. Привет, мир!
3. See admin help without message

**Comment by Doster-d** [comment]
![image](https://user-images.githubusercontent.com/63081538/118374654-14ad8400-b5c6-11eb-8bb6-07fda5a1fc2f.png)

**Comment by DeadLineSS13** [comment]
Fix Russian words can broke English words for english players

**Comment by Doster-d** [comment]
> Fix Russian words can broke English words for english players

If you use _char procs it wouldn't broke English words and will fix this issue.

**Comment by DeadLineSS13** [comment]
> > Fix Russian words can broke English words for english players
> 
> If you use _char procs it wouldn't broke English words and will fix this issue.

Already do it. As a result, /imporer does not work and I remember that DS13 could not even compile the build.

**Comment by DeadLineSS13** [comment]
I know what problems this fix method creates.

**Comment by Doster-d** [comment]
> Already do it. As a result, /imporer does not work and I remember that DS13 could not even compile the build.
> 

Strange. I done this with my branch and it was completely fine.
