### ISSUE TITLE
BUG: screen slides away after relog?

### ISSUE THREAD

**Issue by saltprjak** [DS-13-Dev-Team/DS13-1.0#143]
### Description of issue

the ingame screen slides away to the upper-right corner, becoming smaller, and leaving black borders in vacant space. http://prntscr.com/rgg0e4

#### Difference between expected and actual behavior

i dunno, chief, i don't think it's normal for the screen to shrink.

#### Steps to reproduce 

game crashed at one point after viewing a surgeon's id card, relogged and had this afterwards.

#### Length of time in which bug has been known to occur

Snypehunter said they know about it, so i suppose for some time. he asked me to upload a bug report still

#### Client version, Server revision & Game ID
Client Version: 513
Server Revision: 9ced6c46c4926a8ee127895616a34b9f14e050d2 - dev - 2020-03-14
Game ID: b6a-dmmx
Current map: USG Ishimura

**Comment by NanakoAC** [comment]
Known issue and it's been seen frequently, but I still lack a consistent way to reproduce it

**Comment by NanakoAC** [comment]
It happened to me when clicking on a jumplink in chat
several people have complained about it while recieving surgery, being in medical, and/or falling asleep
