### ISSUE TITLE
[SUGGESTION] Security armour reworking

### ISSUE THREAD

**Issue by 2kajowsmol** [DS-13-Dev-Team/DS13-1.0#1431]
#### **_Suggestion:_** 

- The suggestion is to remove Security RIGs from the Security Officer/Senior Security Officer's lockers, and have them replaced with armor vests(or jackets, such as in the movie). 
- It would not have the SEC RIGs removed, however, as they would instead be placed in the armory, where they would be removed in the event of an actual emergency. 
- This means that security guards don't spend the entire shift walking around in RIGs, (that they didn't even appear to have) and instead means that they are walking around in lightweight armor vests or jackets(they are on a civilian ship, afterall).

#### **_What do you think it'd add:_** 

- I believe it would add balance, and generally would fit the theme of the Ishimura better. 
- This isn't a military ship. They aren't going to be all walking around in security RIGs 24/7. They would probably be lightly armed, which is fine as they are now, but they most certainly shouldn't be walking around in RIGs, unless it's a code red or blue. 
- To conclude, I am of the opinion that the replacement of security RIGs with armour vests of some type in their lockers would balance them better, (pre outbreak) and allow for them to fit more closely with the original Ishimura security team.

**Comment by Snypehunter007** [comment]
This was done awhile ago, IDK why it didn't auto close.

Closing.
