### ISSUE TITLE
[Suggestion] security rig being reworked 

### ISSUE THREAD

**Issue by lamesace** [DS-13-Dev-Team/DS13-1.0#1440]
Suggestion: Maybe make it so when sprawl comes out Sec rigs are taken away from the ishimura or maybe add like 2 to armory
or you could just take it out from Ishimura right now. I also really dislike the sec rig sprite I recommend just making it a reskin of riot rig and changing it blue and stuff 

What do you think it'd add: Make the Ishimura more similar to the lore It would also make the other mostly unused security tools more useful and give it a reason to be there you can even give the sec the same vest CSECO has so they could have some protection but this is only a matter of lore vs gameplay I want lore because that's what the server said it was mostly based off of

**Comment by Snypehunter007** [comment]
We already have something in the works for this that address the first part, changing their gear and not providing the RIG suit as standard.

**Comment by Snypehunter007** [comment]
Just realized this is a duplicate of #1431.

Closing.
