### ISSUE TITLE
Suggestion: Add more RIG modules to RnD designs. 

### ISSUE THREAD

**Issue by DTraitor** [DS-13-Dev-Team/DS13-1.0#1450]
#### Suggestion: 
Add more RIG modules to RnD designs. 
Modules that can be added: kinesis, vitals monitor (normal and advanced), femoral exoskeleton (normal and avanced), internal storage compartments, maneuvering jets.
Also if it's possible add this modules: chem dispenser (empty, can be refilled with any chems) and grenade launcher (empty, can be loaded with grenades).

#### What do you think it'd add: 
It'll make easier to obtain some modules and RnD will be a bit more useful.

**Comment by ghost** [comment]
Long term goal will allow for this, closing for now.

**Comment by Snypehunter007** [comment]
Denied for now, is the reasoning.
