### ISSUE TITLE
BUG: R&D is fucked

### ISSUE THREAD

**Issue by Cairo283** [DS-13-Dev-Team/DS13-1.0#146]
#### Description of issue

The entirety of R&D is, both from a code standpoint and a mapping standpoint, gooched.

#### Difference between expected and actual behavior

R&D not only has pretty much no materials inside of the department at the start of a round to work with, a bunch of things in the protolathe are just completely missing or glitched. Most items just don't appear at all, showing only what it costs to make them, and some others are just missing half of their name, like bluespace beakers just being called "bluespace".

#### Steps to reproduce 

Click on the R&D console, go into the protolathe. Most of the starting buildable things will be un-buildable, due to their names missing.

#### Length of time in which bug has been known to occur

I assume since day one, since you guys haven't messed with R&D yet.

#### Client version, Server revision & Game ID

Server Revision: 9ced6c46c4926a8ee127895616a34b9f14e050d2 - dev - 2020-03-14

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by Snypehunter007** [comment]
Yeah, we know about it but thanks for formally posting the bug about it.

The relatively low amount of materials is due to wanting the miners to be vitally important to the ship when mining finally works.

**Comment by Cairo283** [comment]
Two things to add to this: Stacks of items are consumed when used in the deconstructive analyzer, resulting in the entire stack being deleted even if putting them in one at a time would result in a higher level gained.
Secondly if you do get around to working with R&D, please add proper levels to dead-space tools. A lot of them seem to just have "combat systems 1" on them, which is really lazy and boring to see.

**Comment by Snypehunter007** [comment]
Some starting materials have been added to research and the name bug has been fixed in #233 

Closing.
