### ISSUE TITLE
Suggestion: Make Necros Unable to choose where they attack on a person

### ISSUE THREAD

**Issue by Cairo283** [DS-13-Dev-Team/DS13-1.0#147]
Currently, a necromorph can just choose to target a human's head, often instantly killing them, through decap or paincrit, or their legs, rendering them unable to do anything since bay code doesn't let people without legs use their arms for some reason.

My suggestion is to remove letting necros target body parts on their own, instead making it random where they hit, or having them only able to attack a person's chest, to prevent fights from lasting half a second when fighting an unarmored human.

**Comment by NanakoAC** [comment]
the effectiveness of head attacking strategies is something we're looking at, I agree that it is too powerful. But in the case of something being unbalanced, the correct solution is to fix it, not remove the ability to use it. Limiting their ability to target bodyparts would essentially just be removing gameplay and strategy, simplifying things too much

**Comment by NanakoAC** [comment]
the recent defense overhaul has sort-of done what this PR asks, we won't be limiting the ability to target specific bodyparts though
