### ISSUE TITLE
BUG: Cannot open ribs in surgery

### ISSUE THREAD

**Issue by Snypehunter007** [DS-13-Dev-Team/DS13-1.0#148]
#### Description of issue
- Whenever you go to open to up someone's ribs in surgery to access the internal organs, you get a bug saying, "Cannot cut with incision in the way", or something like that.

#### Steps to reproduce 
- Start surgery.
- Use scalpel, then hemostat, then retractor.
- Try using the circular saw.

**Comment by freemysou1** [comment]
Can confirm that this isn't just to do with ribs, any form of bone does it chest, head, arms and legs.
