### ISSUE TITLE
Suggestion: Make shields block less damage.

### ISSUE THREAD

**Issue by MarshalRed** [DS-13-Dev-Team/DS13-1.0#1480]

**Comment by NanakoAC** [comment]
not explicitly accepting or denying, but some general notes;

-Held items take damage themselves when used to block hits, they will eventually break after absorbing enough damage.
-Shields are intended to make melee builds more viable, they can block hits from anything weaker than a brute
-Acid deals damage to worn and held items, it ought to be a decent counter to heavily shielded troops
-All blocking, shields included, is frontal only. It won't protect you from getting flanked/surrounded and slashed in the back
