### ISSUE TITLE
Suggestion: Make ammo much more sparse.

### ISSUE THREAD

**Issue by MarshalRed** [DS-13-Dev-Team/DS13-1.0#1483]

**Comment by NanakoAC** [comment]
While isaac doesn't find a lot of ammo, he has a magical angel watching over him who makes sure all the ammo he DOES find is miraculously for one of the guns he has currently equipped.

We have just as many guns, but implementing such a filtering mechanism in an uninstanced multiplayer game is not so feasible. For any given ammo drop, the odds are pretty high that it's made for a gun that you've not seen all round and probably won't. The odds of finding ammo you can actually use are relatively low
