### ISSUE TITLE
Suggestion: add a security device that overrides the rig lock

### ISSUE THREAD

**Issue by blackwolf602** [DS-13-Dev-Team/DS13-1.0#1515]
Suggestion:

Add a device similar to medical rig retraction device except it doesn't ask for permission to retract the rig. Possibly for head sec only or a limited amount for sec.

What do you think it'd add:

I believe it would help sec with controlling the people they have locked up. since flashes won't work with anyone wearing a helmeted rig and the fact that people can still use the built in modules even after capture examples are (kinesis, grenades, flash, rcd, and taser) and the fact you cannot force them to remove the rig (without killing them) or being able to check the rig for any contraband. So I believe a device that can force the rig to retract without the consent of an unwilling person or prisoner would improve the sec role and make sense within the ship.

**Comment by Snypehunter007** [comment]
I know this came before the following issue, but since the other one has been accepted already, I'm going to close this one.

https://github.com/DS-13-Dev-Team/DS13/issues/1634

Duplicate. Closing.
