### ISSUE TITLE
Bug: Camera Issues, Ubermorph

### ISSUE THREAD

**Issue by freemysou1** [DS-13-Dev-Team/DS13-1.0#156]
#### Description of issue

Camera issues, Ubermorph

Upon being attacked by a Ubermorph causes the attacked players screen to completely bug out,

Upon ghosting/evacuating as a Ubermorph causes the linked player's screen to bug out.

#### Difference between expected and actual behavior

The camera shouldn't be off-centering to the Top Right corner.

#### Steps to reproduce 

Evacuating:

1. Spawn as a Ubermorph
2. Evacuate, Aghost or Ghost as said Ubermorph.

Attacking (Requires 2 people):

1. Spawn as an Ubermorph
2. Attack a player

#### Specific information for locating

Not Applicable 

#### Length of time in which bug has been known to occur

Not Applicable (Hosted Server)

#### Client version, Server revision & Game ID

Byond Beta 513
Lastest Dev Build (Hosted Server)

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by Snypehunter007** [comment]
Really this and #155 should in the same thing Free.

And also potentially tied into #143.
