### ISSUE TITLE
Suggestion: suggestion dump

### ISSUE THREAD

**Issue by ghost** [DS-13-Dev-Team/DS13-1.0#1565]
#### What do you think it'd add: currently they can be spammed making them difficult and annoying to fight, making them have longer ability times gives humans more of a fighting chance and makes playing necro harder than just "click button"

--------

#### What do you think it'd add: necros being able to target limbs means they can just disable you from fighting easily by cutting off your hands, making them unfair for anyone who doesn't have strong armor to fight.

--------

#### What do you think it'd add: it'd make fire more balanced as to see where its actually affecting, and would be much less laggy and buggy than the current particle fire

--------

#### What do you think it'd add: currently getting hit by a pebble will crit you from pain, or make you extremely slow, making it so unless you have painkillers you're likely dead

--------

#### What do you think it'd add: currently the only way to fully heal from lots of damage is chems, which most of the crew don't have access to, unless they have a medical ID or get lucky with finding medkits in maintenance

--------

#### What do you think it'd add: with the bigger necros it's much harder to hit people when they're covered by your sprite, so having a client-only option to change that would provide a nicer experience to the necros

--------

#### What do you think it'd add: from what I've seen, necros can use disarm making them hard to fight when they just keep knocking whatever you're holding out of your hand, making it so they can't do this would make them more fair to fight (and they have no use for help intent)

**Comment by DTraitor** [comment]
> Suggestion: necros shouldn't be able to target limbs

~This will be discussed. The best option I can imagine is to randomise limb on each hit.~
Denied, blocking system was added to prevent necros using head target.

> pain thresholds need to be lowered

I'll take a look on adrenaline. Technically it should act as good painkiller but not for long.

> being able to fully heal from physical healing items

Dead Space medkits should fix this problem once someone will make them.

**Comment by Snypehunter007** [comment]
Do it again, but follow the rules for posting suggestions and not put multiple suggestions in one, @Serxule.

EDIT: Apparently we forgot to add it to the list for the rules, despite me having it written down here. Apologies about that. It'll be added to the default text when you open an issue.
