### ISSUE TITLE
Suggestions: Several

### ISSUE THREAD

**Issue by YellowKingThe** [DS-13-Dev-Team/DS13-1.0#1567]
#### Suggestion:
Add investigative tools to the Earthgov Telecrystal purchases, things like recorders, cameras, wire tappers, ect.

#### What do you think it'd add:
It will allow the Earthgov agent to actually feel like an investigator and not just have a big list of mostly combat related things to pick up.

#### Suggestion:
Make loadouts per job instead of per character.

#### What do you think it'd add:
Loadouts should be themed to a job largely anyways, the items a Reaserch Assistant would carry on them would not be the same as a Sec officer would need, could also restrict items based on job so security officers/bridge crew for instance, could buy extra ammo with their points potentially but other jobs couldn't.

#### Suggestion:
Increase Movespeed

#### What do you think it'd add:
Movespeed is very slow currently especially for unarmored people, it is practically impossible to outrun necros which means if you don't kit up early, IE before the threat starts there is a high chance of just getting instantly gibbed because a single hit can easily pain crit you and lead to you being dead.

#### Suggestion:
Restrict number of antags by population

#### What do you think it'd add:
Currently the pop of the server drastically changes how antag roles act, if there are three unitologists on a 20 pop server they will act much more brazen then on a 30 pop because of how much larger of a percentage of the crew they are. This would make it so that this issue is lessened in lower pop rounds.

**Comment by DTraitor** [comment]
> Increase Movespeed

You can use shift to run.

> Restrict number of antags by population

I'll take a look. I don't know why we don't have it yet

**Comment by Snypehunter007** [comment]
Do it again, this time follow the rules for not posting several suggestions in one, @YellowKingThe .

EDIT: Apparently we forgot to add it to the list for the rules, despite me having it written down here. Apologies about that. It'll be added to the default text when you open an issue.
