### ISSUE TITLE
BUG: Marker can be dissasembled

### ISSUE THREAD

**Issue by Ketrai** [DS-13-Dev-Team/DS13-1.0#157]
#### Description of issue
Isaac did it all wrong

#### Difference between expected and actual behavior
applying tools works to the marker as it's a structure; it can be wrenched, and then taken apart with a screwdriver, destroying it.

#### Steps to reproduce 
use tools on marker

**Comment by Ketrai** [comment]
Double checking, it appears welder bombs and other explosions just outright destroy the marker.

**Comment by Snypehunter007** [comment]
Aetsuki and Free also noted this during their private testing.
