### ISSUE TITLE
Necrovision is spotty.

### ISSUE THREAD

**Issue by Ketrai** [DS-13-Dev-Team/DS13-1.0#158]
#### Description of issue
Necrovision doesn't always update properly. it gets stuck on places, wether or not an eye or corruption has vision of the area.

#### Difference between expected and actual behavior
for corruption/eye to give vision.

#### Steps to reproduce 
Toy around with corruption and nodes, see if they give vision everywhere?x

![image](https://user-images.githubusercontent.com/28861083/76712393-c3cba280-6718-11ea-8856-414250df910a.png)

**Comment by NanakoAC** [comment]
known issue, but i'm not sure exactly why it's happening. Visualnet code is complicated and hard to debug.

placing something that would affect it seems to force an update, so its not major, but definitely should be addressed
