### ISSUE TITLE
SUGGESTION: Give Medical Staff Access to Chemestry

### ISSUE THREAD

**Issue by Greg351** [DS-13-Dev-Team/DS13-1.0#160]
Doctors, including the Senior Medical Officer, don't have access to Chemistry by default. This can make their job difficult, as they're locked out of useful chems such as Peridaxon, Dexalin+ or Bicaridine.

Currently, the only way of getting into this area is having a scientist open it for you, but this may not always be an option, since they could be busy or dead in a place where you can't snatch their ID.

Since it's locked behind the Science department, I propose giving them **_SOME_** access to science so they can get in, make their stuff, then get out. Not enough to let a doctor toy around with R&D, just enough to let them make healing juice.

**Comment by Snypehunter007** [comment]
The point of Chemistry being inside Research is for Research Assistants to man it and communicate with the doctors.

**Comment by Snypehunter007** [comment]
Just re-read this suggestion and checked the code @Greg351.

It was a bug that the SMO's don't have access to Research doors to get into Chemistry.

Ironically, we gave the SMO's access to Chemistry to specifically fill in for if there is no Research Assistants or a Chief Research Officer available but we forgot to give them Research access so they could even reach the Chemistry doors, lol.

I'll add that in with the next branch, hopefully that will satisfy the problem you have with it?

**Comment by Snypehunter007** [comment]
Given the lack of comment back, I'm going to deny this suggestion as I think that the bugfix alleviates this problem.

Locking.
