### ISSUE TITLE
BUG: Stairs & Ladders get destroyed constantly.

### ISSUE THREAD

**Issue by Ketrai** [DS-13-Dev-Team/DS13-1.0#1605]
#### Description of issue:
Explosions especially. But even just shooting them or charging at them can destroy a stair/ladder. They're pretty essential.

#### Difference between expected and actual behavior:
They kinda should just be invulnerable. To avoid cheese from both sides.

**Comment by NanakoAC** [comment]
as a minor feature, i'm thinking that they should be allowed to be broken, but not deleted, instead getting set into a broken state with a different sprite, and taking significantly more time (and stamina) to climb up and down until repaired

Would you feel up to making some sprites for broken ladders and collapsed stairwells?
