### ISSUE TITLE
Suggestion: Make Bolas Actually Useful

### ISSUE THREAD

**Issue by Thegodemperorofmankind11** [DS-13-Dev-Team/DS13-1.0#1608]
Suggestion:Make Bolas Useful

 What do you think it'd add:
It'll mean sec can actually take people in Non-lethally, Currently the Bola does a slight Movement de-buff the person hit by it can still shoot, Move, and the time to remove it is like half a second.
What I propose. 
1) Buff the Bola, make it knock people to the ground, and disable their hands, allowing sec to cuff them.

2) Add an Incentive to actually use it, Currently sec just rocks Pulse rifles always, for Antagonist situations, And kills the Uni afterwords anyway. As, there's no reason to take them alive. (At least for the Valid hunters.) To touch on this, I've had multiple times when I've surrendered, Been Incapacitated, Or Came in peacefully, only for sec to shoot me, for committing a crime (Which they have no proof of other than hearsay.) Update the EarthGov Law book, add in incentives, could be money could be a way to loyalty implant them, Whatever, just make sure a player game doesn't end due to sec opening up with guns.

3) make it, so security doesn't need to grab to apply cuffs.

4) Add additional Non-lethal weapons, like a Net gun, Non-lethal gas grenade Etc Make necros immune to them, or the players WILL abuse it.

**Comment by Snypehunter007** [comment]
Bolas should probably just be made into a net gun, as originally designed. The weird lethal/non-lethal combo doesn't work.

**Comment by NanakoAC** [comment]
We are aware that the bolas are a bit weak, they will be looked at in the coming balancing season
