### ISSUE TITLE
Buff or standardize Exploder explosions.

### ISSUE THREAD

**Issue by Greg-Joffer** [DS-13-Dev-Team/DS13-1.0#1616]
Right now Exploders are wildly different on performance and vary in how damage they do, due to RIGs and Armour.

I think explosions should be buffed to add more risk for Un armoured opponents rather than them getting away with minor bruises and burns even from an enhanced exploder (which as acid fire and shrapnel too) 

This will add more consistently to exploders and their damage they deal to both players and the environment, rather than nuking the entirety of the ship into lattices where explosions meet no resistance and travel for ages.

**Comment by lamesace** [comment]
I agree we should buff them
