### ISSUE TITLE
(Suggestion) Frantic Growth needs to go

### ISSUE THREAD

**Issue by lamesace** [DS-13-Dev-Team/DS13-1.0#1617]
-->

**Comment by Survivor23** [comment]
Remember that part in dead space when the walls surrounded isaac in a box?

While we're on this topic, make Maws not be able to be lined up. They are like walls, except they are far more durable and they kill you if you walk on them.

**Comment by ToroidalZer0** [comment]
Could also apply this to cysts, and not have like 5 of them lined up on a singular wall, prevent defensive growths from being planted adjacent to each other.

**Comment by NanakoAC** [comment]
the main purpose of frantic growth is to create a vision-blocking screen behind which normal things can be placed. They aren't really be meant to block in players, but to briefly block OUT players, just for a few seconds, while you hastily construct a better defense behind it.

To better fit this purpose i'm planning to give frantic growth a minimum range, it'll have to be placed at least a certain distance from crewmen

**Comment by NanakoAC** [comment]
> 
> 
> Remember that part in dead space when the walls surrounded isaac in a box?
> 
> While we're on this topic, make Maws not be able to be lined up. They are like walls, except they are far more durable and they kill you if you walk on them.

this is actually off the topic and doesn't really fit here, but worth noting, maws, much like beartraps, are designed to be a threat to loners. Its easier to free someone else from one than freeing yourself, and also much easier if you use a tool.
Simply get a friend with a crowbar to follow you around and you shouldn't have any trouble with them

**Comment by lamesace** [comment]
Maws have there place in ds13 but frantic growth I've never seen a single positive thing in those I hope the get a nerf of some kind or removed

**Comment by Survivor23** [comment]
Placing Maws in rows of 3 to block hallways from being used is excessive. Worse is when they are placed at the top of stairs, so if you don't use the "Look up" verb that basically no one knows exist, you will switch z levels and IMMEDIATELY be Maw trapped.

**Comment by Survivor23** [comment]
> 
> 
> Placing Maws in rows of 3 to block hallways from being used is excessive. Worse is when they are placed at the top of stairs, so if you don't use the "Look up" verb that basically no one knows exist, you will switch z levels and IMMEDIATELY be Maw trapped.

Not to mention, they are incredibly tanky and can't just be removed like walls can. It takes way more time.
