### ISSUE TITLE
[Bug] Manual Restart after round is delayed does not come back up.

### ISSUE THREAD

**Issue by MarshalRed** [DS-13-Dev-Team/DS13-1.0#1621]
#### Description of issue:
Manually Restarting after a delay to the round seems to stop the server. Usually occurs after very 'busy' rounds.(Explosions/Atmos Issues/High-Moderate Player Count)

#### Difference between expected and actual behavior:
Shouldn't crash the server box.

#### Steps to reproduce:
I really don't know.

**Comment by NanakoAC** [comment]
Does it work fine in busy times when no delay has been used?
Does it work at quiet times when the round is delayed?

**Comment by MarshalRed** [comment]
Usually, but sometimes it has issues even then. Haven't tested when rounds aren't delayed.
