### ISSUE TITLE
More infector bugs.

### ISSUE THREAD

**Issue by Ketrai** [DS-13-Dev-Team/DS13-1.0#1628]
- [x] Infectors can still use parasitic leap on other necromorphs. (when they're standing or buckled
- [x] spine shot has no cooldown
- [x] DOUBLE CHECK TO MAKE SURE THEY DON'T SPAWN EXTRA BIOMASS WHEN THEIR NECROS DIE. (Although this might be because of execute, and the fact conversions spawn gibs. Consider lowering the execution bonus to 2KG or something, the gibs are usually 4-8 KG already anyways.
- [x] They can drag during a flap, which is obviously unfun for humans and necros alike
- [x] decapitated humans can be turned via reanimate
- [x] engorge can be cast on already engorged necromorph. Does nothing, retracts bio
- [ ] reanimate can be cancelled, which is fine, but it doesn't refund essence.
- [ ] Can't heal missing limbs with mend
- [x] mend still uses the engorge description... did you overwrite your own changes?

SUGGESTION.

- [x] Mend is more expensive than reanimate on average. Would it be possible to cure 1/3rd the amount healed as a reduction in lasting damage taken to make it more worthwhile? Currently only the marker can do it, and wasting a rebuild on a robust infector or enhanced is quite wasteful.

**Comment by NanakoAC** [comment]
>reanimate can be cancelled, which is fine, but it doesn't refund essence.
Cannot reproduce this, refund is working fine on cancellation
