### ISSUE TITLE
SUGGESTION: Corpse landmarks are very lacking.

### ISSUE THREAD

**Issue by Ketrai** [DS-13-Dev-Team/DS13-1.0#163]
#### Description of issue
/obj/effect/landmark/corpse/chef
/doctor
/engineer
/scientist
/miner
/bridgeofficer
All spawn completely naked. 

There are no new corpses for special DS13 roles yet.

#### Difference between expected and actual behavior
Corpses to spawn with gear.

#### Steps to reproduce 
Be admin. Spawn a landmark corpse.

#### Specific information for locating
code/modules/awaymissions/corpse.dm
outfits link to
code/datums/outfits.

**Comment by Snypehunter007** [comment]
TBF, we don't really have a need for corpses at the moment.

**Comment by JakeDaBoss** [comment]
Recently checked into this:
/obj/effect/landmark/corpse/bridgeofficer
	name = "Bridge Officer"
	corpse_outfits = /decl/hierarchy/outfit/job/command/bo

Apparently they spawn with outfits now.

@Ketrai can you confirm whether or not they spawn with outfits now, and tag me in a response on this issue?

**Comment by Snypehunter007** [comment]
This was fixed a while ago, just checked.

Closing.
