### ISSUE TITLE
Suggestion: Rig Retractor

### ISSUE THREAD

**Issue by YellowKingThe** [DS-13-Dev-Team/DS13-1.0#1634]
#### Suggestion: 
Rig retractors should not require consent, or should have a version that does not ask for consent for emergency uses. Also rig retractors should not ask for consent from unconscious targets.

#### What do you think it'd add:
It will allow Sec,/Doctors remove rigs from people who are resistant without killing them.

**Comment by Snypehunter007** [comment]
Yeah, this should already be a thing, idk why it isn't.

**Comment by NanakoAC** [comment]
Have you actually tested this?

The consent comes with a timeout, and the rig is retracted if no response is given. This behaviour is intended to accomodate unconscious targets.

If someone won't cooperate, you can either sedate them and use it like above, or use rig removal surgery to physically cut it off of them

The rig remover is a tool for medical treatment, not law enforcement. There is no way to forcibly remove the rig of someone who is alive, conscious, and fighting back, this is intended

**Comment by Snypehunter007** [comment]
> Have you actually tested this?
> 
> The consent comes with a timeout, and the rig is retracted if no response is given. This behaviour is intended to accomodate unconscious targets.
> 
> If someone won't cooperate, you can either sedate them and use it like above, or use rig removal surgery to physically cut it off of them
> 
> The rig remover is a tool for medical treatment, not law enforcement. There is no way to forcibly remove the rig of someone who is alive, conscious, and fighting back, this is intended

For sec, they need to get RIGs off of people. Knocking someone unconscious to then be able to use a tool to remove a RIG, is an unnecessary step and absurd step.

**Comment by ghost** [comment]
@NanakoAC @Snypehunter007 I'm inclined to agree that there shouldn't be a matter of consent. Security needs to be able to wrestle people out of RIGs.

**Comment by YellowKingThe** [comment]
> 
> 
> Have you actually tested this?
> 
> The consent comes with a timeout, and the rig is retracted if no response is given. This behaviour is intended to accomodate unconscious targets.
> 
> If someone won't cooperate, you can either sedate them and use it like above, or use rig removal surgery to physically cut it off of them
> 
> The rig remover is a tool for medical treatment, not law enforcement. There is no way to forcibly remove the rig of someone who is alive, conscious, and fighting back, this is intended

When you are unconscious it still asks you for consent in a pop up, if it is not supposed to then that is a bug.
