### ISSUE TITLE
Bug:Infector can't execute people that are unconscious or resting.

### ISSUE THREAD

**Issue by reklaw9** [DS-13-Dev-Team/DS13-1.0#1636]
#### Description of issue:
Infectors can't transform or execute people that are not standing up.

#### Difference between expected and actual behavior:
Being Able to execute or transform people that are unconscious because they can't resist and are almost dead 

jump over downed guy, it seems that infectors don't like to touch bodies
#### Steps to reproduce:
find guy at the floor > try to use parasitic leap ont he guy > f a i l

**Comment by NanakoAC** [comment]
not a bug, the descriptions clearl state as such. Gotta get him before you knock him out, or after he's dead
