### ISSUE TITLE
Bug(?): people can still use items while being "hugged" by a infector

### ISSUE THREAD

**Issue by reklaw9** [DS-13-Dev-Team/DS13-1.0#1637]
#### Description of issue:
People are still able to fully pick up and use items(using items isn't exactly the problem, its more being able to grab your pulse rifle and shoot it at the infector) when they are having to fight for their live against a creature twice their size thats trying to make kebab out of their head

#### Difference between expected and actual behavior:
people not being able to use guns or huge tools while grappling for their live, or atleast not being able to pick them up.

people can simply say "hold up infector, stop trying to kill me and let me grab my gun before we can continue grappling" and grab their gun.
#### Steps to reproduce:
have a human get parasite leaped at> tell the human to try to pick any of his guns/stuff

**Comment by NanakoAC** [comment]
This is fully intended, you are not helpless, and infectors are physically weak.

When it jumps on your face, you are supposed to fight back and try to kill it before it turns you
