### ISSUE TITLE
Suggestion: make infectors able to eat dead bodies for essence

### ISSUE THREAD

**Issue by reklaw9** [DS-13-Dev-Team/DS13-1.0#1638]
#### Suggestion:
Make infectors able to eat dead bodies(of humans and necros alike) for essence, necro bodies equal to 0.8 essence, human bodies equal to 6.0(one per limb) essence, the whole process takes 20 seconds and at the end only leaves the dead body's clothings and some gibs behind

#### What do you think it'd add:
a way to get essence faster and a new ability for the infector, and a way to clean up dead bodies so they don't alert any survivors further into the round.

**Comment by NanakoAC** [comment]
The ability to devour corpses is something i have planned in future, but it will be an ability for new, different necromorphs which don't currently exist.

No existing necromorph is going to be able to do this

If you want to hide evidence, you could drag the body away (with a non-infector necro) and use signals to clean up the blood. The gameplay possibility of stealthy necromorphs isn't exactly supported yet, it could work, however corpse devouring isnt the way to do it
