### ISSUE TITLE
BUG: ADS Floor

### ISSUE THREAD

**Issue by YellowKingThe** [DS-13-Dev-Team/DS13-1.0#1640]
#### Description of issue:
The ADS floor can not be pried up

#### Difference between expected and actual behavior:
Floors should be able to be pried up to expose wires

#### Steps to reproduce:
Crowbar ADS floor.

**Comment by DTraitor** [comment]
It's kinda intended. ADS is a protected room. You can't break walls that leads to it and you can't break floor. That would make things too easy.

**Comment by YellowKingThe** [comment]
Then the APC should also be unbreakable, because you can not fix it from what I can tell.
