### ISSUE TITLE
Bug: infectors and leapers can't leap over open spaces

### ISSUE THREAD

**Issue by reklaw9** [DS-13-Dev-Team/DS13-1.0#1652]
#### Description of issue:
Infectors and leapers aren't able to leap/fly over open spaces(no i don't mean walking, but leaping/jumping)

#### Difference between expected and actual behavior:
a infector being able to fly over a open space, cause you know, they can fly
a leaper being able to jump over a open space, cause you know, they are jumping over it

falls
falls

**Comment by NanakoAC** [comment]
Fixed in #1684
