### ISSUE TITLE
MULTIPLE Bugs: some infector bugs that i have found(duplicates included)

### ISSUE THREAD

**Issue by reklaw9** [DS-13-Dev-Team/DS13-1.0#1655]
- [ ] after "parasitic leaping" someone the infector sprite gets bugged

- [ ] infectors can't walk over tables

- [ ] infectors can't pull, push or jump over heaters, scrubbers and others

- [ ] infectors can't force doors open(infectors are made mostly out of bone and muscle, plus, they have hands, unlike slashers.)

- [ ] infectors can't pull chairs

- [ ] infectors can't pull lockers

- [ ] if a infector "parasitic leaps" someone that is dead but still standing(like on a chair), their ability will be put on cooldown, and nothing else will happen

- [ ] if someone willingly uses rest, they become immune to the infector's parasitic leap

- [ ] infectors can't grab(not pull) dead bodies

- [ ] infectors(and leapers) can't jump over over spaces

- [ ] infectors take fall damage

- [ ] infectors can create multiple buildings on the same tile

- [ ] if a infector has no wings, it can't resist

- [ ] if a infector(or any other necro) loses it's head they will be considered a "unknown" in the necrochat

**Comment by Snypehunter007** [comment]
https://github.com/DS-13-Dev-Team/DS13/issues/1653

Duplicate. Closing.
