### ISSUE TITLE
Bug?: Rig Mounted Drill Melts walls

### ISSUE THREAD

**Issue by YellowKingThe** [DS-13-Dev-Team/DS13-1.0#1660]
#### Description of issue:
The rig mounted dimond drill melts through walls, I was able to cut through a reinforced plasteel wall in almost no time I think it was 2 or 3 hits.

#### Difference between expected and actual behavior:
Even a rig mounted drill should not melt plasteel walls.

#### Steps to reproduce:
Install the rig drill on a rig and use it on walls.

**Comment by Snypehunter007** [comment]
This is a problem with a lot of weapons, for example baseball bats and fire-axes do the same thing.

Edit: Actually, since this all a problem with the same system, Duplicate. Closing

https://github.com/DS-13-Dev-Team/DS13/issues/1073
