### ISSUE TITLE
Suggestion: Corpses Turn Into Infectors on Marker Activation

### ISSUE THREAD

**Issue by drfate786** [DS-13-Dev-Team/DS13-1.0#1661]
-->
#### Suggestion: 

All corpses in the morgue or within maints will turn into infectors upon marker activation. This would be a great addition with vent crawling and would allow necromorphs to be semi-present within the entire ship in a cat and mouse style of early game.

#### What do you think it'd add:

 It would make corpses in the early game a significant danger to the crew and allow for outbreaks of corruption and Necromorphs to occur everywhere on the ship as opposed to being confined to the Marker area. This would also force the crew into hunting down the infectors before any attempts to contain the Marker can be made, allowing corruption to spread far quicker on the lower levels of the ship.

Currently, all Necros spawn at the marker room at the start of a game and despite being told not to metagame most crew members will simply be present near the area to yell on their headsets.

**Comment by reklaw9** [comment]
20% of chance of turning into a infector, 30% of turning into a slasher, and the rest, nothing happens

**Comment by NanakoAC** [comment]
this isn't a direction we're going, at least as an automated thing. Some form of remote infection may be possible in future, but if implemented as decribed this would just cause a whole lot of metagaming and tossing every corpse out an airlock or into the supermatter
