### ISSUE TITLE
Reminder: Make it so pill bottles can be used easily one-handed.

### ISSUE THREAD

**Issue by Ketrai** [DS-13-Dev-Team/DS13-1.0#1668]
#### Suggestion:
If you target your own mouth whilst holding a pill bottle, you should be able to swallow pills.

#### What do you think it'd add:
It makes sense.

**Comment by Snypehunter007** [comment]
Idk, I'm really just imagining that you'd have to pour the entire bottle in your mouth. You can't exactly just get one pill that way.

I mean, you probably can, but it would be so difficult that you'd be better off just putting the bottle on a surface, twisting the top off one-handed, and plucking a pill out.

Or just pour all the pills out on a surface, take one, then pour the rest back in.

**Comment by DTraitor** [comment]
We have code for that already. It appears one var is missing and because of that the game thinks we target head instead of mouth. I'll fix it soon
