### ISSUE TITLE
Suggestions and Ideas for Outbreak Escalation I

### ISSUE THREAD

**Issue by Lucmio** [DS-13-Dev-Team/DS13-1.0#1674]
#### Suggestion: 

Instead of make the marker activate at a standard minute it can get activated from the minute a dead body appears. The dead body could be from any source (Murder, Suicide, Spawned by an Admin...etc.) and species (animals, humans, AI spawned by an Admin). 

#### What do you think it'd add:

The activation of the marker this way will regulate when the players and admins want to start the outbreak stage, letting them freedom to the survival stage.

**Comment by Snypehunter007** [comment]
This would hugely limit Admin events or could lead to the Marker activating soon after round start.

Denied. Closing.
