### ISSUE TITLE
Suggestions and Ideas for Outbreak Escalation III

### ISSUE THREAD

**Issue by Lucmio** [DS-13-Dev-Team/DS13-1.0#1676]
Suggestion:

Add a button for unitologist or humans to go crazy. That will give them some strenght bonus for 5 min but will commit suicide after those 5 minutes.

What do you think it'd add:

This will give unitologist a way to kill other people easily under the marker command or to normal people to survive or help others in exchange of their lifes. This could be a hard decision to make and could help players in some extreme situations or disadvantaged situations.

**Comment by Snypehunter007** [comment]
We plan on a psychosis system, but not like this.

Denied. Closing.
