### ISSUE TITLE
Suggestion: Make infectors able to infect dying people

### ISSUE THREAD

**Issue by reklaw9** [DS-13-Dev-Team/DS13-1.0#1682]
#### Suggestion:
make people able to parasitic leap dying/unconscious/resting people for lore reasons.

#### What do you think it'd add:
a more lore accurate infector parasitic leap and a better gameplay feature than what we currently have(dragging people to chairs to infect them)

**Comment by reklaw9** [comment]
might i add, that most players think that its a bug (mostly because it makes no sense) and that its honestly a bad feature both for lore and gameplay reasons

**Comment by Lucmio** [comment]
i completely agree

**Comment by lamesace** [comment]
I was just about to make a suggestion about this they should infect dying people too it's just so annoying that players have to fucking use bugs just to infect a guy on the ground
