### ISSUE TITLE
BUG: you can instantly stop infector executions

### ISSUE THREAD

**Issue by reklaw9** [DS-13-Dev-Team/DS13-1.0#1683]
#### Description of issue:
you can instantly stop infector executions by grabbing the infector and throwing it out of you, sometimes stunning it for 20 seconds, sometimes bugging it and getting damaged while having no infector on you

#### Difference between expected and actual behavior:
infectors must be killed or severely wounded to be removed

lol grab an throw
#### Steps to reproduce:
get a infector on you > grab infector > REINFORCE grab > throw away like trash

**Comment by Survivor23** [comment]
From what I understand, throwing infectors off of you is intended.

**Comment by reklaw9** [comment]
thing is, in that way you can instantly stop the infector's leap as soon as he gets on you

**Comment by lamesace** [comment]
It's intended and it's fucking chad feature

**Comment by Ketrai** [comment]
Not a bug, this is also an intentional feature. Severely injury your targets first.
