### ISSUE TITLE
Suggestion: make infectors able to pull/push stuff like any other necros

### ISSUE THREAD

**Issue by reklaw9** [DS-13-Dev-Team/DS13-1.0#1690]
#### Suggestion:
Make infectors able to pull/push stuff like any other necros

#### What do you think it'd add:
a better gameplay feature, currently because of this infectors can't pull lockers, pull dead bodies or do most stuff even tho they have two hands and a tentacle made to help the infector infect dead bodies without missing the head, BUT, slashers can do so without having any arms or hands

**Comment by lemshake** [comment]
okay but they have no hands

**Comment by reklaw9** [comment]
> okay but they have no hands

they do, its one of the only limbs(sure, only 3 huge fingers on each hand, but still) recognizable from when they were humans

**Comment by Ketrai** [comment]
Being unable to push/pull is intentional behavior right now.
