### ISSUE TITLE
Bug: Projectiles

### ISSUE THREAD

**Issue by YellowKingThe** [DS-13-Dev-Team/DS13-1.0#1697]
#### Description of issue:
Projectiles from humans don't seem to work right, I never got a gun so I was unable to test them, but my mining cutter did not shoot a projectile, I didn't think to check if my charge on it went down or not, but my rig mounted tazer was draining energy, and had no projectile and was apparently not harming anyone.
This seemed to be only human side as I saw lurker projectiles and was hit by them taking a good chunk of damage.

#### Difference between expected and actual behavior:
Projectiles should exist and do damage

#### Steps to reproduce:
Shoot something with projectiles

**Comment by Ketrai** [comment]
If this is related to the new box test. Please refrain from posting issues related to it for now. It's because of issues cloning the repo, so the resulting bugs aren't quite the usual kind, the overarching problem has to be fixed first.

**Comment by YellowKingThe** [comment]
All the bugs I posted around this time are related to the test, 
Westy asked to have them posted on the git, 
Sorry if that was counter productive.

**Comment by Ketrai** [comment]
> All the bugs I posted around this time are related to the test,
> Westy asked to have them posted on the git,
> Sorry if that was counter productive.

It seems the main bug is fixed but many still ensue. It's a good time to start reporting again.

**Comment by NanakoAC** [comment]
The plasma cutter does not fire any projectile, it hits instantly at the target and just creates a flash of light
