### ISSUE TITLE
Bug: No RIG Modules Tab

### ISSUE THREAD

**Issue by lemshake** [DS-13-Dev-Team/DS13-1.0#1702]
#### Description of issue:

The RIG modules tab has disappeared after the server was updated to have TGUI.

#### Difference between expected and actual behavior:

There should be a RIG modules tab to allow easier use of modules.
There actually isn't now that TGUI is in.

#### Steps to reproduce:
Equip a RIG, turn it on, and look for the RIG modules tab section.

**Comment by Ketrai** [comment]
This sounds like it's related to the new box test. Please refrain from posting issues regarding the new box test for now. It's due to issues cloning the repo, so these are all related to an overarching problem that needs to be fixed first.
