### ISSUE TITLE
BUG: TGUI doesn't works correctly

### ISSUE THREAD

**Issue by reklaw9** [DS-13-Dev-Team/DS13-1.0#1719]
#### Description of issue:
**Note: if this issue is closed because of a single duplicate while all the other bugs are still active i will simply copy and paste it back**
TGUI has multiple problems currently, some of them are:
admin PMs and necro chat being white
letters normally being smaller than normal(fixable in game)
HUD randomly stops existing (happened when changing it to PLAIN mode) and never comes back
"stat panel"(commonly referred as "Tab"s) doesn't appear sometimes, same with the "fix stat panel" thing
(examine)letters on normal mode are WAY too dark(
![image](https://user-images.githubusercontent.com/36147254/134347195-3cd1446c-beba-4618-9e55-04b06906de96.png)
)

Round time will normally be VERY wrong (
![image](https://user-images.githubusercontent.com/36147254/134349308-747c60fc-aa35-4f04-a2b4-92ed3535382b.png)
)

stat panel will always be white after clicking "fix stat panel" even if your preferences ask for dark mode(
![image](https://user-images.githubusercontent.com/36147254/134349436-90b931d4-2bab-4790-83de-a0dead834d19.png)
)

stat panel's "floor" tab appears at the end of the tabs simply as deck instead of floor, none of it's items has a icon on it and they also can't be clicked on (
![image](https://user-images.githubusercontent.com/36147254/134349652-102ca318-32a5-4a6a-af0e-a0ca65e9f1fd.png)
)

Necros have no HUD

Humans can't feel where the pain is on their HUD anymore

**Comment by DeadLineSS13** [comment]
> #### Description of issue:
> **Note: if this issue is closed because of a single duplicate while all the other bugs are still active i will simply copy and paste it back**
> TGUI has multiple problems currently, some of them are:
> admin PMs and necro chat being white
> letters normally being smaller than normal(fixable in game)
> HUD randomly stops existing (happened when changing it to PLAIN mode) and never comes back
> "stat panel"(commonly referred as "Tab"s) doesn't appear sometimes, same with the "fix stat panel" thing
> (examine)letters on normal mode are WAY too dark(
> ![image](https://user-images.githubusercontent.com/36147254/134347195-3cd1446c-beba-4618-9e55-04b06906de96.png)
> )
> 
> Round time will normally be VERY wrong (
> ![image](https://user-images.githubusercontent.com/36147254/134349308-747c60fc-aa35-4f04-a2b4-92ed3535382b.png)
> )
> 
> stat panel will always be white after clicking "fix stat panel" even if your preferences ask for dark mode(
> ![image](https://user-images.githubusercontent.com/36147254/134349436-90b931d4-2bab-4790-83de-a0dead834d19.png)
> )
> 
> stat panel's "floor" tab appears at the end of the tabs simply as deck instead of floor, none of it's items has a icon on it and they also can't be clicked on (
> ![image](https://user-images.githubusercontent.com/36147254/134349652-102ca318-32a5-4a6a-af0e-a0ca65e9f1fd.png)
> )
> 
> Necros have no HUD
> 
> Humans can't feel where the pain is on their HUD anymore
> 
> #### Difference between expected and actual behavior:
> #### Steps to reproduce:
> #### Suggestion:
> #### What do you think it'd add:

Make issues with problems. Alt Click fixed #1783

**Comment by reklaw9** [comment]
almost sure that this is fixed
