### ISSUE TITLE
SUGGESTION - Necro exception to KILLING ON SPOT rule

### ISSUE THREAD

**Issue by Lucmio** [DS-13-Dev-Team/DS13-1.0#1731]
#### Suggestion: 

Change the "must kill on spot" RULE of necros at the beginning of the outbreak, specially if they are non-combatant strains. 

#### Reason: 

According to media and lore necros just go "ninja" and act pretty shy if outnumbered, usually running away from people instead of engaging them until they are enough to handle them. Also certain necros on early stages act more passively, even avoid attacking. Infectors for example just hide until a body is ready for being reanimated... they also focus more isolated targets and even remain passive if overwhelmed.

#### What do you think it'd add:

Will give more freedom to necro players, not just going "killing-machine" mode.
Will delay the code blue procedure, giving usual RP as human more time.
Will give new interactions between humans and necros. For example studies about them.
Will give more deep development of personality of each necro.

**Comment by reklaw9** [comment]
thats just logic bruh, if you know that you will die if you charge you won't charge, the kill on spot rule is for weak/unarmored survivors

**Comment by Lucmio** [comment]
> thats just logic bruh, if you know that you will die if you charge you won't charge, the kill on spot rule is for weak/unarmored survivors

my suggestion goes farther than that, most necros just "ZERG RUSH" without a second thought and they justify by this rule, that is kinda dumb if you ask me.
