### ISSUE TITLE
Suggestion: Marker ability to kick signals from necro's

### ISSUE THREAD

**Issue by XtremeSavageXD** [DS-13-Dev-Team/DS13-1.0#174]
#### Description of issue
Give the marker player an ability to kick a player/signal from a live necro if their being AFK or just plain griefing or inexperienced.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by Ketrai** [comment]
I don't think people should be able to be forced out of a certain necro. You won't get the chance to get better as easily if you're restricted. Though I do agree that high tier necros are best left alone until people have at least a couple hours combat experience
