### ISSUE TITLE
Suggestion: some suggestions to make the ship spacing proof(no one really likes spacing)

### ISSUE THREAD

**Issue by reklaw9** [DS-13-Dev-Team/DS13-1.0#1747]
#### Suggestion:
add external indestructible firelocks to all EXTERNAL windows of the ship, that when detecting a breach will automatically close and never open

indestructible "Hull" walls to the exteriors of the ship

make it so external doors and firelocks close 30 seconds after being broken open if they detect atmospheric changes that may be lethal

**Comment by Lucmio** [comment]
Like the idea, if not unbreakable at least very resilient

**Comment by Snypehunter007** [comment]
Atmos will remain apart of our system for the foreseeable future, having firelocks that never open again is not what we want.

Denied. Closing.
