### ISSUE TITLE
Suggestion: Buff the health of the hands and the feet

### ISSUE THREAD

**Issue by reklaw9** [DS-13-Dev-Team/DS13-1.0#1754]
#### Suggestion:
buff the health of the hands and the feet, or maybe even make it so that they can't be cut off

#### What do you think it'd add:
A way to stop necros from instantly cutting off people's hands in a single charge/attack

**Comment by Snypehunter007** [comment]
We have a branch that is already merged about this, I'd suggest waiting.

Closing.
