### ISSUE TITLE
SUGGESTION: Hotkey fix

### ISSUE THREAD

**Issue by XtremeSavageXD** [DS-13-Dev-Team/DS13-1.0#176]
#### Description of issue
Doing ALT + Ctrl for a charge wile trying to move and aim is a bit too much for my fingers. I suggest you move every necro's main ability to middle mouse button or right mouse button for better ease. Then you could put the secondary ability on ctrl or alt without it being a hassle.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by NanakoAC** [comment]
Highly recommended to enable hotkey mode, and use WASD to move. That takes the middle three fingers (or just one)
Ctrl+Alt can be pressed with pinky and thumb, allowing right hand to leftclick

is this hard to do ?

**Comment by XtremeSavageXD** [comment]
I’m not saying it’s the hardest thing in the world to do, but it just seems that assigning every main ability to a singular easy to click button seems like a quality of life improvement

**Comment by NanakoAC** [comment]
it would also necessitate disabling the rightclick menu for necromorphs which they might object to. it can currently be used for targeting abilities if someone likes, or for pulling a particular corpse/object

**Comment by NanakoAC** [comment]
for now this is something we're not ready to do, but we may revisit it in future when more advanced necromorphs are added
