### ISSUE TITLE
BUG: EDF ERT Can't land in the Hanger anymore

### ISSUE THREAD

**Issue by JoJoMama25** [DS-13-Dev-Team/DS13-1.0#1765]
I think it started when the new server box got added. Basically, the Valor can't land in the hanger anymore because "the hanger is obstructed" so they have to jump down to the colony every time it's called. This issue only occurs with the Valor and not the kellion or the pilgrim.

**Comment by Snypehunter007** [comment]
Fixed in #1781 .

Closing.
