### ISSUE TITLE
Bug: Salvage Techs

### ISSUE THREAD

**Issue by YellowKingThe** [DS-13-Dev-Team/DS13-1.0#1767]
#### Description of issue:
Salvage techs don't have a sec hud icon and get no pay.

#### Difference between expected and actual behavior:
Cargo techs are not big red Xs and should make money at payday.

#### Steps to reproduce:
Play a salvage tech, look at them with a sec hud.

**Comment by DTraitor** [comment]
From what I know it's intended to get 0 money. They should find things in maints

**Comment by Snypehunter007** [comment]
> 
> 
> From what I know it's intended to get 0 money. They should find things in maints

Do they get paid for that though?

**Comment by YellowKingThe** [comment]
They get paid if they find schematics, but other jobs can find them and turn them in as well. Other then that they have to find peng or cred sticks, which other people can also find. There is currently no job unique way for them to get credits.
Granted other people doing that stuff in maints are breaking the law but that doesn't always stop them, also one ST can get all the money and leave nothing for the others if they are fast enough.
