### ISSUE TITLE
Aegis VII needs reworked

### ISSUE THREAD

**Issue by NanakoAC** [DS-13-Dev-Team/DS13-1.0#177]
The planetside colony has three major issues, in which it differs from dead space:

1. There is no light. The whole thing is pitch black. The caves should be dark, but outdoor areas ought to be brightly lit. Darkness is annoying for everyone

2. There is no air. Aegis in DS1 had a breathable atmosphere. This makes combat pretty unbalanced since one suit puncture is lethal

3. There is no gravity, the biggest issue. Necros are almost unable to move, constantly floating

**Comment by Snypehunter007** [comment]
I can look at 3, but 1 is impossible to change without giving the entire planet default lighting with no light change and 2 is a debatable.

**Comment by Ketrai** [comment]
I'd rather we don't have to look into completely rebalancing rigsuits and fighting with punctures. Even toxic air is better than no air, as that only slowly kills you if it's like... 5% co2  or something.

**Comment by Snypehunter007** [comment]
Points one and three have been fixed so, I'm going to close this one.
