### ISSUE TITLE
SUGGESTION: Make special rules or guidelines for Signals (Necro-horde)

### ISSUE THREAD

**Issue by Lucmio** [DS-13-Dev-Team/DS13-1.0#1785]
#### Suggestion: 

Make special rules for necro signals that regulate their behavour and/or make a proper guideline for them.

#### Reasons:

Most signals just spawm "kill yourself" whisp instead of elaborate or give a good atmosphere to other players.
Most signals focus just go into TDM and no in RP, and they pick on the ones RPing.
Most signals show trolling behaviour like sabotage other signals or even the Marker.

#### What do you think it'd add:

Will have Signals more regulated.
Signals will learn better and play better their role.
Rulebreaking as signal could be better documented and ticketed

**Comment by Snypehunter007** [comment]
@WestHybrid
