### ISSUE TITLE
Bug: Ishimura randomly underwent a bluespace jump.

### ISSUE THREAD

**Issue by JBlum2** [DS-13-Dev-Team/DS13-1.0#1795]
#### Description of issue:
During the round suddenly for myself and at least one other player, the screen turned a dark blue tint and we saw duplicates of ourselves. After touching my duplicate my character became brain dead. This guy from discord was the only person I managed to find who seemed to know what was going on, maybe it'll help. https://i.imgur.com/zmkevQV.png

#### Steps to reproduce:
No idea what caused this to trigger, there were no staff on at the time.

**Comment by GMR25** [comment]
This is caused by the Crew Transfer. A CT vote is automatically called after a specified period of time, set in the config. It's a Baycode thing that you don't commonly see because rounds don't usually go long enough to see it.
