### ISSUE TITLE
Suggestion: HV mag size

### ISSUE THREAD

**Issue by YellowKingThe** [DS-13-Dev-Team/DS13-1.0#1799]
#### Suggestion:
Change the HV ammo on the Ishimura to 50 round mags instead of 100, if 100 still wants to be available for the ERT make it a separate ERT Extended Mag with HV.

#### What do you think it'd add:
It will make 100 round mags unavailable to the Ishimura and make pulse rifles and HV less crazy overall.

**Comment by NanakoAC** [comment]
it was changed to 100 to give more value to the grenades, which don't get any stronger and use 25 ammo no matter what

its current ammo count is priced into the store cost, that was recently doubled

**Comment by DTraitor** [comment]
Mag sized was changed by Ketrai at some point
