### ISSUE TITLE
[BUG] Flamers lose the ability to fire with extended use

### ISSUE THREAD

**Issue by ToroidalZer0** [DS-13-Dev-Team/DS13-1.0#1803]

**Comment by DTraitor** [comment]
Happened to me yestrday/ I didn't even use it before, just found it in node room. You can still turn it on using "Switch Safety" but nothing happens when you click turf.

**Comment by DTraitor** [comment]
Are you sure you wasn't in vacuum?

**Comment by ToroidalZer0** [comment]
Yes, I was not in a vacuum.
