### ISSUE TITLE
Suggestion:  Colorable Fingerless Gloves

### ISSUE THREAD

**Issue by JoJoMama25** [DS-13-Dev-Team/DS13-1.0#1806]
That's it. That's literally it. They're like the normal colorable gloves we have in loadouts... 𝐁𝐔𝐓 𝐅𝐈𝐍𝐆𝐄𝐑𝐋𝐄𝐒𝐒.

**Comment by Snypehunter007** [comment]
Denied, didn't follow the format.

Closing.
