### ISSUE TITLE
Bug: Unitologist sacrificial blades are bugged in the loadout menu. 

### ISSUE THREAD

**Issue by JoJoMama25** [DS-13-Dev-Team/DS13-1.0#1807]
Unitologist sacrificial blades are bugged in the loadout menu. You can't select or choose them anymore, The spot where they are at in the menu is blank and you can't select it. It doesn't even "properly" appear correct. Unsure when it started since I rarely play Zealot but It might've started back when we got a new Server Box.

**Comment by NanakoAC** [comment]
will be fixed in upcoming new custom items system

**Comment by Snypehunter007** [comment]
Duplicate #1761.

Closing.
