### ISSUE TITLE
Null.pain error

### ISSUE THREAD

**Issue by NanakoAC** [DS-13-Dev-Team/DS13-1.0#1822]
Clientless monkeys taking damage
[12:36:09] Runtime in pain.dm, line 2: Cannot read null.pain
proc name: flash pain (/mob/proc/flash_pain)
src: the monkey (830) (/mob/living/carbon/human/monkey)
src.loc: the deck (165,147,3) (/turf/simulated/floor/tiled/kafel_full)
call stack:
the monkey (830) (/mob/living/carbon/human/monkey): flash pain(135)
the monkey (830) (/mob/living/carbon/human/monkey): custom pain("Your right leg hurts badly!", 40.25, 0, the right leg (/obj/item/organ/external/leg/right), 1)
the monkey (830) (/mob/living/carbon/human/monkey): handle pain()
the monkey (830) (/mob/living/carbon/human/monkey): Life(20, 1017, Mobs (/datum/controller/subsystem/processing/mobs))
Mobs (/datum/controller/subsystem/processing/mobs): fire(0)
Mobs (/datum/controller/subsystem/processing/mobs): ignite(0)
Master (/datum/controller/master): RunQueue()
Master (/datum/controller/master): Loop()
Master (/datum/controller/master): StartProcessing(0)

**Comment by DeadLineSS13** [comment]
#1726
