### ISSUE TITLE
Suggestion: add subtypes for rat necros

### ISSUE THREAD

**Issue by reklaw9** [DS-13-Dev-Team/DS13-1.0#1831]
#### Suggestion:
rats which can only be made by the infector:

**mine rats** which explode when stepped on(can only be picked up by infector, uber or exploder)
**acid rat** which can run into survivors and explode into a small amount of acid, attacking explodes the rat
**infector rat** which can run into dead bodies to slowly start reviving them(all humans will see the body starting to shake, if the body gets shot/kicked the rat will die), rat dies after infecting a body, attack gives two damage
**slasher** rat which is small and extremely weak but fast compared to humans conterparts(gives 5 damage per slash, cooldown of 2 seconds)
**lancer rat** which can charge humans and get stuck to them, when stuck the lancer rat will give 3 damage each 2 seconds, needs to be removed just like a shrapnel, injects 1u of necrotoxin every two minutes
**eye rat** a rat with a single yellow eye that works almost as a "gaze", gives no light but looks weird when examined, faster than slashers but slower than humans, three damage per attack
**builder rat** a rat that can build stuff just like the infector, has a +0.5 essence per second and can contain 20 essence at max, has 15 Health and moves at the same speed as a exploder, can mend other necros, one damage per attack

20% chance for mine rat
30% chance for slasher rat
15% chance for eye rat
15% chance for lancer rat
10% chance for infector rat
5% chance for builder rat
5% chance for acid rat
#### What do you think it'd add:
More variety for necromorphs, currently rats simply become limbs when turned into a necro.

**Comment by NanakoAC** [comment]
i love rats but they arent really the focus of dead space

they're planned to become swarmers once we make those, divider limbs are a temporary thing

**Comment by reklaw9** [comment]
closing this, old suggestion
