### ISSUE TITLE
Balance Suggestions: 

### ISSUE THREAD

**Issue by lamesace** [DS-13-Dev-Team/DS13-1.0#1837]
-->
#### Suggestion: Okay here are a few idea's for balancing where I think a lot of the main problems would disappear 

Slasher and enhanced slasher: Less Charge Range 

Leaper: Charges in a straight line

Exploder/Enhanced Exploder: Less Charge range, Slower movement speed, less limb health

Infector: No Spine shooting or lower spine damage

Ubermorph: Higher Lunge Cooldown, Slower speed

Seeker Rifle: No stun

Cysts: Less detect range and not allowing them to be within 4/5 tiles of eachother

Frantic Growth: Remove them or make it so you can't place it within 6 tiles of a survivor

**Comment by Snypehunter007** [comment]
Denied. Mega-suggestions aren't allowed.

Closing.
