### ISSUE TITLE
Suggestion/Bug: add inaprovaline and dylovene back to sleepers(its not in their UI now)

### ISSUE THREAD

**Issue by reklaw9** [DS-13-Dev-Team/DS13-1.0#1839]
#### Suggestion:
add inaprovaline and dylovene back to sleepers

#### What do you think it'd add:
i am really not sure if this was expected or a bug, but either way, this UI is kinda bad (pic related)
![image](https://user-images.githubusercontent.com/36147254/135988911-2cf8112a-5e6f-49af-acf7-17b4e4c6b87f.png)

**Comment by reklaw9** [comment]
this UI(THE ELDER GOD'S BLESSING) happened the first time that i tried using the sleeper

**Comment by Snypehunter007** [comment]
> 
> #### Description of issue:
> #### Difference between expected and actual behavior:
> #### Steps to reproduce:
> #### Suggestion:
> 
> add inaprovaline and dylovene back to sleepers
> #### What do you think it'd add:
> 
> i am really not sure if this was expected or a bug, but either way, this UI is kinda bad (pic related) ![image](https://user-images.githubusercontent.com/36147254/135988911-2cf8112a-5e6f-49af-acf7-17b4e4c6b87f.png)

i believe this was fixed in #1840, unless I'm missing something?

**Comment by DTraitor** [comment]
view bug isn't connected with sleeper

**Comment by Snypehunter007** [comment]
@reklaw9 are you still encountering the UI error?

**Comment by reklaw9** [comment]
fixed
