### ISSUE TITLE
Suggestion: Add more items for both the EarthGov op and the unitologist 

### ISSUE THREAD

**Issue by stuff-labs** [DS-13-Dev-Team/DS13-1.0#1844]
Add in more items (Such as the emag) for the unitolgist/EarthGov agent's uplink.

It would add in more traitor items including the obvious stuff (Emag, Agent ID, stim cigs, comms key for example) and some more unique gear for each faction (some more guns would be nice too).

**Comment by Snypehunter007** [comment]
> 
> 
> Add in more items (Such as the emag) for the unitolgist/EarthGov agent's uplink.
> 
> It would add in more traitor items including the obvious stuff (Emag, Agent ID, stim cigs, comms key for example) and some more unique gear for each faction (some more guns would be nice too).

Please adjust your suggestion so it follows the format.

**Comment by Snypehunter007** [comment]
Denied. It has been two days and the formatting hasn't been fixed.

Closing.
