### ISSUE TITLE
BUG: infector why breaks if someone takes over it

### ISSUE THREAD

**Issue by reklaw9** [DS-13-Dev-Team/DS13-1.0#1846]
#### Description of issue:
the infector UI completly breaks(only blurred bright colors are visible, like bright blue and others) if someone takes it over, quits and then someone else takes it over

#### What do you think it'd add:
![image](https://user-images.githubusercontent.com/36147254/136249720-dfa52b7b-d14e-4d1d-8d37-1a6daf138a7e.png)

**Comment by MarshalRed** [comment]
Reconnect, it fixes it for some reason

**Comment by reklaw9** [comment]
*bug* fixed in the past month, infectors actually are normal functional members of society now
