### ISSUE TITLE
Plasma Cutter energy takes up way too much space

### ISSUE THREAD

**Issue by ReynTheLord** [DS-13-Dev-Team/DS13-1.0#185]
#### Description of issue

The plasma cutter energy things take up more space in a bag than a goddamn plasma cutter, it's literally more efficient just to haul more plasma cutters

#### Difference between expected and actual behavior
I'd expect plasma cutter energy to take up much less space

#### Steps to reproduce 
Put plasma cutter energy ammo in a bag. done

#### Specific information for locating
Plasma energy

#### Length of time in which bug has been known to occur
Dunno

#### Client version, Server revision & Game ID
Irrelivant, currently

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x ] Issue could be reproduced at least once
- [ x] Issue could be reproduced by different players
- [x ] Issue could be reproduced in multiple rounds
- [ x] Issue happened in a recent (less than 7 days ago) round
- [x ] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by NanakoAC** [comment]
definitely bug, oops!

**Comment by Snypehunter007** [comment]
Fixed in #212

Locking.
