### ISSUE TITLE
Suggestion: Make engineering great again.

### ISSUE THREAD

**Issue by MarshalRed** [DS-13-Dev-Team/DS13-1.0#1857]
#### What do you think it'd add:
Give engineers more tools to do their jobs. Allow them to create entry ways that can become barricades. Allow them to paint doors they move. Allow engineers to grab hydrogen to make the engine generate more power.

**Comment by Gigantomidgeto** [comment]
Engineering will also need the rapid pipe dispenser(RPD) and a source of for the hyperwave filter(a vital component to fix comms) in order to allow Engineering able to do its job correctly
