### ISSUE TITLE
Bug: Knife Execution breaks view and UI

### ISSUE THREAD

**Issue by MarshalRed** [DS-13-Dev-Team/DS13-1.0#1867]
#### Description of issue:
View breaks if the knife hits a helmet or you get interrupted. UI Gets Squished together. While this is happening you cannot perform another execution.

#### Difference between expected and actual behavior:
Should just reset after failure.

#### Steps to reproduce:
Get interrupted or perform a sacrifice on a helmeted target.

**Comment by Snypehunter007** [comment]
Duplicate of #1408.

Closing.
