### ISSUE TITLE
Suggestion: replace eva (suits) with astronaut rigs

### ISSUE THREAD

**Issue by blackwolf602** [DS-13-Dev-Team/DS13-1.0#1877]
Instead of the regular Eva suit (not Eva rigs) we find in suit storages around the station escape pods, I suggest The implementation of the Astronaut Rig ![image](https://user-images.githubusercontent.com/54816502/137278454-d804ae17-05a9-4b2a-a7c9-5a93444f3641.jpeg)

**Comment by NanakoAC** [comment]
didn't we recently add a civilian eva rig with a similar helmet and a white color scheme?
