### ISSUE TITLE
Suggestion:double walking and running speed

### ISSUE THREAD

**Issue by reklaw9** [DS-13-Dev-Team/DS13-1.0#1879]
#### Suggestion:
double the speed that humans and necros move and double the slowdown of heavy armor.

#### What do you think it'd add:
Both necros and humans are extremely slow currently, even when unarmored, this would make it so using RIGs/Heavy Armor would be more taxxing on speed while making having no RIG a valid strategy

**Comment by NanakoAC** [comment]
speed will be looked at in time, it may yet change, but nothing as crazy as doubling is going to happen

**Comment by reklaw9** [comment]
alright closing this now
