### ISSUE TITLE
Suggestion: RP improvements

### ISSUE THREAD

**Issue by RegJoe** [DS-13-Dev-Team/DS13-1.0#1885]
//The following list has been gathered and filtered by CSWINE. It's multiple Ideas thrown in by players who practice/practiced RP regularly. 

Increase importance of Bridge. Examples:

- Make the Bridge have a purpose such as making lockdowns relevant

Encourage RP by: 

- Implementing Store Restrictions.

- Removing skills or very least skill points.

- Add in more non-lethal ways to deal with a target.

- Rebrand "Zealots" to something less extreme. "Touched by the marker". A simple rename can go a long way.

Signals rework: 

- Lowering signal whisper costs.

- Refresher of the Signal rules. 

- Enforce MRP to them.

Additionally, RP guidelines need to be followed by staff to show the correct example for players.

**Comment by MarshalRed** [comment]
I have a idea for zealots. Split them into Church Operative and, of course, Zealot. Church Operative just wants to delay evac as long as possible in an attempt to keep with the plan of getting the marker to earth, whereas Zealot is the crazy antag we know and love.

**Comment by NanakoAC** [comment]
>     * Make the Bridge have a purpose such as making lockdowns relevant

I wholly agree. In fact I had the hall turret controls in the captain's nest until snype moved them, we should put that back.
Lockdown is currently relevant though, it protects the bridge from asteroids. Those blast shutters allow it to survive far longer and sustain many direct impacts that would vent the place in one hit.

Other ideas for making the bridge more relevant are welcome, but should really be seperated off

>     * Implementing Store Restrictions.

This would be noncanon so i'm generally not in favor. Though i wouldn't be opposed to a soft touch by giving discounts on things more relevant to your job

>     * Removing skills or very least skill points.

I have a massive plan for redesigning the skill system but we have some internal disagreements about it. For now, the team isn't certain what direction we want to go in with this

> >     * Add in more non-lethal ways to deal with a target.

We have bola, taser and pepperspray, is that not enough?
DS is a very lethal universe, horror genre is a lot about gory murder more than peaceful takedowns. Conflicts ending in death is totally within the spirit of the genre

>     * Rebrand "Zealots" to something less extreme. "Touched by the marker". A simple rename can go a long way.

This one's a no, they already did get rebranded. To zealots. To indicate that they ARE extreme. And in doing so, to differentiate them from normal, non-extreme worshippers of unitology.

Unitology is a universal religion, you can pick it in character setup and roleplay a peaceful moderate unitologist. The zealots are, specifically, the nutcases who do ritual sacrifices and worship zombies

> Signals rework:
> 
>     * Lowering signal whisper costs.

Simple enuogh to do. The current cost was mostly for the sake of encouraging longer form conversations but maybe reducing it would be best
