### ISSUE TITLE
(Suggestion) Seeker Rebalance

### ISSUE THREAD

**Issue by lamesace** [DS-13-Dev-Team/DS13-1.0#1887]
#### Suggestion: What you could do to balance the seeker more
-Less ammo like 2 mags that come with it 
-Remove the ammo and gun from the stores and you can't print ammo or the gun
-Put 1 seeker on board
-Stun the user temporarily if they don't have experienced in guns 
-No shooting through walls 
-Only putting a seeker in armory

**Comment by NanakoAC** [comment]
Seeker has recently been rebalanced, have you played with the new changes yet?

**Comment by NanakoAC** [comment]
Ah its not merged yet. I'm going to call this Fixed in #1870 

If that PR is unsatisfactory, please reopen this after playtesting it once its merged
