### ISSUE TITLE
Suggestion: Add a way to disable the attack animation

### ISSUE THREAD

**Issue by reklaw9** [DS-13-Dev-Team/DS13-1.0#1890]
#### Suggestion:
add a way to disable the attack animation

#### What do you think it'd add:
a way for people to not get confused at the attack animation, currently its very ugly and looks almost as if you threw your weapon to that person

**Comment by NanakoAC** [comment]
The attack animation is feedback for everyone around about what's going on. The sliding icon of a weapon is pretty informative

While it could possibly be worked on, its not going to be removed, and it's definitely not going to be selectively removed for some people. Turning it off would give an advantage by making it harder to understand what you're doing.

Possibly in future the sliding could be reworked to more of a swing animation, but this issue as requested, won't be happening
