### ISSUE TITLE
Anyone can use chem dispenser

### ISSUE THREAD

**Issue by NanakoAC** [DS-13-Dev-Team/DS13-1.0#1909]
The chem dispenser needs some controls to prevent people without the appropriate skill from being able to easily use it. Random powergamers breaking into the lab to make their own enhancing chems is nonsensical

Possibilities for what will happen to characters with little or no chem skill:
-A simple error message, "You don't have the skills to use this machine"
-Randomly scrambling the button order and linkage. So when you press the oxygen button you're really getting some other element that you don't know.
-Randomly scrambling the button order and name, so the oxygen button reads some gibberish and is in a different location
-Random mistakes, when you try to press a button you'll accidentally press another instead (and be told that you did so)
-Random chance to spill some or all of the contents of the beaker when performing actions (dispensing, removing/inserting, etc)

Generally, people who aren't trained chemists, should not be able to make medicines, performance enhancers, etc, for themselves.

**Comment by DTraitor** [comment]
We can also replace letters in reagent name. If you don't know what chem it is then you can misread it.

**Comment by Snypehunter007** [comment]
We had a discussion about this before, I'm pretty sure. Or at least West and I did.

Not really a point to having a chem skill at all if it just access based, is what I think we ran into.

If we were to do it, the simplest solution would be best, just not allow them to use the machine.
