### ISSUE TITLE
(Suggestion) Revert back to psci sec body armor/rigs

### ISSUE THREAD

**Issue by lamesace** [DS-13-Dev-Team/DS13-1.0#1912]

**Comment by lamesace** [comment]
yeah also the security team has devolved into raiding cargo for decent gear this update fucked up a lot of shit for sec players

**Comment by NanakoAC** [comment]
The old security rig was from sprawl, not ishimura, it will be used again in future on the sprawl map

The appearance of current sec gear is lore accurate, and not likely to change. Please try to seperate visual and functional concerns

**Comment by lamesace** [comment]
I'm referring to the  PSCI body armor and PSCI rig

**Comment by NanakoAC** [comment]
limiting the number of rigs was a decision from west, that's not likely to be reverted. The goal here is to encourage more use of the body armors

If you think they're too weak, that could be a valid concern, but this issue is all over the place.

**Comment by MarshalRed** [comment]
Just upgrade the defense, the armor looks fine I've not heard that '90%' of people complain about it.

**Comment by lamesace** [comment]
The '90%' thing was an over exaggeration atleast higher our armor defense the sprites look kinda ass in my opinion and armory is now like a race to see who put more stats in athletics to get rjg

**Comment by NanakoAC** [comment]
> 
> armory is now like a race to see who put more stats in athletics to get rjg
Well that's the fault of command staff. The officer in charge should decide which personnel are most qualified for the higher tier of equipment

you shouldn't even be opening the armory at all until there's a tangible threat

**Comment by Survivor23** [comment]
> 
> 
> > armory is now like a race to see who put more stats in athletics to get rjg
> > Well that's the fault of command staff. The officer in charge should decide which personnel are most qualified for the higher tier of equipment
> 
> you shouldn't even be opening the armory at all until there's a tangible threat

The point he is trying to make is this.

The standard security armor is paper. It protects against nothing. The old armor had at least a resemblance of value. And the riot gear doesn't protect against bullets either. Unitologists absolutely shred security officers who are supposed to be the ones handling such threats. Engineers and Planet crackers have better equipment to deal with human threats (and necromorph threats, but to an extent that's acceptable). 

In my opinion, the standard armor should be buffed to atleast offer some acceptable ballistic protections. And half of the riot suits in the armories should be replaced by ballistic vests/helmets so security is at least capable of handling human aggressors.
