### ISSUE TITLE
Suggestion: add more items and weaponry to crew loadout

### ISSUE THREAD

**Issue by reklaw9** [DS-13-Dev-Team/DS13-1.0#1930]
#### Suggestion:
add the following items to crew loadout:
Bomber Jacket(1)
Labcoat (1)
Weapons permit (2): Spawns the person with a gun permit, gun not included>
Divet (6):Gives a loaded illegal divet to the player, better to not let the cops find it.
Health Analyser (2)
HandMade Armor (4): Gives a HandMade armor vest to the player, its illegal, better not to let cops find it.
HandMade Helmet(3): Gives a HandMade armor helmet to the player, its illegal, better not to let cops find it
First Aid Kit(2)
Stabilization First Aid Kit(4): Gives the player a Stabilization First Aid Kit, containing a cryo bag and 4 emergency medicine pouches, extremely useful.
Zoom Pill Bottle (4)
Stunprod(6): Gives the player a charged illegal stunprod. 
Ambrosia: Gives the player 3 ambrosia "leafs", it may be illegal, but its still ambrosia.
LSD: Gives the player a beaker containing 60u of mindbreaker toxin, extremely illegal.
Happy Pills: Gives the player a Pill Bottle of happy pills, extremely illegally happy!

_don't ask me why i wrote all those "descriptions"_

#### What do you think it'd add:
Illegal stuff and weaponry to cause conflict with, giving security something to do other than hunt down unis or people that did nothing wrong.

**Comment by Snypehunter007** [comment]
No. Denied.

Closing.
