### ISSUE TITLE
Bug: Humans get a message for marker awakening

### ISSUE THREAD

**Issue by lemshake** [DS-13-Dev-Team/DS13-1.0#1935]
#### Description of issue: Humans, just like signals, during the moment when the marker awakens get the same message about it.
![abeletes](https://user-images.githubusercontent.com/90796968/140072779-60e225a8-4b27-4338-a06f-587c92a106ee.jpg)

#### Steps to reproduce:
1. Join in as a human.
2. Wait until marker awakening
3. See the subtle message saying "The marker has awoken, new abilities are unlocked. Check your abilities menu!"

**Comment by DTraitor** [comment]
I think I fixed it at some point (it happened due to using `locate()` instead of weakrefs
