### ISSUE TITLE
Suggestion: Mining shuttle becomes unable to go to the colony after a certain amount of time.

### ISSUE THREAD

**Issue by lemshake** [DS-13-Dev-Team/DS13-1.0#1944]
#### Suggestion: 
After the 1:35 or so hour mark (once the outbreak usually overtakes most/all of the lower deck), the mining shuttles should not be able to be used with the consoles on the ishimura by normal means.

#### What do you think it'd add:
I often see survivors sit out a certain amount of time at the colony, despite it not counting as the station Z which causes a round end for people on the colony, they can still rely on the people alive aboard ishimura. This feature would not let humans go to the colony after a certain amount of time passes in the round, which prevents blatant hiding from necromorphs, which then makes it boring for both sides of the gamemode. This way, people already hiding on the colony will, at one point, have to go back up to ishimura, while also not being able to go back down.

**Comment by blackwolf602** [comment]
I believe it should be how the dead space movie had it but tweaked. As in once the infection reaches as certain point have it so the mining ships are disabled. And have necromorph nest hidden in the colony after as certain amount of time or a threshold is passed
