### ISSUE TITLE
Bug Report: theres no + or - on the chem dispenser

### ISSUE THREAD

**Issue by reklaw9** [DS-13-Dev-Team/DS13-1.0#1945]
#### Description of issue:
theres no + or - on the chem dispenser, its hard to explain, but essentially, you can only inject custom amounts of a reagent if you manually drag/pull the shitty "custom amount" thing, meaning that for example, you can't just put your amount as 5u and then turn it into a custom amount by turning it into 15u, you gotta drag the thing to exactly 15u, there is no indication that you have to drag/pull the custom amount thing, meaning that if you don't hover your mouse over it, you won't even notice that you can drag/pull it(and yes, you have to drag and pull it)

#### Difference between expected and actual behavior:

a + and - button with preset amounts, ranging from -40 to +40 so you can do chemistry quickly like in any server that uses TGUI or has actual chemistry.

(![image](https://user-images.githubusercontent.com/36147254/140651827-e24d6200-7450-4dce-a56f-b5f51267019b.png)

**Comment by DTraitor** [comment]
You can click slider to set exact amount
