### ISSUE TITLE
AFK Mining is too profitable

### ISSUE THREAD

**Issue by NanakoAC** [DS-13-Dev-Team/DS13-1.0#1949]
The problem:
A lot of mining income is being produced by the passive drills, which you just setup and go.

This has a few knock on effects:
-Less engagement with core mining gameplay, and use of the specific mining tools
-Mining income is skewed away from labour output, 20 miners don't produce anything close to what one miner does, because it only takes one person to setup those drills
-At low population times especially, the drilling makes it too easy for a single person, or handful of people, to farm money.

Goals:
I would like to:
-De-emphasize the drills, and encourage use of lore appropriate mining tools
-Make the drills less rewarding in money especially
-Make/keep mining fun and engaging, don't want to make it a boring slogfest

Some possible changes that could be made:
-more strictly managing the cells that can be put into things, so huge weapon batteries can't be used to run a drill forever
-Low power versions of mining tool-weapons (like linecutter) that use much less ammo but are less effective for fighting with, and can be upgraded to their normal versions
-Aoe swing for rock saw to mine several tiles at once
-Lowering the output of mining drills, or the total ore that can be mined from the ground before it needs to be moved elsewhere
-Making drills occasionally break down and require some tool interaction to restart them

Other ideas are welcome

**Comment by Snypehunter007** [comment]
Drills already "break down". They need to be emptied and power cells replaced on the regular.
