### ISSUE TITLE
BUG:Multitools don't do anything

### ISSUE THREAD

**Issue by Cairo283** [DS-13-Dev-Team/DS13-1.0#195]
#### Description of issue

Using a multi-tool on a wire to pulse it just results in the text saying "You need a multi-tool!"

#### Difference between expected and actual behavior

To be able to pulse wires with a multi tool to hack a door.

#### Steps to reproduce 

Open a door maintenance panel, click on the pulse button for a wire with a multitool in your hand.

#### Specific information for locating

multitool

#### Length of time in which bug has been known to occur

Just today, I dunno if was happening last test.

#### Client version, Server revision & Game ID

893d8ac3e599a5a251b539ca4d0d47f7312709d4 - dev - 2020-03-28

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by ghost** [comment]
This may also be related to the inability to access the Telecomms machines.
