### ISSUE TITLE
Limiting stores (suggestion)

### ISSUE THREAD

**Issue by lamesace** [DS-13-Dev-Team/DS13-1.0#1953]

**Comment by blackwolf602** [comment]
In my opinion the store should work as by checking the security clearance or type of job the person has as well as the blueprint where if you find the blueprint no matter what you'll still have it.

**Comment by NanakoAC** [comment]
Counterpoint

The stores were designed to provide an alternative to scavenging, so you can spend the early parts of the round doing your job, and still be able to buy some useful things later on

If items in there are restricted, it'll mean gardeners and doctors have to go back to scavenging maintenance to get ahold of a weapon
