### ISSUE TITLE
Suggestion: make captain, FL and security unable to be antags (read my arguments first, please).

### ISSUE THREAD

**Issue by reklaw9** [DS-13-Dev-Team/DS13-1.0#1956]
#### Suggestion:
Make Captain, Security and the FL unable to be Unitologists or EGA.
#### What do you think it'd add:

**My argument for captains and FLs not being Unitologists:**
**GAMEPLAY:**While its lore inaccurate, Captains and FLs have access to most of the ship and command most of the crew, plus they have access to the armory and can easily disable comms and make a fake concentrantemente saying that some random engineer sabotaged comms, plus, no one BUT admins can do a thing if captain decides to get a security/vintage/riot RIG, grab a seeker and murderbone the crew, they also can easily sabotage the bridge, destroy all weapons on all three armories and then vent most of the ship.

**My argument for Captain, FL and security being unable to be EGAs:**
**LORE:** CEC would clearly take DNA samples, look at all their records and do extensive background checks(*considering that they are command and security staff on a ILLEGAL mission*) to see if they were ever involved on any crimes, military operations or infiltration due to the fact that they are going to a quarantined zone, the repair crew was sent due to the fact that comms weren't working and CEC had no time to do any background checks, thats the reason that there was a EGA among them.
**Gameplay:** Making security able to be EGAs gives them a reason to metagame, powergame and validhunt unitologists, doing random searches and other things with no consequence whatsoever , and the captain and FL have access to all the stuff that they need to take photos of, plus they have easy access to fax machines, encouraging them to just send out a distress signal and ask for a EGA "Police Squad" after they are done with the photos.

**Comment by NanakoAC** [comment]
As i think you're already aware, the captain was canonically a unitologist in dead space+downfall. And indeed, many of the staff were followers of it too

Given that, i'm personally against this change, its just not how that universe works. And a uni captain has a lot more potential for intrigue with his postition of power

**Comment by reklaw9** [comment]
in about 70% of the rounds(that HAD some players) in the past month, if there was a captain, he was a unitologist

**Comment by reklaw9** [comment]
rejected caus lore
