### ISSUE TITLE
Suggestion: Make exploder pustules the hand part of the mob

### ISSUE THREAD

**Issue by Fernlicker** [DS-13-Dev-Team/DS13-1.0#1960]
#### Suggestion:
Move the exploding pustule on the exploder and enhanced exploder to the hand part, so it can be taken off by delimbing the appropriate arm.

#### What do you think it'd add:
Makes it more in line of what DS players would expect is the go to solution or handling exploders, and it leaves the pustule severed to be used as an improvised kinesis explosive. Makes the proper arm targeting more rewarding for survivors, and curbs exploder only spams from Markers if the players have an effective way of dealing with a threat of potentially spacing the entire ship. Thus further urging marker players to mix and match necros instead of 1 type spam.

**Comment by NanakoAC** [comment]
There's a misunderstanding here.

We have several variants of the exploder, the classic one (which is still in use) has the pustule as the hand.
The newer one, and its right side variant, have the pustule integrated into the whole arm.

These anatomical configurations support the sprites that they have, we don't have sprites for a seperate arm and hand on the new ones. I'm pretty proud that i managed to code variants of a necromorph having different anatomy

ultimately this is a spriting matter, and making it work as desired would require major retooling of those sprites, which is highly unlikely
