### ISSUE TITLE
SUGGESTION: add shutters to the windows of the bridge

### ISSUE THREAD

**Issue by reklaw9** [DS-13-Dev-Team/DS13-1.0#1984]
#### Suggestion:
add shutters to the windows of the bridge to prevent breaches from asteroids and other things, it makes no sense for the bridge windows to always be open, there should be a way to close them in case of a ADS failure in the mid of a meteor shower

**Comment by DTraitor** [comment]
There are shutters already, search for a button in the center of the bridge

**Comment by Ketrai** [comment]
Apparently already addressed

**Comment by Ketrai** [comment]
Apparently already addressed
