### ISSUE TITLE
BUG: Lower level escape pods don't have power

### ISSUE THREAD

**Issue by Cairo283** [DS-13-Dev-Team/DS13-1.0#199]
#### Description of issue

The lower level escape pods, at least the ones on the east side, don't have power, and thus can't be opened when evacuation is called.

#### Difference between expected and actual behavior

For the doors to have power, so I could unbolt and board the escape pod. Instead the door bolts are stuck down and they have no power, so there's no way to open the pods short of an RCD.

#### Steps to reproduce 

Call for evacuation, try to get in the escape pods in the lower deck on the east side of the ship.

#### Specific information for locating

Pretty sure it has something to do with their area not being powered.

#### Length of time in which bug has been known to occur

Since the escape pods were added down there, I assume.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by Snypehunter007** [comment]
Yeah, this is my fault. I forgot to add areas when I was doing the pod setup, they are already fixed and have been committed.

They should be in for the next test.

**Comment by Snypehunter007** [comment]
Fixed in #202
