### ISSUE TITLE
BUG: twitchers leave invisible copies of themselfes.

### ISSUE THREAD

**Issue by DrCrawler** [DS-13-Dev-Team/DS13-1.0#1993]
Reporting client version: 514.1571

Each time the twitcher randomly moves he creates an invisible copy of himself that cannot move, but can very much be interacted with. A leaper can leap into it, teleporting the leaper to the twitcher; you can charge into it, which will charge the twitcher; you can bump into it and you will either push the twitcher or swap places with him (depends on intents of both you and the twitcher).

How to recreate: Be twitcher. Wait for the passive ability to proc and move you a tile or two. Done, there is(are) now a copy(ies) of you in there. You cannot move there anymore.

The only way this bug can be avoided unless you simply dont play twitcher. 
Feel free to PM me on discord: DrCrawler#1733. But keep in mind its late at the time i report the issue so i might not answer for a while.

**Comment by Ketrai** [comment]
Isn't this already fixed?

**Comment by DTraitor** [comment]
I didn't encouter this at all
