### ISSUE TITLE
BUG: EW can start even if there are no shardbearers

### ISSUE THREAD

**Issue by reklaw9** [DS-13-Dev-Team/DS13-1.0#2008]
#### Description of issue:
EW can start even if there are no shardbearers, i am aware that shardbearers can appear later on the round, but it almost never happens

#### Difference between expected and actual behavior:
"There aren't enough shardbearers (1 required) reverting to containment gamemode"

"get fucked you ain't seeing necros this round"

**Comment by ghost** [comment]
We're losing this mode for now. @DTraitor
