### ISSUE TITLE
BUG: You cannot drag crates up ladders

### ISSUE THREAD

**Issue by Cairo283** [DS-13-Dev-Team/DS13-1.0#201]
#### Description of issue

Dispite the text saying "you begin to climb the ladder with the crate, slowing you down", the crate doesn't actually follow you up the ladder.

#### Difference between expected and actual behavior

To be able to drag a crate up a ladder.

#### Steps to reproduce 

Pull a crate, then start climbing up a ladder.

#### Length of time in which bug has been known to occur

Assuming since it was made possible to drag things up ladders.

#### Client version, Server revision & Game ID

893d8ac3e599a5a251b539ca4d0d47f7312709d4

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by JakeDaBoss** [comment]
Not a bug, that's a feature.

You can't drag them up ladders because you that's not how it works. We're not CM.

Use stairs for these kind of things.
