### ISSUE TITLE
BUG:shitcurity boots can't be slipped

### ISSUE THREAD

**Issue by reklaw9** [DS-13-Dev-Team/DS13-1.0#2014]
#### Description of issue:
/obj/item/clothing/shoes/pcsi has slip immunity

#### Difference between expected and actual behavior:
Soap is soap, you slip on it, you fall, be robust or get slipped

seccies can't focken slip

**Comment by DTraitor** [comment]
Intended feature

**Comment by Viz-Titan** [comment]
Should still be closed due to not being a bug
