### ISSUE TITLE
Bug: You can move scry eyes with the Kinesis Module

### ISSUE THREAD

**Issue by RDS88-beeman** [DS-13-Dev-Team/DS13-1.0#2032]
#### Description of issue: 
Targeting a tile with a scry eye (created by a signal's scry ability) while the kinesis module you can spawn with is active will allow you to pick up, move, and smack people with the scry eye.

#### Difference between expected and actual behavior:
I'm fairly sure scry eyes are meant to be intangible points, and while being able to move them isn't particularly balance ruining it's kind of immersion breaking

#### Steps to reproduce: 
As a signal, create a scry eye
As a crew member with the kinesis module on their RIG suit, press F to activate the suit and target the tile with the eye on it. 
Your module will snap to the scry eye, and you will be able to move it

**Comment by DTraitor** [comment]
It was fixed at some point
