### ISSUE TITLE
BUG: Ripper blades fit on ear slot

### ISSUE THREAD

**Issue by ghost** [DS-13-Dev-Team/DS13-1.0#206]
#### Description of issue

Ripper blades fit on your ear slot.

#### Difference between expected and actual behavior

Your ears are not a good place to keep sawblades.

#### Steps to reproduce 

Put ripper blade on your ear slot.

#### Specific information for locating

Just put a ripper blade on your ear slot. It's probably something to do with size class.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x ] Issue could be reproduced at least once
- [x ] Issue could be reproduced by different players
- [x ] Issue could be reproduced in multiple rounds
- [ x] Issue happened in a recent (less than 7 days ago) round
- [ x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by Snypehunter007** [comment]
Fixed in #212

Locking.
