### ISSUE TITLE
[BUG]: Blank Screens (PDA, console, vendor, craft menu)

### ISSUE THREAD

**Issue by ghost** [DS-13-Dev-Team/DS13-1.0#214]
When attempting to use PDAs, consoles, vendors and the craft menu (essentially anything that brings up a separate window), it appears as a blank white or just a blank image, as if the screen is loading. Despite being open for extended periods of time, it never loads. 

Relogging hasn't fixed it, and I've experience the issue across multiple rounds (The 2 in today's test) and has not visibly fixed itself through the course of a round.

An update: This includes the marker spawning menu, potentially really fucky with someone's round if they get marker and can't use it at all.

**Comment by NanakoAC** [comment]
this is possibly related to asset sending, though i'm not clear on the specifics.

If i'm right, clearing your byond cache should fix it on your end. Thats usually found at 
C:\Users\<username>\Documents\BYOND\cache

Next time this occurs, disconnect, delete everything in that folder, then reconnect. see if that helps

**Comment by JakeDaBoss** [comment]
> When attempting to use PDAs, consoles, vendors and the craft menu (essentially anything that brings up a separate window), it appears as a blank white or just a blank image, as if the screen is loading. Despite being open for extended periods of time, it never loads.
> 
> Relogging hasn't fixed it, and I've experience the issue across multiple rounds (The 2 in today's test) and has not visibly fixed itself through the course of a round.
> 
> An update: This includes the marker spawning menu, potentially really fucky with someone's round if they get marker and can't use it at all.

Fully investigated the issue. Going into Documents/BYOND and deleting your Skins folder, allowing it to redownload, should work.
