### ISSUE TITLE
Necrochat breaks.

### ISSUE THREAD

**Issue by Ketrai** [DS-13-Dev-Team/DS13-1.0#217]
#### Description of issue
A couple minutes into the round after the marker activates the chat just breaks.

#### Difference between expected and actual behavior
For it to work.

#### Steps to reproduce 
Unknown, perhaps it has something to do with the first necromorphs spawning and messing with the chat? No idea.

**Comment by NanakoAC** [comment]
It was caused by key oddities in byond during mob switching. People were getting entered into the necroplayers list twice, and then it threw a runtime error on one of those two due to being invalid, and terminated the proc
