### ISSUE TITLE
Puker feedback.

### ISSUE THREAD

**Issue by Ketrai** [DS-13-Dev-Team/DS13-1.0#218]
- Very strong at range, acid might be a little too debilitating as it seems to last very long. There needs to be a way for humans to take a moment and wash off the acid.
- Puke melts guns rather quickly, meaning all it takes to make someone defenseless is a slasher knocking the person down followed by a puker melting the gun. Guns should probably be exempt from acid, or take a long time to melt down in acid.
- Pukers can do little against grenade launchers due to their speed. 
- There's no indicator for pukers or spitters hitting enemies. Need to add some sort of effect or make targets light up on hit. Same for guns.

**Comment by NanakoAC** [comment]
The last one is a general issue which will be a project of its own to develop

Being vulnerable to grenades is intentional, they're a fairly big and slow target
will work on the first two points

**Comment by NanakoAC** [comment]
also worth noting that acid puddles on the floor can be mopped up like any kind of stain. Someone should play janitor next time :P

**Comment by Ketrai** [comment]
> also worth noting that acid puddles on the floor can be mopped up like any kind of stain. Someone should play janitor next time :P

specifically  meant the  acid affect after being  hit by an acid  projectile or getting puked on.

**Comment by NanakoAC** [comment]
thats what showers can fix, although it doesn't really last long enough to run to one. any suggestions?

**Comment by Ketrai** [comment]
Sinks, buckets, soap, perhaps taking off clothes I guess.
