### ISSUE TITLE
Brutes can be grabbed and moved freely.

### ISSUE THREAD

**Issue by Jackofashepard** [DS-13-Dev-Team/DS13-1.0#22]
As the title says people are able to grab brutes and move/throw them easily as well as performing various wrestling moves on them (albeit you need to be in a red grab to move them) 
![image](https://user-images.githubusercontent.com/51462035/71033928-f1f11480-2120-11ea-9fe6-93074b882cc7.png)

**Comment by Snypehunter007** [comment]
This was fixed awhile ago.

Closed.
