### ISSUE TITLE
[Suggestion] Make marker node spells more potent.

### ISSUE THREAD

**Issue by Ketrai** [DS-13-Dev-Team/DS13-1.0#227]
#### Description of suggestion
Let the marker use their energy to make proper nodes rather than mini-nodes. This way they can choose wether to use their spells more offensively or defensively. It also lessens the competition between nodes and necromorphs for biomass spending. It often feels like a bit of a waste to make 10 npdes, which is easily a leaper or a twitcher without actually providing any immediate benefit. It's rare for humans to wander into corruption except for the very late game.

Or instead, let the marker upgrade mini-nodes for a lesser cost than placing a full node normally. 50% likely. Especially eyes are useful to spot stragglers, but other nodes aren't as useful until the late game.

**Comment by NanakoAC** [comment]
Aside from partially relieving choice conflict, a major part of this project was also to allow signals to take over some of the busywork of constantly expanding corruption. The distinction in node efficacy is a little part of preventing redundancy, and i'm hesitant to make so many things essentially free by adding them to energy too. If we did that, there'd be little point in having the biomass-costing versions

I think it is a good thing to have the option of spending biomass for something more powerful. If anything, i'd lean towards buffing the biomass-cost nodes more, to make them really worth it.

the marker gets tons of energy and can spawn all the same things signals can
