### ISSUE TITLE
[suggestion] reveal the ship to signals before the marker activates.

### ISSUE THREAD

**Issue by Ketrai** [DS-13-Dev-Team/DS13-1.0#228]
#### Description of suggestion
Make it so signals can see the whole ship until the marker activates. Mainly just to allow them to mess around with flickering lights. I don't particularly think the whole ship is needed, but at least a less restrained space than the current.

**Comment by NanakoAC** [comment]
definitely agreed, but technically more difficult than expected i'll need to do some work on visualnets to enable it
