### ISSUE TITLE
Necro blood turns into default dry blood after a while

### ISSUE THREAD

**Issue by Jackofashepard** [DS-13-Dev-Team/DS13-1.0#26]
![image](https://user-images.githubusercontent.com/51462035/71076385-526a6b00-218e-11ea-8c17-a19feea2202a.png)

**Comment by Snypehunter007** [comment]
Is this still a thing?

**Comment by NanakoAC** [comment]
Not a bug, blood just changes its name and brightness when it dries up. Theres no reason necromorph blood wouldn't too

there's nothing default about it, dried necro blood looks different from dried human blood
