### ISSUE TITLE
[Suggestion] Let necros create signal teleport notifications at their position

### ISSUE THREAD

**Issue by SailieVN** [DS-13-Dev-Team/DS13-1.0#265]
#### Description of suggestion
Allow necromorphs to create notifications at their position for signals to teleport to them, like when humans are detected by necro Eyes. This should make coordinating with other necros easier and allow signals to use their abilities more effectively.

Maybe in addition, a list of all occupied/unoccupied necros/signals and their positions, like the Prey Sightings window, would be useful. That one should probably be a separate suggestion, though.

**Comment by Snypehunter007** [comment]
This was implemented awhile ago.

Locking.
