### ISSUE TITLE
leapers seem to get stunned at the end of a leap, regardless wether they hit someone or not.

### ISSUE THREAD

**Issue by Ketrai** [DS-13-Dev-Team/DS13-1.0#271]
#### Description of issue
Leapers always get stunned at the end of the leap. Whilst probably intentional for a miss, hitting a player doesn't change this

#### Difference between expected and actual behavior
reward goof leaps

#### Steps to reproduce 
be leaper
leap at a person

**Comment by ghost** [comment]
@Ketrai Did your recent PR fix this?

**Comment by DTraitor** [comment]
It was fixed at some point
