### ISSUE TITLE
[suggestion] Let signals revive low tier necros for a high cost.

### ISSUE THREAD

**Issue by Ketrai** [DS-13-Dev-Team/DS13-1.0#272]
#### Description of suggestion
Let signals revive (and possess) dead necromorph of the lowest tier (below 80 biomass).
this should probably cost 500 - 900 psi energy.

Just for fun so corpses that get up can attack survivors for a scare. Might need corruption underfoot though. Or a higher cost off corruption.

original suggestion bio maskednecro

**Comment by Snypehunter007** [comment]
Talked it over with West and we both agreed it just wasn't worth it, especially since the Necromorphs also have a healing system now.

Closing.
