### ISSUE TITLE
[suggestion] Have necromorph head damage count for less than other limbs.

### ISSUE THREAD

**Issue by Ketrai** [DS-13-Dev-Team/DS13-1.0#286]
aiming head is too benefitial, same for legs. removing a leg slows down/knocks down a necro massively, and removing head blinds/kills/debilitates them. There's little reason to shoot arms, and it should probably be faster to kill a necro via shooting off arms rather than legs/head. Aim legs/head for debuffs, arms for kill.

**Comment by TheMaskedMan2** [comment]
Killing head should probably do very little beyond maybe lower their vision range a tad.

Part of Necromorphs thing is how the simple "aim for the head" doesn't work on them.
