### ISSUE TITLE
Should consider reworking the vanilla bibles into a unitoligist version

### ISSUE THREAD

**Issue by Jackofashepard** [DS-13-Dev-Team/DS13-1.0#29]
![image](https://user-images.githubusercontent.com/51462035/71077380-faccff00-218f-11ea-87de-5fb5f4f057b6.png)
![image](https://user-images.githubusercontent.com/51462035/71077400-04566700-2190-11ea-8c7a-965dfc156ebb.png)

**Comment by Snypehunter007** [comment]
Fixed as of CodeWorkV.5 #73. Bible's still exist but a Unitologist bible has been added and is spread in a few places throughout the map.
