### ISSUE TITLE
Strange leftover ship section 

### ISSUE THREAD

**Issue by Jackofashepard** [DS-13-Dev-Team/DS13-1.0#30]
![image](https://user-images.githubusercontent.com/51462035/71077714-a1b19b00-2190-11ea-8b1a-e5fabacff85e.png)

**Comment by Jackofashepard** [comment]
Level above this 
![image](https://user-images.githubusercontent.com/51462035/71078572-539d9700-2192-11ea-8f6b-b8c1f2e65993.png)

**Comment by Snypehunter007** [comment]
Yeah, this is leftover from a previous update. It has been removed now, but the branch hasn't been merged.

**Comment by Snypehunter007** [comment]
Fixed as of IshimuraCodeWorkV.4 #79.
