### ISSUE TITLE
Exploders can destroy plating

### ISSUE THREAD

**Issue by Ketrai** [DS-13-Dev-Team/DS13-1.0#302]
#### Description of issue
exploders can destroy plating, making holes in the floor or space. this is a huge issue, as it'll kill anyone not in a suit, and make people drop down levels.

#### Difference between expected and actual behavior
for exploders to not be complete bio-terrorists

#### Steps to reproduce 
be exploder, go boomboom

**Comment by JakeDaBoss** [comment]
@WestHybrid can be closed.
