### ISSUE TITLE
[Bug] Necromorphs can't attack while lying down

### ISSUE THREAD

**Issue by TheMaskedMan2** [DS-13-Dev-Team/DS13-1.0#305]
I suppose you could consider sometimes it's a stunlock, but for the most part anything that causes a Necromorph to fall over.

1. Space Wind Atmos
2. Melee weapons causing the "knocked down" status effect
3. Losing their legs
4. Tons of stuff

Anything that causes a Necromorph to be in the "lying" state on their side prevents them from attacking, even if they are capable of crawling around. Necromorphs in my opinion should obviously be able to crawl around and try to slash peoples ankles, but even in general I think being near this things should be a flailing critter of death.

Pushing it over shouldn't make it harmless, it even applies to Brutes and bigger Necros.

**Comment by Snypehunter007** [comment]
The new system allows for mobs to attack while downed.

Locking.
