### ISSUE TITLE
Cleaning grenade foam makes necros slips (even brutes) making the janitor the strongest role on ship

### ISSUE THREAD

**Issue by Jackofashepard** [DS-13-Dev-Team/DS13-1.0#31]
![image](https://user-images.githubusercontent.com/51462035/71078006-34ead080-2191-11ea-8914-3c813c2f73a9.png)

**Comment by Jackofashepard** [comment]
This extends to soap as well

**Comment by Ketrai** [comment]
Hey, someone has to clean up the mess.

**Comment by Cairo283** [comment]
No bugs here, just robust strats.

I guess this also means that clowns can slip necromorphs.

**Comment by Jackofashepard** [comment]
Its robust until its a meta, mark my words powergamers will use this

**Comment by NanakoAC** [comment]
certain necromorphs shouldn't be slipping. Notably brute, tripod, lurker and leaper. All the rest are working as intended,
