### ISSUE TITLE
[Bug] Necros can be stunned by flashes/pepperspray/etc

### ISSUE THREAD

**Issue by TheMaskedMan2** [DS-13-Dev-Team/DS13-1.0#310]
Generally a whole ton of stuns that should not work on Necros, works on them.

Soap, water, flashes, pepper spray, punch KO's.

Some of this can probably be prevented with no_slip or some such, or somehow making their eyes welder/flash proof? However pepper spray works im not sure. Do flashbangs work with sounds?

As for the punching KO's I have no idea.

Also if you aim for the eyes while melee'ing you can blind them.

**Comment by TheMaskedMan2** [comment]
Edit: Disarms also stun and knock them over for a lengthy amount of time.

I'm going to go ahead and say I feel like necros should be mostly immune to stuns unless it's like an explosion or force-gun.

I suppose a good example might be xenos from CM. They can be stunned, but it's by like weapons and explosions, not disarms and the same stuff that would knock out normal people.

Necros in the DS games were able to be handicapped and slowed down, but never really like, just knocked over so they couldn't do anything. Does that make sense? Stunning is kind of a pain response thing, necros just keep wobbling even with no legs and their head missing.

So sure, let people knock over Necros and handicap them, but it should be able to continue slashing people or hobbling along until the monster stops moving, you get what I mean? Stun reduction?

**Comment by NanakoAC** [comment]
With the addition of crawling combat, i'd say this problem is mostly resolved, maybe stuns are a bit too much on large necros still?
