### ISSUE TITLE
BUG: Planet Cracker Prep randomized Plasma Cutters do not work

### ISSUE THREAD

**Issue by PrimusOmega** [DS-13-Dev-Team/DS13-1.0#313]
#### Description of issue
The plasma cutters that randomly spawn in the Planet Cracker shipside prep lockers do not actually function correctly.
https://cdn.discordapp.com/attachments/706239421892132965/706243604137377832/BLANK_PLASMA.PNG

#### Difference between expected and actual behavior
Plasma cutters do not shoot the expected projectile or do damage.

#### Steps to reproduce 
Find one of the randomly spawning plasma cutters in the Planet Cracker lockers and attempt to shoot it.

#### Specific information for locating
Planet Cracker prep locker random cutter spawns.

#### Length of time in which bug has been known to occur
Several Weeks at least.

#### Client version, Server revision & Game ID
Client Version: 513
Server Revision: e8e208f9dbd3075caf750c46fca8470fc37fa999 - dev - 2020-05-02
Game ID: b6X-ddDE
Current map: USG Ishimura

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this

**Comment by Snypehunter007** [comment]
This'll be fixed when #315 is merged.
