### ISSUE TITLE
[Bug] Twitchers don't have missing limb icons

### ISSUE THREAD

**Issue by TheMaskedMan2** [DS-13-Dev-Team/DS13-1.0#314]
Title. Twitchers can be missing all of their limbs, laying on the ground, dead, and they still are just standing like nothing happened.

**Comment by Ketrai** [comment]
FIXED AT LAST. AS FORETOLD BY THE ANCIENT SCROLLS. BE FREE MASKED ONE. YOUR CONCERNS NOW BELONG TO THE AETHER
