### ISSUE TITLE
[Bug] Advanced Energy Gun Woes

### ISSUE THREAD

**Issue by TheMaskedMan2** [DS-13-Dev-Team/DS13-1.0#320]
The advanced energy gun is able to be mass-produced by a competant science team.

This isn't really a huge problem alone - it's a problem simply due to how absurdly strong the advanced energy gun is on our code against Necros.

It regenerates ammo, has perfect aim, and gibs limbs of even Brutes on single shots, so obviously unintentionally good.

**Comment by NanakoAC** [comment]
best course of action is to remove it, and make the contact beam easier to produce
