### ISSUE TITLE
[Bug] Certain Necros can't break lights, pry doors, or slash APCs

### ISSUE THREAD

**Issue by TheMaskedMan2** [DS-13-Dev-Team/DS13-1.0#321]
Noticed specifically with the Puker and I believe the exploder, I did not test every single Necro of course, but I imagine it has to do with the behind-the-scenes work on which weapon they "use".

**Comment by TheMaskedMan2** [comment]
I think I found what causes this.

Underneath slasher is:
```
/* Unarmed attacks*/
/datum/unarmed_attack/blades
    name = "Scything blades"
    desc = "These colossal blades can cleave a man in half."
    attack_verb = list("slashed", "scythed", "cleaved")
    attack_noun = list("blades")
    eye_attack_text = "impales"
    eye_attack_text_victim = "blade"
    attack_sound = 'sound/weapons/slice.ogg'
    miss_sound = 'sound/weapons/slashmiss.ogg'
    sharp = TRUE
    edge = TRUE
    shredding = TRUE
    damage = 14
    delay = 13
    airlock_force_power = 2
```

While underneath of puker is this:
```
/*
    Unarmed Attacks
*/
//Weaker version of slasher blades
//Light claw attack, not its main means of damage
/datum/unarmed_attack/claws/puker
    damage = 7
```

If my dumb monkey brain understands this right, the fact that pukers are not a subtype of /blade or don't have the additional airlock_force_power = 2 and other such things is probably the reason why.

I imagine some other Necros might also suffer from this instead of just Puker. Prying doors and smashing lights and other basic things are pretty integral so.

**Comment by TheMaskedMan2** [comment]
This also seems to apply to leaper as well, and lurker.

**Comment by JakeDaBoss** [comment]
Correct. This won't be fixed as it is an intended feature. Some Necromorphs are not able to pry open airlocks or anything else.

Slashers and Spitters for example can. It's all about the arms. Or lack thereof, when people can't.
