### ISSUE TITLE
[Bug] turrets were never meant to be meleed

### ISSUE THREAD

**Issue by Ketrai** [DS-13-Dev-Team/DS13-1.0#326]
#### Description of issue
Nobody can attack turrets with melee. Most noticeably necromorphs. Turrets made by engineers can also just be turned off because they don't have access restriction. 

#### Difference between expected and actual behavior
Necro smash

#### Steps to reproduce 
Try to melee a turret on harm intent. Open menu instead

**Comment by TheMaskedMan2** [comment]
Can confirm, just tried to do that, it also just tells me "Access Denied" without slashing.

Also with lots of exploders and brute slams and admin bombs the turrets were still firing, they dont seem to die.

Edit: Yes Turrets do not seem to die at all, at least locally on my side.

**Comment by JakeDaBoss** [comment]
Can reproduce. Investigating.
