### ISSUE TITLE
Rename and re-texture thalers to credits.  

### ISSUE THREAD

**Issue by Jackofashepard** [DS-13-Dev-Team/DS13-1.0#33]
![image](https://user-images.githubusercontent.com/51462035/71078765-b2fba700-2192-11ea-88eb-497937f4192f.png)
![image](https://user-images.githubusercontent.com/51462035/71078779-ba22b500-2192-11ea-90c1-6beac3475918.png)

**Comment by Snypehunter007** [comment]
Should be fixed as of #73
