### ISSUE TITLE
I HIGHLY recommend cutting a good portion of vanilla bay chemicals.

### ISSUE THREAD

**Issue by Jackofashepard** [DS-13-Dev-Team/DS13-1.0#34]
The reason for this being a LOT of the chemicals are insanely overpowered. Chloral can knock anything out in a second for ages, section large napalm slip grenades, chemical that instantly stops hearts ect.

**Comment by NanakoAC** [comment]
quite a few chemiocals have been removed, and the rest have been documented on the wiki. Seems we're likely to keep what's left, at least for now
