### ISSUE TITLE
BUG: Slasher bash window smash (Attack message for slasher on windows grammar error)

### ISSUE THREAD

**Issue by Aetsuki** [DS-13-Dev-Team/DS13-1.0#341]
#### Description of issue
Attacking windows as a slasher is missing the verb for the attack. 

#### Difference between expected and actual behavior
Expected behaviour: Slasher 457  attacks the reinforced window!
Actual behaviour: Slasher 457  the the reinforced window!

#### Steps to reproduce 
Bring down convergence on a window as a slasher

#### Specific information for locating

Slasher 457  the the reinforced window!

#### Length of time in which bug has been known to occur

5/9/20 

#### Client version, Server revision & Game ID

Client Version: 513
Server Revision: e2e87d3f585f073d34b61c34a7d8c81a53cb5146 - dev - 2020-05-09
Game ID: b65-c59d

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by Snypehunter007** [comment]
Fixed awhile ago.

Locking.
