### ISSUE TITLE
[BUG] cysts broke

### ISSUE THREAD

**Issue by Ketrai** [DS-13-Dev-Team/DS13-1.0#343]
Description of issue:
cysts don't work

Steps to reproduce:
spawn a cyst, walk in front, it doesn't shoot! woo!

**Comment by TheMaskedMan2** [comment]
Mentioning cysts as well they commonly shoot at charging necros or the spit from spitters and just things they maybe should ignore.

**Comment by Ketrai** [comment]
They trigger before any kind of fast movement or projectile. I don't mind, means you can set up traps activsted by spitters.

**Comment by Snypehunter007** [comment]
Fixed by #352. Closing.
