### ISSUE TITLE
[ISSUE] Spawner nests don't use necroque

### ISSUE THREAD

**Issue by Ketrai** [DS-13-Dev-Team/DS13-1.0#346]
#### Description of issue
Spawner nests don't have an option to involve people in the necroque

**Comment by NanakoAC** [comment]
they're not supposed to.
They output a message in chat when a body is ready, so that people can jump there and decide if they want to possess it

**Comment by Ketrai** [comment]
which is a bit silly, there should be an option to allow yourself to spawn from a nest when ready. First-come first-serve was something necroque aims to avoid after all. right tnnow fastest tto click gets it.
