### ISSUE TITLE
[Suggestion] Add Janitor Role

### ISSUE THREAD

**Issue by Marrone321** [DS-13-Dev-Team/DS13-1.0#355]
#### Description of issue
There is currently no Janitor/Custodian role! Also, there are missing items in the janitorial closet I will list below!

#### Difference between expected and actual behavior
The expected behavior is there is a janitorial role with more janitor stuff in the closet, the actual behavior is there is not that.

#### Steps to reproduce 
Please consider adding these items to the Janitorial closet:
A mop (or two) , a bar of soap, three more wet signs (if we are going to have two janitorial carts), mouse traps, a trash bag, a light replacer and replacement lights. 

Additionally, an occupation for sanitation technician/custodian/janitor needs to be added, but if all the items spawn in the closet maybe we have them go to their closet to get geared up. That would mean 2 of each item if there are only 2 slots for this occupation.

#### Specific information for locating
Sorry I do not have the typepaths :-(

#### Client version, Server revision & Game ID
Client Version: 513
Server Revision: 43f9e96a434aebc7c1ea774215205932d2a5a66c - dev - 2020-05-14
Game ID: b60-cOv2
Current map: USG Ishimura

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this]

**Comment by Snypehunter007** [comment]
This is kinda two suggestions in one, I'd preferred if you had put two separate suggestions, one about the mapping changes, one about adding a janitor role.

**Comment by Marrone321** [comment]
Sure I asked Spicy Fly and he said to put it in one. I will edit out the insulated glove part as last time i checked the gloves were gone. Thank you so much!!!

**Comment by Snypehunter007** [comment]
@Marrone321. We talked about it and decided we will add a Janitor role in the future, but are going to wait until we have more of a population and the engineers are given more things to do than just set up the engine at the moment.

I will go ahead and add those other changes to the janitorial closets though.

**Comment by Marrone321** [comment]
Thank you so much!! Super happy about the project so far, cant wait till the next test!! Youre the best!!
