### ISSUE TITLE
BUG: Emergency Bags and Medical Kits make Necromorph sounds:

### ISSUE THREAD

**Issue by Odisurin** [DS-13-Dev-Team/DS13-1.0#374]
I'm pretty sure it's a glitch, it happens whenever I open a small bag and it creeps the fuck out of me.

When I was playing a Researcher All the medical bags make a screaming sound when I opened them and just a few minutes ago as a Civilian my Emergency bag made the exact same sound.

Not sure if its a local thing or not.

**Comment by NanakoAC** [comment]
that is spooky as hell, wow

**Comment by TheMaskedMan2** [comment]
This should be a part of psychosis when that's in. Bags screaming at you.

**Comment by JakeDaBoss** [comment]
Can no longer reproduce. Fixed?

**Comment by Odisurin** [comment]
Be me, enjoying shift as a cargo tech. Open bag to take out some smokes and hear a "RARHR" come from it almost every time, yell on the coms that you hear things only to be sent to medical to never get help for it.

**Comment by JakeDaBoss** [comment]
> Be me, enjoying shift as a cargo tech. Open bag to take out some smokes and hear a "RARHR" come from it almost every time, yell on the coms that you hear things only to be sent to medical to never get help for it.

Did this occur during the past 2 tests?
