### ISSUE TITLE
[Bug] Atmospherics Control

### ISSUE THREAD

**Issue by Afya212** [DS-13-Dev-Team/DS13-1.0#375]
#### Description of issue

Colony/USM air alarm shows up on the same system as Ishimura air arlarms.

#### Difference between expected and actual behavior

Colony/USM air alarms not to how up on Ishimura atmospherics control.

#### Steps to reproduce 

Use engineering computer.

#### Specific information for locating

Use engineering computer.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by Snypehunter007** [comment]
TBH, I'm not sure how to even separate the two systems. I know CM had the same problem.
