### ISSUE TITLE
SUGGESTION: Time Limit for Evac

### ISSUE THREAD

**Issue by Gigamonsta** [DS-13-Dev-Team/DS13-1.0#382]
I have a roleplay issue with evac: When roleplaying as command I want to roleplay AS a GOOD OFFICER.

Yesterday, with the role I was playing, I kept asking sec to set up checkpoints and engies to make barricades on the top levels. But, when the ship keeps getting depressurized, comms aren't working or being sabotaged, and we have scant power, it is hard NOT to call for an evacuation. Why wouldn't someone who wants to play as a competent office call an evac?

I think there needs to be some 1 1/2 hour limit to calling an evac. The reason given could be time to maybe "fuel the pods" or something believable like that. That way there is not a confusion in the roleplay as to why or why not an officer should call for an evacuation.

**Comment by Snypehunter007** [comment]
We've put a limit on calling the pods now and we plan on making them a target for sabotage in the future.

Considering that the immediate suggestion is completed by #383. I'm going to close this.

In the future as well @Gigamonsta please use the suggestion format that is pinned in the general channel on Discord.
