### ISSUE TITLE
Brute gets stunned for a while if charging nothing.

### ISSUE THREAD

**Issue by Ketrai** [DS-13-Dev-Team/DS13-1.0#39]
#### Description of issue
If the brute hits nothing after a charge, it's stunned, for a very long time. This also applies to charging at tiles, because you hit and damage tiles. Or catwalks. But if you click a human, the human runs away, you get stunned on nothing.

#### Difference between expected and actual behavior
To not get stunned at all.

#### Steps to reproduce 
1. charge. 2. make sure the path is clear. 3.be surprised you're stunned.

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by NanakoAC** [comment]
fixed this today in ubermorph branch
