### ISSUE TITLE
[BUG] Right hand.exe stopped working.

### ISSUE THREAD

**Issue by Ketrai** [DS-13-Dev-Team/DS13-1.0#392]
#### Description of issue
When you have a container open, you can't use the right hand.

#### Steps to reproduce 
Open a container, try to use your right hand. You can't.

**Comment by NanakoAC** [comment]
Cannot reproduce, need more info. Can you specify an exact kind of container?

**Comment by Ketrai** [comment]
This is the info I got, I'll have to ask around. Ask bill canister either way

**Comment by Snypehunter007** [comment]
Fixed in #395.

Closing.
