### ISSUE TITLE
BUG: Closests can fit in disposal units

### ISSUE THREAD

**Issue by Snypehunter007** [DS-13-Dev-Team/DS13-1.0#432]
#### Description of issue
- See the title.

#### Difference between expected and actual behavior
- It should not be possible to pull a large locker into a disposal unit.

**Comment by JakeDaBoss** [comment]
How do you reproduce this?

**Comment by JakeDaBoss** [comment]
Reproduced. @Snypehunter007 tells me it's fine to axe, so I'll look into this at some point.
