### ISSUE TITLE
[OVERSIGHT] Wheel chairs aren't adapted to our slower movement speed.

### ISSUE THREAD

**Issue by Ketrai** [DS-13-Dev-Team/DS13-1.0#448]
#### Description of issue
Wheel chairs are actually redicilously fast. You ever seen a man roll themselves forwards with a wheelchair? It be slow. Loosing a leg should be a handicap.

**Comment by Snypehunter007** [comment]
Mmm, IDK, if you have the arm strength for it, you can go rather fast in wheelchairs.

**Comment by Ketrai** [comment]
Still needs to be balanced in some way. Perhaps going over certain speeds can make you bump into walls. Going fast is one thing. Turning in a wheelchair is another

**Comment by Snypehunter007** [comment]
That is true.
