### ISSUE TITLE
exploder door runtime

### ISSUE THREAD

**Issue by NanakoAC** [DS-13-Dev-Team/DS13-1.0#518]
[19:39:22] Runtime in door.dm, line 287: undefined proc or verb /mob/living/carbon/human/necromorph/exploder/has quality(). 
usr: Exploder 512 (/mob/living/carbon/human/necromorph/exploder) ([0x3000045]) (the plating) (56,143,2) (/turf/simulated/floor/plating) (jameshaller345)
usr.loc: The plating (/turf/simulated/floor/plating) ([0x101337b]) (56,143,2) (/area/ishimura/upper/maintenance/aft_port)

**Comment by Evankhell561** [comment]
I can't find any reference to the proc "has quality" in door.dm.

**Comment by Evankhell561** [comment]
due to changes in the dm, i don't know if this has already been resolved.

**Comment by NanakoAC** [comment]
this is caused by mobs being passed as the attacking object in door attackby, adding some safety checks
