### ISSUE TITLE
Ghosting from a brute does not reset view.

### ISSUE THREAD

**Issue by Ketrai** [DS-13-Dev-Team/DS13-1.0#52]
#### Description of issue
When ghosting out of a brute you remain zoomed in.

#### Difference between expected and actual behavior
For vision to return back to normal.

#### Steps to reproduce 
Possess a brute, ghost

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by NanakoAC** [comment]
fixed in #103
