### ISSUE TITLE
Unitologist unprotected jobs.

### ISSUE THREAD

**Issue by JakeDaBoss** [DS-13-Dev-Team/DS13-1.0#543]
#### Description of issue
Unsure if this is intended to happen, though I've noticed that even the upper echelons of command can get Unitologist, unlimited.

I'd suggest making command jobs, especially senior command jobs (Captain, CoS, CE, CMO, etc etc) locked from gaining Unitology. Imagine rolling a full-command unitology team, which would be basically unstoppable with all-access.

#### Difference between expected and actual behavior
Command jobs should not be able to spawn with unitologist.

#### Steps to reproduce 
Enable Unitologist
Spawn as Captain (Or other command jobs)
Geddit.

#### Specific information for locating
N/A.

#### Length of time in which bug has been known to occur
Unknown, but presumably since start.

#### Client version, Server revision & Game ID
N/A.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/DS-13-Dev-Team/DS13/issues)

**Comment by ghost** [comment]
It's possible in the future we'll keep most head roles from being Uni's but it is an intended feature. Keeping in line with the source material, and to add to the sense of paranoia, all roles onboard the Ishimura can be selected. If this becomes a problem of powergaming, then we'll probably make changes down the line. Until then, it'll stay pending further testing. Thanks for bringing up your concern though!
