### ISSUE TITLE
Security has no armor for non-code Blue/Red operations.

### ISSUE THREAD

**Issue by JakeDaBoss** [DS-13-Dev-Team/DS13-1.0#544]
#### Description of issue
Security has yet to receive any armor (RIGs spawn fine) for regular operating procedure. I'd expect that Security would be receiving these items.

#### Difference between expected and actual behavior
Basic body armor is absent.

I'd advise the modular ones that allow attachments, if it's applicable.

#### Steps to reproduce 
Spawn as Security.
Search high and low.
Eventually come up empty.
Cry.

#### Specific information for locating

Brig/Security area.

#### Length of time in which bug has been known to occur
I can only confirm as of yesterday.

#### Client version, Server revision & Game ID
N/A.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/DS-13-Dev-Team/DS13/issues)

**Comment by Snypehunter007** [comment]
The security uniforms have protection sown into the clothing, so they act as armor.

**Comment by JakeDaBoss** [comment]
I'd still advise making some kind of altered plate carriers, which I would think to be commonplace for their storage ability. Though, I know they are currently bugged. Looking into it.

**Comment by JakeDaBoss** [comment]
@Snypehunter007 Let me know once you or West have had a chance to decide on this. I can add this to the locker code in less than 10 minutes.

**Comment by Snypehunter007** [comment]
Going to go ahead and put a "Denied" stamp on this one.

P-SEC aren't shown to wear separate vests on their uniform, so either they do not have armor protection or their clothes are made from a protective material, or have plates in them.

We will be making it more obvious that the uniform is armored though, by adding the word "armored" to the uniform's name, so people hopefully stop thinking they have no armor protection as Security.

Locking.
