### ISSUE TITLE
[BUG] Stun Baton delimbing on help and disarm intent. 

### ISSUE THREAD

**Issue by driecg36** [DS-13-Dev-Team/DS13-1.0#563]
#### Description of issue:
Stun baton seems to ignore intents and delimbs people very quickly even on help and disarm intent. After two arrests where I was aiming for the leg due to fighting necros I tried to arrest two separate individuals while on disarm and help intent with the baton, both their legs came off after a handful of prods.

#### Difference between expected and actual behavior:
Prodding should stun without harming unless you are on harm intent. 

#### Steps to reproduce:
Aim for the limbs with a baton on help or disarm intent, click on spaceman to commit accidental warcrimes, get called shitsec.

**Comment by 5crownik007** [comment]
**Testing information:**
*Conditions:*
- Help Intent
- Active baton
- Naked subject

*Result:*
Targeting limbs led to 2 click dismemberment, sometimes 3 clicks. I was on help intent. It would do the prod, as well as the melee strike. Using view-vars, target took roughly 30 brute damage per hit.
After continuous beating on the torso for 10~ seconds, subject was at 279 brute damage, severe heart damage, and in about a minute they had bled out and died.
*Notes:*
- Baton has Force 15 so hypothetically it should do 15 brute damage per hit on harm intent
- Baton should also not be *striking* the target, but prodding them, dealing nothing but stun damage.

I reckon there's been changes in the attack code. Help intent shouldn't really ever make anything strike with damage. I'll look into it a bit further

**Comment by NanakoAC** [comment]
confirmed, the code for stunprodding is executing after strikes happen, batons need some modification to work with the strike system
