### ISSUE TITLE
Suggestion: Add a way to easily tell which way your camera is facing

### ISSUE THREAD

**Issue by psykzz** [DS-13-Dev-Team/DS13-1.0#579]
#### Suggestion:
After changing your view ingame, without map knowledge it can be hard to know which way is north.
Adding a facing var to the status statpanel would go along way

#### What do you think it'd add:
Help with navigation around the map for new players.

**Comment by NanakoAC** [comment]
can you elaborate what you mean by changing your view? Are you rotating the client direction?

**Comment by NanakoAC** [comment]
assuming its that, you're not usually supposed to mess with that. I'm actually planning to use it for psychosis effects in future, to deliberately confuse and disorient people

**Comment by psykzz** [comment]
Yeah its the rotate view clockwise or rotate view counter-clockwise.
If thats the case, happy to close, just it seem'd cool but i got confused quickly since i don't know the maps.
