### ISSUE TITLE
BUG: Cannot interact with severed right arm of Slashers

### ISSUE THREAD

**Issue by Snypehunter007** [DS-13-Dev-Team/DS13-1.0#581]
#### Description of issue:
When trying to pull, using right click -> pull or the grab intent, could not interact with a severed, right slasher arm.

Trying to pick up yielded the same result.

#### Difference between expected and actual behavior:
You can pick up severed, left Slasher arms, but not right arms.

#### Steps to reproduce:
1.) Shoot a Slasher and sever their right arm.
2.) Attempt to pick it up or drag it.

**Comment by NanakoAC** [comment]
Cannot reproduce
can you give any more information regarding the circumstances?

**Comment by Snypehunter007** [comment]
Huh, tested it again and it's fine. I don't know what happened.


I guess I close this one then.
