### ISSUE TITLE
BUG: broken APC turns nearby tiles dark

### ISSUE THREAD

**Issue by AshTheGuy** [DS-13-Dev-Team/DS13-1.0#585]
#### Description of issue:
When breaking an APC Power goes off on nearby Areas, and Tiles near the APC turn Black for some reason, Flashlights dont work on said tiles too

#### Difference between expected and actual behavior:

Tiles shouldnt be pitch black, and flashlights should work on tiles too,

#### Steps to reproduce:
-Slash or break the APC

**Comment by NanakoAC** [comment]
Unable to reproduce, and apcs can't be slashed or shot. As far as i can tell, they can only currently be destroyed by explosions

Blasts also destroy floors.
A broken floor lets you see the level below, and this ship is quite dark

I believe what's happened here is that these dark tiles are just holes in the deck, and there's no bug.

**Comment by AshTheGuy** [comment]
im 100% sure it was a bug, also it happend on one of the tests, i slashed the BPL APC as a spitter then All the nearby Tiles Turned black, Flashlight didnt work on said tiles too. i think it does have something to do with specific areas. Same thing happend a while ago on the Aegis 7 colony.

**Comment by aguyiguess** [comment]
I destroyed an APC as a brute and something like this happened, but flashlights ended up working

**Comment by DTraitor** [comment]
Looks strange and flashlight still can light that place
![image](https://user-images.githubusercontent.com/74188902/123706115-8721ad00-d870-11eb-81eb-031dc6c7e4e7.png)
![image](https://user-images.githubusercontent.com/74188902/123706151-9274d880-d870-11eb-8581-308521e919eb.png)
