### ISSUE TITLE
Suggestion: RIG flatline

### ISSUE THREAD

**Issue by Felkvir** [DS-13-Dev-Team/DS13-1.0#586]
#### Suggestion:
If someone loses vital signs and their healthbar goes empty it plays the flatline sound (unless they're not wearing a RIG for some reason) 

#### What do you think it'd add:
Just some simple flavor to the RIG function and alerting nearby crew if someone dies

**Comment by Snypehunter007** [comment]
We already kinda have this planned, so I'll go ahead and label it as accepted, though it will probably take us some time to implement it.

**Comment by NanakoAC** [comment]
Definitely planned, I've been asking everyone i can to please rip that audio file for me.

All we're waiting on is the sound, and it'll be done. If you know any way to get ahold of it, let me know. We've had someone scouring the dead space assets with no luck

**Comment by aguyiguess** [comment]
https://www.youtube.com/watch?v=y5psyfZ9OZA

Would this work? Seems like a direct rip to me.
