### ISSUE TITLE
BUG : Found a Baycode testing area.

### ISSUE THREAD

**Issue by Lawrence-Wile** [DS-13-Dev-Team/DS13-1.0#601]
#### Description of issue:

During an escape, myself and the SSO were told that too many people were on the escape pod after it fired and that it would exlode if people didnt jump, so we did the hero thing and jumped, drifting for a while to the north, till we hit a wall. I used the wall itself and a fire extinguisher to follow the wall to the north, where I found a giant flat area with O2 and gravity, which was likely, as guessed by TrialMod, TheLion(?), a Baycode testing area. I was asked to make a report on this by the TrialMod.

#### Difference between expected and actual behavior:
I dont know if thats supposed to be accessible, but according to the mod, its been disused for a good while.

#### Steps to reproduce:
Fire escape pod, jump out, drift north, follow wall to the north, profit, safe, O2, Gravity, correct pressure.

#### What do you think it'd add:
It was my first Major Human Victory. Feels good, man.

**Comment by Snypehunter007** [comment]
Yeah, I think it's a Bay Away-Mission area.

**Comment by JakeDaBoss** [comment]
Will look into fixing.
