### ISSUE TITLE
Rules Button does not work

### ISSUE THREAD

**Issue by NanakoAC** [DS-13-Dev-Team/DS13-1.0#604]
At the top of the client, the rules button is nonfunctional

**Comment by aguyiguess** [comment]
@WestHybrid @Snypehunter007 
I didn't check to see if this got fixed, but if it didn't, go into the config folder and edit the rules.html file. Uncomment the baystation link and replace the link with the ds-ss13 wiki page. 

If you want to get rid of all the links and stuff, download the html file and copy-paste the bodyContent div instead.

**Comment by ghost** [comment]
Fairly certain this has been fixed.
