### ISSUE TITLE
Implant Yank runtime

### ISSUE THREAD

**Issue by NanakoAC** [DS-13-Dev-Team/DS13-1.0#613]
[10:33:51] Runtime in mob.dm, line 944: Cannot read null.implants
proc name: Yank out object (/mob/proc/yank_out_object)
usr: Damien Lowe (/mob/living/carbon/human) ([0x300005b]) (the deck) (151,92,3) (/turf/simulated/floor/tiled) (conthegodoffire)
usr.loc: The deck (/turf/simulated/floor/tiled) ([0x101b9b8]) (151,92,3) (/area/aegis/colony/hangar)
src: Damien Lowe (/mob/living/carbon/human)
src.loc: the deck (151,92,3) (/turf/simulated/floor/tiled)
call stack:
Damien Lowe (/mob/living/carbon/human): Yank out object()

Talked to damien loew, he had an axe in his arm, and the arm came off while yanking it out. More than one player attempted to do the yanking at the same time which may also have been a factor

**Comment by ghost** [comment]
Weird Baycode bullshit, could be solved in 2.0.
