### ISSUE TITLE
Necroshop Savefile error

### ISSUE THREAD

**Issue by NanakoAC** [DS-13-Dev-Team/DS13-1.0#625]
High priority due to many ocurrences

[11:04:43] Runtime in necroshop.dm, line 265: bad savefile or list
proc name: finalize spawn (/datum/necroshop/proc/finalize_spawn)
usr: Marker (ketrai) (/mob/observer/eye/signal/master) ([0x30000e5]) (the reinforced plasteel bulkhead) (80,120,1) (/turf/simulated/wall/r_wall) (ketrai)
usr.loc: The reinforced plasteel bulkhead (/turf/simulated/wall/r_wall) ([0x1006b39]) (80,120,1) (/area/ishimura/lower/mining/locker_room)
src: /datum/necroshop (/datum/necroshop)
call stack:
/datum/necroshop (/datum/necroshop): finalize spawn(/list (/list))
/datum/necroshop (/datum/necroshop): start spawn()
/datum/necroshop (/datum/necroshop): Topic("src=\[0x21032f21];spawn=harves...", /list (/list), /datum/topic_state/interactive (/datum/topic_state/interactive))
/datum/nanoui (/datum/nanoui): Topic("src=\[0x21032f21];spawn=harves...", /list (/list))
Ketrai (/client): Topic("src=\[0x21032f21];spawn=harves...", /list (/list), /datum/nanoui (/datum/nanoui))
Ketrai (/client): Topic("src=\[0x21032f21];spawn=harves...", /list (/list), /datum/nanoui (/datum/nanoui))

**Comment by NanakoAC** [comment]
cause currently unknown, a seemingly innocuous line is throwing this, presumably with some bad data in the list

**Comment by ghost** [comment]
@DTraitor Please take a look at this when you have a moment to see if it's still relevant or happening.

**Comment by DTraitor** [comment]
It was fixed at some point
