### ISSUE TITLE
Restart Vote needs to be disabled from public use

### ISSUE THREAD

**Issue by NanakoAC** [DS-13-Dev-Team/DS13-1.0#630]
Restarting the round outside of normal gameplay methods like evac, is the perogative of admins only

**Comment by JakeDaBoss** [comment]
Config option. @WestHybrid @Snypehunter007 

## allow players to initiate a restart vote
ALLOW_VOTE_RESTART

## allow players to initate a mode-change start
ALLOW_VOTE_MODE

These lines need to be getting a # if they want to be blocked. Admins automatically override this config option and can call them manually.
