### ISSUE TITLE
Necroshop runtimes

### ISSUE THREAD

**Issue by NanakoAC** [DS-13-Dev-Team/DS13-1.0#635]
No farther info, not in verbose mode

[20:31:57] Runtime in necroshop.dm, line 316: Cannot execute null.clear turfs in view().
usr: Marker (Pizzatiger) (/mob/observer/eye/signal/master) ([0x300008b]) (the deck) (164,124,1) (/turf/simulated/floor/tiled/white) (pizzatiger)
usr.loc: The deck (/turf/simulated/floor/tiled/white) ([0x1006f25]) (164,124,1) (/area/ishimura/lower/crew/cryo)

[20:31:54] Runtime in necroshop.dm, line 147: Cannot read null.x

**Comment by Evankhell561** [comment]
necroshop.dm:
![image](https://user-images.githubusercontent.com/49106866/106838597-e3571b00-669c-11eb-8e14-91e8c2fa2515.png)

**Comment by Evankhell561** [comment]
necroshop.dm:

![image](https://user-images.githubusercontent.com/49106866/106838646-fe298f80-669c-11eb-810e-4cdc30f275ea.png)

**Comment by Evankhell561** [comment]
from the changes in the dm, I don't know if this has already been resolved.
