### ISSUE TITLE
Suggestion: custom analyzer machines for research

### ISSUE THREAD

**Issue by Felkvir** [DS-13-Dev-Team/DS13-1.0#637]
#### Suggestion:
Basically give research some sort of machine to study alien objects like marker shards or necromorph tissue and the like (maybe a seperate area of research), and an activation button to get different effects. I know there's already a thing in SS13 where you can put artifacts in, we could have a custom version of that. Xenobiology/artifact study. 

#### What do you think it'd add:
Research nerds have little to do atm but it would be fun being able to mess with the marker/necro properties in some way, and maybe the marker can mess with them in return

**Comment by aguyiguess** [comment]
I think this would work well when psychosis is fixed cause it could cause the dementia
