### ISSUE TITLE
SUGGESTION: Add Blast doors to the science department

### ISSUE THREAD

**Issue by AshTheGuy** [DS-13-Dev-Team/DS13-1.0#659]
#### Suggestion:
Add blast doors to Science, from both sides, East and west. and buttons that only the CSO can access in his office

#### What do you think it'd add:
I think Science should have blast doors/shutters, would be a good place to hold

**Comment by JakeDaBoss** [comment]
If this is accepted, I'll add it.

**Comment by NanakoAC** [comment]
up to snype, mapping issue

**Comment by Snypehunter007** [comment]
I'll put this in while I'm here mapping.
