### ISSUE TITLE
[Suggestion] Remove some of the less fitting jukebox tracks and replace them with alternatives

### ISSUE THREAD

**Issue by Green-Horns** [DS-13-Dev-Team/DS13-1.0#668]
#### Suggestion: Remove some of the Dead Space tracks from Jukeboxes and replace them with more fitting songs.

A small list of recommendations:

- https://www.youtube.com/watch?v=w34fSnJNP-4
- https://www.youtube.com/watch?v=3WLE6FpAcVs
- https://www.youtube.com/watch?v=nAk5ane_9AQ
- https://www.youtube.com/watch?v=D5p8YhhaVlA
- https://www.youtube.com/watch?v=lwfl9TMelZE&t
- https://www.youtube.com/watch?v=7dY4qtLaUlE
- https://www.youtube.com/watch?v=2wf-MNzSbpA
- https://www.youtube.com/watch?v=seHlHzYpWBU

#### What do you think it'd add: It'd allow jukeboxes to feel more 'in-universe'. Stuff like Twinkle Twinkle Little Star and some of the other choices are more in line with lobby or after-game tracks, and don't feel like they totally fit.

**Comment by NanakoAC** [comment]
I'll leave the final call on this to Westhybrid, but generally, i added those things to the jukebox simply because we had them already. Taking more songs from dead space might make sense, but these videos linked above are entirely unrelated and belong to different copyright holders. I dont think violating even more copyrights is a good idea

**Comment by JakeDaBoss** [comment]
In general, songs that can/will play organically, such as by activation of mechanic or player, need to absolutely remain within the spectrum of Dead Space. Deviation will, no doubt about it, cause a lot of songs to feel different within the prospect of the game. We need to maintain one, universal standard for that.

**Comment by NanakoAC** [comment]
west says no
