### ISSUE TITLE
Necromorphs can check pulse and attempt CPR on humans

### ISSUE THREAD

**Issue by XtremeSavageXD** [DS-13-Dev-Team/DS13-1.0#67]
#### Description of issue
When on help intent as a Necro, will attempt CPR and/or check pulse on a human

#### Client version, Server revision & Game ID

Latest Dev branch

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by JakeDaBoss** [comment]
CPR no longer possible, checked myself.

Check Pulse remains accessible.

**Comment by JakeDaBoss** [comment]
@Snypehunter007 re-open please. I forgot to remove it from my PR.

This is *NOT* fixed!

**Comment by Snypehunter007** [comment]
Auto-closed when you linked the branch and issue together.
