### ISSUE TITLE
[BUG] Getting Disconnected and reconnecting with a screen covered in walls

### ISSUE THREAD

**Issue by Green-Horns** [DS-13-Dev-Team/DS13-1.0#677]
#### Description of issue: I got smashed into crit by a brute(?) and ended up getting disconnected during a particularly bad spike of lag . I reconnected and it was fine, but got disconnected again while trying to fix myself up. I could hear marker chat at this point, but I am told that is a known issue. I was once again disconnected, and when I reconnected, I was staring a screen filled with walls. Attached in a screenshot of what I saw while finally succumbing to my wounds. 

I think hovering over some of the wall tiles DID give the proper names for them, but I could not move during any of this, even though I wasn't in hardcrit quite yet.

![Walls walls everywhere and not a medkit to see](https://user-images.githubusercontent.com/69741491/90344420-3221d300-dfdf-11ea-929a-e3acd85a69fa.png)

**Comment by Green-Horns** [comment]
I got put into hardcrit and tried to replicate it myself. I noticed that ocean of walls appears right when you get back into the session, but fades out. Maybe it's getting stuck on that instead of fading like it should? I don't know if that helps at all.

**Comment by JakeDaBoss** [comment]
Please ignore me screaming at Lurkers.

As @Anne-Clarke pointed out, it happens arbitrary, though it is most common when:
1. The character is unconscious (i.e. under anesthesia) or in critical condition where they pass out.
2. Something happens to the ckey. It needs to be any action that would physically remove a player from their character's view. Adminghost, disconnects, ghosting and returning will all do the trick.
