### ISSUE TITLE
Suggestion: Reduce slasher cost

### ISSUE THREAD

**Issue by MarshalRed** [DS-13-Dev-Team/DS13-1.0#680]

**Comment by Felkvir** [comment]
I feel this would be a good tradeoff in general for standard necros if they are going to be treated as actually expendable. At least until we have infectors.

**Comment by AshTheGuy** [comment]
i think that'd make more sense in the future, i totally agree with you. slashers cost should be reduced since they tend to die from literally anything

**Comment by Ketrai** [comment]
This has issues though. We currently run extremely high pop. Necro biomass isn't dymamic which is the bigger problem.  Imagine if you could spawn 16 slashers against 20 humans round start. That wouldn't be very balanced. Currently there's far more humans than necros roundstart.

**Comment by MarshalRed** [comment]
As a person who plays survivor the most, slashers are very slow. Slashers swarms are only good if people don't run from them.

**Comment by JakeDaBoss** [comment]
I'm against this.

Slashers are just fine.

**Comment by NanakoAC** [comment]
25 would be utterly crazy, slashers are already the cheapest necromorph, costing about 60% of what a human costs to spawn once, and you can respawn that repeatedly as its reabsorbed. There's enough biomass to spawn five of them from the word go, then another five eight minutes later

Their cost is pretty right for the proportions we want to see in the necromorph spawning rates. Slashers are the most common thing and so its working as intended.
On a broader perspective, are necromorphs struggling to win fights? I've not seen that, their growth seems pretty consistent. 
Slashers will get a little buff in the form of a new ability in future though

**Comment by Snypehunter007** [comment]
> On a broader perspective, are necromorphs struggling to win fights? I've not seen that, their growth seems pretty consistent.

From what I've seen, most Necromorphs are a joke to fight.

**Comment by JakeDaBoss** [comment]
> > On a broader perspective, are necromorphs struggling to win fights? I've not seen that, their growth seems pretty consistent.
> 
> From what I've seen, most Necromorphs are a joke to fight.

They are meant to be. The Marker is an endless spawner of hell. Shy of a Tripod, Brute or Uber, it's going to be fodder for the masses to wear them down.

Reducing slasher cost will cause other costs to be at an unbalanced scale.

**Comment by NanakoAC** [comment]
as mentioned, i'm going to give slashers a new ability, a defensive mode to block with their blades. will probably buff other stats a little bit too, i understand they're feeling a little weak just now

**Comment by NanakoAC** [comment]
Slashers have recieved a few buffs in this upcoming PR, https://github.com/DS-13-Dev-Team/DS13/pull/757

and they will be given one new ability in future too, but their cost is the lowest right now and isn't likely to decrease farther
