### ISSUE TITLE
[BUG] Kinesis glitch causing an unplayable state (Unclear how to reproduce)

### ISSUE THREAD

**Issue by AtlanteanCaptain** [DS-13-Dev-Team/DS13-1.0#697]
#### Steps to reproduce: Unknown, likely something to do with Kinesis. (at least that is what Westhybrid suggested)

<!--

**Comment by NanakoAC** [comment]
i have no idea where to begin with this, sounds wild!

my best guess is that you somehow grabbed yourself with kinesis, i've made some recent changes that may prevent it happening again
