### ISSUE TITLE
Suggestion: Add workbenches in Maints

### ISSUE THREAD

**Issue by AshTheGuy** [DS-13-Dev-Team/DS13-1.0#698]
#### Suggestion:
As the title says, Add workbenches in Maints, so the crew wont have to go to engie every single time just so they can craft 

#### What do you think it'd add:
it would be make things much easier. also it would make sense to have some laying around in maints.

**Comment by JakeDaBoss** [comment]
Workbenches currently serve no use to my knowledge.

They will in due time, but they won't be placed in maintenance to my knowledge. They will be placed in major departments, if I'm correct.

West, Nanako or Snype can give extra clarification on this.

**Comment by Snypehunter007** [comment]
Denied. Workbenches are supposed to be limited and locked away.

Locking.
