### ISSUE TITLE
[Suggestion] Give the bridge an emergency ladder down to the executive hanger area.

### ISSUE THREAD

**Issue by Starless-Horizon** [DS-13-Dev-Team/DS13-1.0#705]
#### What do you think it'd add: Every time the necro's push bridge it goes three ways. Either bridge holds out and pushes them back. Either the Necro's push bridge until they murder everyone inside of it as the survivors stand around the back utterly trapped, or someone breaches the glass and escapes to space only to be warped to a random spot in the ship by an admin.

I think having the possibility to open/close an emergency ladder from either deck would add another dynamic to gameplay. It'd come with its own risks, like if the Necro's had already taken over the executive area, or if a unitologist ensign leaves open the back door. But overall It kind of hurts to see the executive area go almost entirely unused by the bridge staff when it seems like a perfect area to fall back to when the bridge is lost. Since they have access and it's right bellow them. 

Consider that the Ishimura bridge had an elevator in DS1 as well and had direct access to escape pods.

**Comment by Snypehunter007** [comment]
Going to deny this because it brings up a whole slew of problems with defensibly and accessibility.

Currently, the Exec area goes mostly unused because the Executive Shuttle isn't working at the moment. It is also supposed to be a challenge to get there.

Locking.

**Comment by Starless-Horizon** [comment]
You have a single set of stairs for the entire ship. I think you have more problems with defensibly and accessibility than just this.

**Comment by Snypehunter007** [comment]
There is also the engineering ladders.

**Comment by Starless-Horizon** [comment]
Just going to leave this here for the sake of posterity. But the exec hanger will always go unused because it is an utter death trap to even attempt to go near it. You need to go all the way down the choke point hallway, down the ambush stairs, drudge through the slow-down gunk, head past the various defenses the Necromorphs no doubt set up, and pray you don't run into the b-lining horde during your travels who can abuse turning into ghosts to gain information on all survivor movements and relay it to their Necromorph minions.

Unless you've got an entire squad with you, it's pointless to even try it when the escape pods are so much closer and better situated. You'll never get the executive hanger used by anyone other than people who were already hiding in the area and miraculously have access to it.

It's going to remain a pointless addition, coding or not, if the only way to approach it when evac has been called is to willfully try to die.
