### ISSUE TITLE
Suggestion: All roles should have Rig health indicators on their uniforms themselves.

### ISSUE THREAD

**Issue by Starless-Horizon** [DS-13-Dev-Team/DS13-1.0#706]
#### Suggestion:

Add spine health indicators to all role uniforms, or give them role-specific harness types that go in the armour slot, rather than the backpack one.

#### What do you think it'd add: 

I've been doing a binge of all things Deadspace. (Completed DS1, watched the tie-in movie, and am watching a lets play of Extraction) and one thing that has become pretty clear is all jobs on the Ishimura, the colony, and civilian roles in general have rigs built into their uniform jackets, or on role-specific harnesses. What I think this will add is a better grasp on the artistic design of the server, as well as allowing the bypass of a civilian harness you have to spend points on that may clash with your uniforms design.

The purpose of this suggestion is to give uniforms at bare minimum a health indicator without the benefits of a RIG. You'd be able to tie in the visibility of your spine to suit sensors, thus disabling the light if you want to go in stealth mode in the dark. 

It may also be a good idea to remove the backpack type storage and retain only satchels to prevent obscuring of the spines visibility. Which I do not doubt would be part of regulations to keep them visible at all times for liability purposes.

**Comment by Snypehunter007** [comment]
I'm not against this, but we did talk about this before in the past.

**Comment by NanakoAC** [comment]
those " role-specific harnesses" are rigs. just small, slimmer ones. 
We will address this with alternate visual styles for the civilian rig.

In the dead space universe, everyone wears a rig. That's the eventual goal here too

**Comment by NanakoAC** [comment]
discussed farther in discord, we are aware that rigs have significantly less storage than backpacks did, will adjust that in future. This won't be implemented as written though
