### ISSUE TITLE
Bug: Rejuvinate and Aheals remove helmets, shoes and headsets

### ISSUE THREAD

**Issue by ghost** [DS-13-Dev-Team/DS13-1.0#710]
#### Description of issue:
Using the aheal or rejuvinate functions as admins causes players to drop their helmets, shoes and headsets. Also affects RIGs.

#### Difference between expected and actual behavior:
Using these tools should only fix damage and not remove articles of clothing or equipment. 

#### Steps to reproduce:

1. Join with Admin or Dev permissions.
2. Damage a mob wearing a full outfit of equipment to critical condition.
3. Rejuvinate using right click on mob.

**Comment by NanakoAC** [comment]
i've almost certainly caused this with recent change to clothing masking, will look into it
