### ISSUE TITLE
Bug: Reconnecting as a Unitologist removes the uni icon

### ISSUE THREAD

**Issue by aguyiguess** [DS-13-Dev-Team/DS13-1.0#711]
#### Description of issue:
Reconnecting as a unitologist removes the HUD icon next to your head

#### Difference between expected and actual behavior:
The icon should stay instead of disappearing

#### Steps to reproduce:
Be a unitologist
Close the game window
Go back into the game

**Comment by NanakoAC** [comment]
confirmed and reproducible
