### ISSUE TITLE
Suggestion: A mechanical 'madness' gauge that increases based on horde whispers and visual sightings of Necromorphs.

### ISSUE THREAD

**Issue by Starless-Horizon** [DS-13-Dev-Team/DS13-1.0#729]
#### Suggestion: 
Basically the intent is to tie in inevitable madness to an actual mechanic. Being in proximity of Necromorphs or being the target of the horde would gradually increase it. When the target has reached a high enough state only then would indiscriminate murder be allowed and actively encouraged.

#### What do you think it'd add: 
Right now you can pretty much just ignore the markers whispers for the entire round and give a minimal response. I've done it myself. Assuming other systems can be put into place to balance this, you would have a system that causes visual and auditory hallucinations and overall provide consequences for passive gameplay when you should be on the brink of losing your mind. Perhaps when a life is taken by your own hands the insanity would reduce, or the negative effects of insanity would. Maybe you'd even get randomized objectives that let you lesson it, such as sabotaging ship systems or being converted into a unitologist.

Perhaps if insanity stays high too long the hallucinations get worse, physically disabling you from time to time, making doors appear as walls, overall turning your world into a confusing hellscape. Necessitating adherence to the markers influence. You wouldn't have to kill your best friend, but someone will have to pay the price in blood and misery to lessen your own suffering.

**Comment by Snypehunter007** [comment]
We already have plans for a mechanical psychosis system.

**Comment by NanakoAC** [comment]
Snype is right, we have big plans for something very similar to this, though there's some pretty neat ideas here. Seeing doors as walls is one i wouldn't have thought of, i'll add that to the list
