### ISSUE TITLE
BUG: Salt shaker has a checkered undefined texture

### ISSUE THREAD

**Issue by aguyiguess** [DS-13-Dev-Team/DS13-1.0#738]
#### Description of issue:
Salt shaker in the kitchen has an undefined purple and black texture

#### Difference between expected and actual behavior:
It should have a salt shaker texture, and for some reason, its name has capitals. It should be named "salt shaker" instead of "Salt Shaker" like the other ones in the room.

#### Steps to reproduce:
Spawn as a Line Cook or walk to the kitchen
Find the checkerboard texture named "Salt Shaker"

**Comment by JakeDaBoss** [comment]
Can be closed.

This was a freak occurence. Code doesn't indicate it is ever meant to be changed. If this happens again, please report it again.
