### ISSUE TITLE
Suggestion: Removing Radiation Damage From SM Detonation

### ISSUE THREAD

**Issue by ghost** [DS-13-Dev-Team/DS13-1.0#776]
Suggestion: Removing SM rad damage associated with the explosion going off, or tempering the span of the radiation to the immediate area of engineering as opposed to the whole ship. 

What you think it will add: Less pain and keeps rounds from being debilitating.

**Comment by NanakoAC** [comment]
reducing the range seems best i think. While it is currently a bit much, it still made for some interesting stories!
