### ISSUE TITLE
Suggestion: Frantic growth cost change to 450

### ISSUE THREAD

**Issue by MarshalRed** [DS-13-Dev-Team/DS13-1.0#779]

**Comment by ErwinSnowden** [comment]
Or just nerf the health of necro structures in general.

**Comment by NanakoAC** [comment]
I just decreased the cost of this, frantic growth is a counter to spawncamping, allowing screening walls to be constructed in an emergency.

Growths can be destroyed in many ways, they mostly exist to stall for time. And if you've got a ton of growths blocking you, you can get rid of them using one of the many explosive weapons available to crew. use the linecutter's plasma mine for an easy path clear
