### ISSUE TITLE
Rebalance the active camo module.

### ISSUE THREAD

**Issue by ErwinSnowden** [DS-13-Dev-Team/DS13-1.0#780]
#### Suggestion:
Make the electrical cost of the active camouflage module significantly higher, around 1 megawatt to activate and a latent active energy cost of around 50-100 kW/s,
Located here: https://github.com/DS-13-Dev-Team/DS13/blob/69cc276ab678a60c0266af15765b87c3ef97e280/code/modules/clothing/spacesuits/rig/modules/ninja.dm

**Comment by NanakoAC** [comment]
its been brought up a few times;
The stealth module is bay content. There doesn't seem to be any sign of cloaking technology in the dead space universe, so this module is slated to be removed as non-canon unless we find a good reason to keep it

**Comment by JakeDaBoss** [comment]
I'll remove it. Stealth stuff is properly impossible to play against.
