### ISSUE TITLE
Hivemind speak takes character display name.

### ISSUE THREAD

**Issue by Ketrai** [DS-13-Dev-Team/DS13-1.0#80]
#### Description of issue
If someone wears a gas mask, or anything else that changes their character display name, you can get "Uknown" speaking into the hivespeak, this doesn't make sense.

#### Difference between expected and actual behavior
Character name, not display name.

#### Steps to reproduce 
Be unitologist, put on gas mask, hivespeak.

**Comment by NanakoAC** [comment]
fixed last week
