### ISSUE TITLE
Suggetion and might be bug: chemistry and my sanity

### ISSUE THREAD

**Issue by hovershift01** [DS-13-Dev-Team/DS13-1.0#804]
#### Description of issue: chemistry machines doing what they shouldn't, delivering broken numbers of chems, delivering other chems besides the one i asked it to send a example is inaprovaline, you add acetone, carbon and sugar what i got the first time is a broken mess between -2 and +2 of the amount i wanted plus other chemicals, the first time it added silicon which made kelotane, the second time i made received the plus sulfuric acid
the chem master does the same

#### Difference between expected and actual behavior:
it doesn't do what it should do, give broken mess of number instead of actual amount it was asked for

#### Steps to reproduce:
do chemistry

#### Suggestion:
give the chemistry machine the usual which is infinite chems but limited by power
and IF the bug is not a bug remove that "content" and fix chemistry
#### What do you think it'd add:
make my life easier and my sanity ok and medical job less painful and wasteful

**Comment by hovershift01** [comment]
i tested it again and the chemmaster transfer exact amount but if you have more then one chem inside beaker it transfers both chemicals if there is three chemicals its random the chemical it transfers

**Comment by aguyiguess** [comment]
This is because you don't have the correct skill level in-game, I'm not sure what exactly the skill is but I know this isn't a bug. I like infinite chems limited by power but it doesn't really fit, maybe the limited amount of chems already installed could be buffed a bit?

**Comment by hovershift01** [comment]
skills shouldn't affect how much units i get from a machine which is literally press button for this amount

**Comment by Snypehunter007** [comment]
Yeah, this isn't so much a bug, as much as it's Bay's skill system not making sense.

I agree that your skill level really shouldn't effect if a chemical reaction goes off or not, if you add the proper amount, you should get the proper amount back.

Since it isn't a bug, technically, I'll mark it as a accepted suggestion.
