### ISSUE TITLE
Organ printer needs to be disabled

### ISSUE THREAD

**Issue by NanakoAC** [DS-13-Dev-Team/DS13-1.0#805]
apparently the old organ printer is buildable

**Comment by Snypehunter007** [comment]
I can do this one.

**Comment by ErwinSnowden** [comment]
Removing more QoL, OK then, not like it takes some considerable effort to make it or something, and even then to use it. Whatever.

**Comment by Snypehunter007** [comment]
The whole point of us making the BPL was to replace the organ printer, @ErwinSnowden.
