### ISSUE TITLE
More spawnpoints needed

### ISSUE THREAD

**Issue by NanakoAC** [DS-13-Dev-Team/DS13-1.0#806]
Got to add spawning to dorm rooms

and also detect corruption/necros to determine if a room is unsafe

**Comment by Snypehunter007** [comment]
What do you mean, "more spawning"?

**Comment by JakeDaBoss** [comment]
I'm curious as well.

More spawnpoints aren't needed. They're done at a manner of job slots.

**Comment by NanakoAC** [comment]
Fixed in #809
