### ISSUE TITLE
[Suggestion] Add Github webhook at discord

### ISSUE THREAD

**Issue by Terror4000rus** [DS-13-Dev-Team/DS13-1.0#824]
#### Suggestion:
https://gist.github.com/jagrosh/5b1761213e33fc5b54ec7f6379034a22

#### What do you think it'd add:
Easier for devs and interested players to track new PRs, issues and commits.

**Comment by JakeDaBoss** [comment]
Not a whole lot easier. It's spammy, and easy to look over. Its use is limited.

**Comment by Terror4000rus** [comment]
> Not a whole lot easier. It's spammy, and easy to look over. Its use is limited.

It has settings. You can only set  "show new PRs/new issues/new comments/new commits" and so.

**Comment by JakeDaBoss** [comment]
@WestHybrid Need your look into this. I can help you set it up, if need be.
