### ISSUE TITLE
[Bug] Reconnecting doesn't works after round end

### ISSUE THREAD

**Issue by Terror4000rus** [DS-13-Dev-Team/DS13-1.0#833]
#### Description of issue:
After the game round ends, the server doesn't reconnect automatically.
Maybe next lines in configs weren't filled up
```
## set a server location for world reboot. Don't include the byond://, just give the address and port.
#SERVER server.net:port
```

#### Difference between expected and actual behavior:
Autoreconnect.

#### Steps to reproduce:
1) Round ends.
2) Wait.
3) Wait more. The bug happens.
4) Reconnect manually.

**Comment by JakeDaBoss** [comment]
Have noticed this.

**Comment by ghost** [comment]
Will check in with Joe about this to see if it's resolved or not.

**Comment by DTraitor** [comment]
It appears that server wasn't properly restarting because of some miss-placed code. It was fixed in https://github.com/DS-13-Dev-Team/DS13/pull/2039
