### ISSUE TITLE
Suggestion: Add the CCO (Chief Communications Officer)

### ISSUE THREAD

**Issue by 1kajowsmol** [DS-13-Dev-Team/DS13-1.0#838]

**Comment by MarshalRed** [comment]
Yes

**Comment by Snypehunter007** [comment]
So, while this might be a lore role, I'm not sure, mechanically, it'd be worth having as a role, especially since the CE kinda already fills this role.

**Comment by JakeDaBoss** [comment]
CCO will be useful once the comms array is in.

**Comment by Snypehunter007** [comment]
West and I talked this over and we're going to deny this one.

Adding another engineering role with the increased surge in powergaming isn't going to be a great idea and the CE fills this roll essentially already.

Denied.
