### ISSUE TITLE
Divider MegaIssue Thread

### ISSUE THREAD

**Issue by Ketrai** [DS-13-Dev-Team/DS13-1.0#868]
- Divider tongue not retracting when the execution ends x
- People unable to attack arms 
- arms can't climb off their victim
- components are too hard to click, generally x
- Reports of arms on the body being unclickable
- Reports of weapons being lost mysteriously. They might just be breaking from damage without showing a message. Unconfirmed reports that component melee attacks cause it x
- Divider heads need a verb to evacuate a stolen corpse
- Corpses need to only be posessable once, and not reuseable
- leg uses the death sprite, rather than the idle animation.
- Arms can latch onto other necros

- divider heads can take control of other necromorphs.
- This can also cause infinite biomass as it incurs reclamation.
- necros can't tell divider's inhabiting humans from other humans that easily.
- Equipping a helmet or a hat as a divider inhabiting a human will reset the heat sprite back to the original. This includes undeployed rigs from decapped rig personel, making it impossible to tell if someone is human or  not. (due to icon updates)
- Perhaps more of an oddity, but dividers can take over any kind of carbon mob, including monkeys. The head however, doesn't change.  E.G a monkey with a divider will still have a monkey head, which is bad

**Comment by NanakoAC** [comment]
all fixed yesterday
