### ISSUE TITLE
Supermatter can be picked up with kinesis.

### ISSUE THREAD

**Issue by Ketrai** [DS-13-Dev-Team/DS13-1.0#869]
I don't have to even explain why this is a problem.

**Comment by NanakoAC** [comment]
We discussed internally and west ruled on it, but for posterity:

Being able to pickup the supermatter is intended behaviour, its a very lore appropriate use. Remote manipulation to safely handle dangerous materials. Engineers are allowed and even encouraged to do this when its a necessary repair step, for example if ejection goes wrong and you need to get it out, or installing a new supermatter to replace an ejected one.

The case which prompted this report - someone swinging it around as a weapon, is against the rules. Nobody should be messing with a running engine, even antags. Anyone attempting to use the supermatter for combat purposes is an admin issue to handle.

also while it does sound scary, i tested it thoroughly and a few things make this not even practical:
-The supermatter doesn't consume people when its dragged or thrown into them, it only consumes when they are the ones moving
-It can't grab things through glass, someone would need to open the reaction chamber to do this
