### ISSUE TITLE
Announcements broken

### ISSUE THREAD

**Issue by XtremeSavageXD** [DS-13-Dev-Team/DS13-1.0#87]
#### Description of issue
When attempting to make an announcement, you can type in the text in, but when you press enter it does nothing

#### Difference between expected and actual behavior
doesent make the actual announcement

#### Steps to reproduce 
try to announce using software on the bridge console

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by Snypehunter007** [comment]
Fixed in #114
