### ISSUE TITLE
Suggestion: Add more metal/glass to RnD + Make upgraded components more useful

### ISSUE THREAD

**Issue by githubuser4141** [DS-13-Dev-Team/DS13-1.0#871]
#### What do you think it'd add:

Currently the only materials RnD gets roundstart is 20 metal and about 10 glass which isn't enough to sustain it throughout the round, or even in early game. 

++ Suggestion 2: Make upgraded stock parts actually make machinery more efficient, right now T3 parts don't seem to do anything and are a waste of time.

**Comment by JakeDaBoss** [comment]
How do you mean T3 parts don't seem to do anything? Can you give me a concrete example?

**Comment by JakeDaBoss** [comment]
For reference:

Upgraded stock parts are meant to hold more materials. They don't increase anything.
