### ISSUE TITLE
Corruption spread broke.

### ISSUE THREAD

**Issue by Ketrai** [DS-13-Dev-Team/DS13-1.0#872]
corruption spreads instantly whenever it ticks. aka, it spawns a full time of  corruption when the process happens, rather than gradually making a tile corrupted.  This causes insanely fast spread.

**Comment by NanakoAC** [comment]
this should only happen with a debug spreading node, very odd, i'll look into it

Spreading every tick is not itself a bug, its just what happens when the spread rate is very high. seems like its higher than it should be

**Comment by NanakoAC** [comment]
fixed
