### ISSUE TITLE
Turrets Friendly Fire

### ISSUE THREAD

**Issue by XtremeSavageXD** [DS-13-Dev-Team/DS13-1.0#88]
#### Description of issue
Turrets will fire at anyone and everything, usually crew, as two times I lost both my hands

#### Difference between expected and actual behavior
Turrets arent hand takers

#### Steps to reproduce 
walk to the turret near the bridge

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by Snypehunter007** [comment]
Fixed in #114
