### ISSUE TITLE
T4 Necromorphs need to be based on total biomass

### ISSUE THREAD

**Issue by NanakoAC** [DS-13-Dev-Team/DS13-1.0#882]
A reminded for myself
Tier 4 Necromorphs (currently, only the ubermorph) will be moved to having a requirement in total biomass, rather than having a cost.

Total biomass counts all biomass that is under necromorph control, including:
-the available biomass amount the marker has to spend
-Biomass currently invested in alive necromorphs or corruption nodes
-Biomass in dead necromorphs or destroyed nodes which has not yet been reclaimed

If the total of all these sources reaches the required value, a single T4 necromorph can be spawned, without any actual cost.

The required value will be set significantly higher than it currently is, but will be more attainable due to not having to save up a lump sum

**Comment by AshTheGuy** [comment]
Yes.

**Comment by MarshalRed** [comment]
Good idea
