### ISSUE TITLE
Melee Issues

### ISSUE THREAD

**Issue by XtremeSavageXD** [DS-13-Dev-Team/DS13-1.0#89]
#### Description of issue
Several times I attempted to knife a necro using the small knife, nothing happened

#### Difference between expected and actual behavior
supposed to slash

#### Steps to reproduce 
try to slash a necro with the small steel knife as well as other weapons

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by NanakoAC** [comment]
fixed in #96
