### ISSUE TITLE
An idea to get rid of space stalemate

### ISSUE THREAD

**Issue by Terror4000rus** [DS-13-Dev-Team/DS13-1.0#899]
#### Suggestion:
`Mr.Marker, another one engineer just spaced. We can't move there without a chance of lost in the void because the whole hull is black, so, we will just chill aboard and wait for 20 minutes until they will come back to one of pods from windows.`
Familiar, don't it?

So, my idea.
Add constant radiation in space area. Longer they will be on the hull, severly escapers will suffer from their choice of escape route. It is still a last-chance way to escape death, but without proper medicine, it will at least cost them health.
Why there is so much radiaton to die from it?
After (or before) the marker's activation, 2-3 minutes, the crew will get an announcement about entering in classic radiation belt. It will last for end of round.

#### What do you think it'd add:
Less stalemate situations with a guy at the hull. Die alone or die with others, but don't make others boring.

**Comment by JakeDaBoss** [comment]
This is a terrible idea. People who are spaced, will gain injuries anyway and/or randomly run out of Oxygen. They will either be teleported into a random Z, or find their way back inside. And with a solution I have, that'll fix this issue. Spacing yourself is no longer a valid option.

**Comment by NanakoAC** [comment]
the limiting factor on spending time in space is the oxygen reserve. This will likely be significantly reduced in future. Probably not quite the same as the dead space games, where tank times are about 2 minutes. but definitely less than the hour or two it lasts now

**Comment by JakeDaBoss** [comment]
> the limiting factor on spending time in space is the oxygen reserve. This will likely be significantly reduced in future. Probably not quite the same as the dead space games, where tank times are about 2 minutes. but definitely less than the hour or two it lasts now

There's also no escape as of now. You can only teleport onto the levels that are the Ishimura. Eventually, an Uber is gonna come to punt your ass all over the playing field like a football.
