### ISSUE TITLE
SUGGESTION: Make it easier to communicate by adding a loud mode to radios and attaching ranks to radio names

### ISSUE THREAD

**Issue by XtremeSavageXD** [DS-13-Dev-Team/DS13-1.0#90]
#### Description of issue
Would make everything much easier with communication and rank etc.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by Snypehunter007** [comment]
This has been sorta implemented with #284.
