### ISSUE TITLE
Corruption spread is too slow

### ISSUE THREAD

**Issue by NanakoAC** [DS-13-Dev-Team/DS13-1.0#91]
Takes forever to spread corruption, time delay needs reduced a bit, and range increased

**Comment by Ketrai** [comment]
It's quite tricky to get rid of corruption so I feel like the speed is fine. The main issue is spreading it via propagator nodes. There needs to be an alternative way to get corruption in further places. It also shouldn't be too easy as corruption is quite powerful in its current state.
