### ISSUE TITLE
Necromorphs spawning in help intent

### ISSUE THREAD

**Issue by NanakoAC** [DS-13-Dev-Team/DS13-1.0#913]
necros should always start in harm intent

**Comment by JakeDaBoss** [comment]
Or remove intents for them, tbh?

**Comment by NanakoAC** [comment]
they do need intents, they use grab to open doors and some can also grab humans

**Comment by NanakoAC** [comment]
okay the intent is actually set but the hud doesn't update

the hud code for intent buttons is atrociously bad, i'm sickened to look at it.  Needs a little refactoring
