### ISSUE TITLE
Lurker Bugs

### ISSUE THREAD

**Issue by NanakoAC** [DS-13-Dev-Team/DS13-1.0#914]
When lurkers open their shell while on a wall, they cannot move
When shell is open, they sometimes can't climb onto walls
When lurkers fall unconscious or get knocked down, they don't fall off the wall

**Comment by JakeDaBoss** [comment]
> When lurkers open their shell while on a wall, they cannot move

Only happened once to me. Worked after that.

> When shell is open, they sometimes can't climb onto walls

Idem to above.

> When lurkers fall unconscious or get knocked down, they don't fall off the wall

Haven't seen this.
