### ISSUE TITLE
Bridge hull window frames

### ISSUE THREAD

**Issue by Terror4000rus** [DS-13-Dev-Team/DS13-1.0#917]
Some of them (from port and starboard) are blue, as should be, but front one doesn't. Make them all blue, like the hull.
Just check front window frames at bridge.

**Comment by JakeDaBoss** [comment]
> Some of them (from port and starboard) are blue, as should be, but front one doesn't. Make them all blue, like the hull.
> Just check front window frames at bridge.

Please present screenshots of where this occurs, and I'll get to it.

**Comment by Snypehunter007** [comment]
#823
(Just linking this so I can label it as fixed later.)
