### ISSUE TITLE
Add more escape routes for ship areas

### ISSUE THREAD

**Issue by Terror4000rus** [DS-13-Dev-Team/DS13-1.0#918]
### a paste

I'll start with definition.
Escape routes, for me — ways to escape a room without getting cornered.
A character enters in a room. There is a traitor behind. The victim can't get back, because there is a threat - the traitor - behind airlock. There should be a way to escape from this situation.
A list from best to worst:

0) Airlock with only your access. The threat have to spend some time and, likely, will just lost the character.

1) A path without obstacles. A straight way to get out.

2) Other airlock, which leads to separated area.
Example:

<details>

![image](https://user-images.githubusercontent.com/19491666/95867903-dc299b80-0d93-11eb-96ea-c3969d9df6fe.png)
Ordinary escape route. Have one enterence from hallway and another one from maints. If the threat in hallway - use maints. If in maints - use hallway. If in both - there were enough option to escape, so, the player have to pick the least threat and break through.

</details>

2) Windows to other areas.

<details>

![image](https://user-images.githubusercontent.com/19491666/95868425-6540d280-0d94-11eb-92aa-b30e48b4e8e3.png)
The character can break one and get through. More like a way to get in, because, usually, there's no time during chase to break it.

</details>

3) Space bin. Just flush yourself. I don't remember if there is a damage from being flushed or no, but almost every time it's a death (from wounds or necros).

4) Hull window. Don't forget EVA gear and don't will get bored, because there is no threat (a first reason why at least I play here) to a crewmate at hull but oxygen lost, previous wounds and slip chance.

5) Floor. Break the floor and continue running. Will work only if the character isn't at lowest deck. A high chance to die.

6) Walls. Death imminent in case of chase, too much time to break it.

# Suggestion, tl;dr

Good rooms:
<details>

![image](https://user-images.githubusercontent.com/19491666/95870257-80acdd00-0d96-11eb-92f0-691b86e9767e.png)
![image](https://user-images.githubusercontent.com/19491666/95870268-84406400-0d96-11eb-9ee6-89b7faec042c.png)
![image](https://user-images.githubusercontent.com/19491666/95870283-873b5480-0d96-11eb-8e59-87cee6fe3d1f.png)
![image](https://user-images.githubusercontent.com/19491666/95870304-8dc9cc00-0d96-11eb-9842-d1494d788c80.png)

</details>

Bad rooms, aka death traps:
<details>

![image](https://user-images.githubusercontent.com/19491666/95870362-9b7f5180-0d96-11eb-834c-3d32057af574.png)
![image](https://user-images.githubusercontent.com/19491666/95870371-9e7a4200-0d96-11eb-89e5-ccfa74636b15.png)
![image](https://user-images.githubusercontent.com/19491666/95870384-a0dc9c00-0d96-11eb-9bab-9b62d573b7c5.png)
![image](https://user-images.githubusercontent.com/19491666/95870394-a33ef600-0d96-11eb-8512-9b25027e822d.png)
![image](https://user-images.githubusercontent.com/19491666/95870407-a5a15000-0d96-11eb-872d-7b416f7651cf.png)
![image](https://user-images.githubusercontent.com/19491666/95870547-d08ba400-0d96-11eb-8a05-43df85f9691e.png)
And also bridge

</details>

Add more good rooms. More routes to continue gameplay, than just die from being cornered. At least add more windows.
"Don't get in areas where you could be cornered" - there shouldn't be such areas at all, except if it's small and stands somewhere at border. Like a small room in maints with a small amount of loot and some utility gear for jobs.

#### What do you think it'd add:
Better gameplay with chasing somewhere but at the hull.

**Comment by Terror4000rus** [comment]
I don't want to argue (because all arguments were already said), so just think about it, at least

**Comment by NanakoAC** [comment]
this is very broad and difficult to action

**Comment by JakeDaBoss** [comment]
The Ishimura's original design in the game was cramped and suffocatingly claustrophobic. This is a non-issue. People need to know what/where is and isn't a viable holding spot.
