### ISSUE TITLE
Flashbangs don't quite follow design philosophy [ISSUE]

### ISSUE THREAD

**Issue by Ketrai** [DS-13-Dev-Team/DS13-1.0#920]
- flashbangs are universally a little too good compared to alternatives. (Line gun, chevals, forcegun, beartraps, and detonator). 
.
- unlike other options, there's little friendly fire. If you wear a rig, or sunglasses, you are almost entirely protected from the effects of flashbangs. Necromorphs despite their high stun resistance, still get knocked out for 3-5 seconds. 

- stuns are supposed to be rare, especially ones that long. Only the brute has similar strength when it comes to stuns, and his slow movement compensates for this big upside. Being able to take down large necromorphs whilst they're stunned and unable to fight back is rather anticlinactic.

Flashbangs either need to be revamped, or necromorphs need to experience lesser effect. There are no other reliable AOE stuns, people should rely more on the forcegun instead. The radius is also a bit outrageous, whilst a wall can immediately completely nullify flashbangs too, which is odd.

**Comment by Snypehunter007** [comment]
Flashbangs probably shouldn't affect Necromorphs TBH.

**Comment by Ketrai** [comment]
It isn't just flashbangs. It's a bit silly how long you van hold off necros with tasers, combat shields and stun batons. Being stunned or crawling makes life a lot more difficult... mainly for the already weaker melee classes

**Comment by Snypehunter007** [comment]
Tasers, like flashbangs, should also not affect Necromorphs.

Holding off Necromorphs with combat shields should probably be a separate issue, since that is related to Nanako's Combat system. In regards to the stun baton issue you bring up, are you saying that Necros get stunned by the baton or that the baton just does a lot of damage?

**Comment by Snypehunter007** [comment]
#310
(Just linking this to label the it as fixed later.)

**Comment by MarshalRed** [comment]
This needs to be pushed in my opinion.
