### ISSUE TITLE
Ubermorph cost notes

### ISSUE THREAD

**Issue by Ketrai** [DS-13-Dev-Team/DS13-1.0#921]
4.5 k is a bit much, causing the ubermorph to almost never spawn.

at 1:30 necromorphs have about 3-4k biomass. So granted the marker starts with around 450 - 600 biomass at 45:00. This means the marker slowly builds up an income of about 56.66 per minute at the low end, or 75.5 per minute at the high end. This is usually the point most humans have died, or escaped. and then the ubermorph is still 7-30+ minutes away. Note that the higher estimate is FAR rarer and hard to obtain, only occuring if the marker grabs enough objectives and corpses. 

This is not to say the cost is too high in general though. If anything, humans die because the necromorphs gather so much biomass. Having 3.5k biomass for example, means you can technically have up to 10 brutes/tripods active at a time. Even with a large part invested in nodes and nests, necros become a tremendous fighting force. If anything, rounds are still too short. Humans get overrun by large amounts of necros before they can properly mobilize, and mainly civilian casualties are high. 

- humans either need more effective ways of slowing corruption. Ways to hold barricades more easily and construct them. Perhaps a new type of security barricades? Humans need ways to replenish ammo, or gain strength in the late game. After all they get more experienced.

**Comment by NanakoAC** [comment]
amount was recently reduced to 3800 ish, is it still too high?

**Comment by Ketrai** [comment]
It seems to be nust right now. Uber comes out when there's only a couple survivors left. If at all.

**Comment by JakeDaBoss** [comment]
That is their purpose, yes.
