### ISSUE TITLE
[ISSUE] Space isn't adapted yet 

### ISSUE THREAD

**Issue by Ketrai** [DS-13-Dev-Team/DS13-1.0#922]
Outer space is still very much compareable to vanilla ss13 space. It's far too easy to get outside,  survive, and completely avoid necromorph eyes as a result. Not to mention, you can freely travel to a pod from the outside, dismantle the window to get inside. There's often windows near to just invade the pod that way too.

this is not reminiscent of the actual deadspace experience. Where lurkers, leapers and medusa very actively harass survivors. Here's several proposed solutions.

1. Limited air supply when outside the ship, not just a normal vacuum or the mining colony. You should only be able to spend 3-5 minutes outside without a proper E.V.A suit. Due to the conditions of space, and debris from a rapidly degrading spaceship.

2. Make it far tougher to get outside. Outter windows should have strong blast doors that automatically come down soon after destruction. This should make re-entry far more difficult. Outer walls should be tamper proof, allowing no disassembly. Once you're outside you are stranded as a result, being too close to a window when it breaks means getting sucked outside, with perhaps a chance to hang on and pull back inside before the blast doors close. Otherwise you get vented into space, or stranded along the ship walls outside. This could make for a fitting strategy against necros if the suction is powerful enough, like in the games.

3. Medusa and other space borne organisms/growths. The marker should be able to grow a film onto the walls outside, and cultivate the local spacefauna into medusa. Medusa act as sentries,  fighting anyone who gets close and retaliating against attackers. These will gradually make space less and less hospitable. 

4. Space debris. Adding more space debris as the round goes on, including large pieces of shipwreck. This simulates the degradation of the ishimura and necro influence. Being both dangerous to humans, and a tool for lurkers and leapers. Which can both jump from debris to debris in the games. This makes space combat a little more interesting with more to hold onto. Just be careful for moving debris. Both harmful, and easy leverage into the dark depths of space.

**Comment by Ketrai** [comment]
A dedicated EVA deck wouldn't hurt either. As long as it isn't as trivial as opening a window 8nto space is currently.

**Comment by MarshalRed** [comment]
Good idea.
