### ISSUE TITLE
Bug: Captain lockdowns mislabeled

### ISSUE THREAD

**Issue by atenistra** [DS-13-Dev-Team/DS13-1.0#926]
#### Description of issue:
As title suggest, the lockdowns in captain's office do not correspond to the correct sets of blast doors.

#### Difference between expected and actual behavior:
Upper Deck Aft lockdown affects lower deck aft, etc.

#### Steps to reproduce:
Use any of the captain's office's lockdown panels.

**Comment by JakeDaBoss** [comment]
Will fix in Tram deck.

**Comment by JakeDaBoss** [comment]
Fixing this now.
