### ISSUE TITLE
Bug: First Lieutenant does not have ID access

### ISSUE THREAD

**Issue by atenistra** [DS-13-Dev-Team/DS13-1.0#927]
#### Description of issue:
FL does not have permission to manage ID access.

#### Difference between expected and actual behavior:
Wiki has several headings talking about the FL's role in managing ID access.

#### Steps to reproduce:
Try to use the ID Modification program as FL

**Comment by Snypehunter007** [comment]
This is a bug on the wiki, since it's mostly pulled from normal Baystation, @atenistra . It shouldn't say that.

Captain is meant to be the only one with access.

**Comment by Snypehunter007** [comment]
This has now been fixed.

Closing.
