### ISSUE TITLE
BUG: Fleshy slasher sprite missing legs

### ISSUE THREAD

**Issue by NanakoAC** [DS-13-Dev-Team/DS13-1.0#930]
In north direction
https://i.imgur.com/1Hibc0E.png

and east direction
https://i.imgur.com/C9BGxeC.png

with the right leg severed, both legs appear to be gone

does not affect south and west

**Comment by Snypehunter007** [comment]
Pretty sure this is a problem with the masking system you made.

Humans have the same problem when one limb is severed, both disappear from the sprite until the severed limb is reattached.

**Comment by Evankhell561** [comment]
![image](https://user-images.githubusercontent.com/49106866/106599068-d9c49a80-6558-11eb-8948-902b071a0097.png)
![image](https://user-images.githubusercontent.com/49106866/106599078-dc26f480-6558-11eb-90ee-9a444a44b1d1.png)
![image](https://user-images.githubusercontent.com/49106866/106599094-e0eba880-6558-11eb-99e0-f08315714e81.png)
![image](https://user-images.githubusercontent.com/49106866/106599102-e3e69900-6558-11eb-961f-27e4fc14390c.png)

**Comment by Evankhell561** [comment]
It seems that this bug has already been fixed or at least I can't reproduce it.
