### ISSUE TITLE
Suggestion: Bridge staff loss access to armory, instead have divets roundstart.

### ISSUE THREAD

**Issue by MarshalRed** [DS-13-Dev-Team/DS13-1.0#932]

**Comment by MarshalRed** [comment]
An addon would be they only get a divet and the mag in it. No extra mags.

**Comment by Snypehunter007** [comment]
So after talking to West it was decided that Bridge staff (meaning FL and BEs in this case):

- Will keep armory access.
- Be allowed divet pistols at round start with **no** extra magazines.

**Comment by AshTheGuy** [comment]
Why not just make a mini armory in Bridge, wich contains Divet pistols **ONLY** and you can't really access it unless the FL or Cap open it?

**Comment by Snypehunter007** [comment]
Adding an armory would just provide more ammo to bridge staff. Giving them just a Divet with no spare clips caps the initial amount that they would be able to access without ordering more or asking Sec for their ammo.

**Comment by Snypehunter007** [comment]
Added in #933 .

Closing.
