### ISSUE TITLE
[BUG] Ubermorph abilities can break

### ISSUE THREAD

**Issue by Ketrai** [DS-13-Dev-Team/DS13-1.0#936]
#### Description of issue:
As ubermorph, having the ability menu open causes you to inherit verbs of other necros when they're nearby, and causes your own to break.

#### Steps to reproduce:
Be uber, have other necros near, try to use abilities. 
- sense seems to work, same for battle cry when this happens.
- Lunge seems to break after one use.

**Comment by NanakoAC** [comment]
inherit verbs like what? were you able to use other peoples' abilities?

**Comment by Ketrai** [comment]
@NanakoAC not able to use them. But they would flood the ability tab and make it impossible to use. As abilities flip in and out of the menu if a necro went back out of range or died. Weiiiird bug.
