### ISSUE TITLE
[BUG] Total biomass still doesn't work properly.

### ISSUE THREAD

**Issue by Ketrai** [DS-13-Dev-Team/DS13-1.0#937]
#### Description of issue:
Total biomass accumulates correctly now, but you can't spawn an ubermorph with it. The spawn button never lights up.

#### Steps to reproduce:
Obtain total biomass, still can't spawn. NOTE, make sure your current biomass isn't sufficient to spend on an ubermorph. Spawn some tripods first to lower it below the actual cost, as long as total biomass is higher.

**Comment by JakeDaBoss** [comment]
What I think happens here is that it requires the x amount of biomass, but also needs you to have it in reserves to spawn it?
