### ISSUE TITLE
[BUG] Unreasonable Biomass amount

### ISSUE THREAD

**Issue by Ketrai** [DS-13-Dev-Team/DS13-1.0#941]
#### Description of issue:
https://cdn.discordapp.com/attachments/683216679299186745/767167184299360256/New_Biomass_Record.PNG

as per the screenshots, in some cases insane amounts of biomass can be obtained whilst the normal amount id between 3k - 5k by the end of the round. 

#### Steps to reproduce:
Uncertain. The example above happened on an enemy within round. There may be anomalies related to it. Also, check if capturing biomass objectives early enough can cause this to happen.

**Comment by NanakoAC** [comment]
i have no reason to doubt it, but currently no way to make it happen.  Any additional information would be helpful

**Comment by NanakoAC** [comment]
marking resolved for now, reopen if it reoccurs
