### ISSUE TITLE
SUGGESTION: Add science comms to Miners headsets

### ISSUE THREAD

**Issue by AshTheGuy** [DS-13-Dev-Team/DS13-1.0#954]
-->
#### What do you think it'd add:
Give miners Science comms access so they can order Tools and so can the CSCIO order ores without having to bug Cargo about it

**Comment by JakeDaBoss** [comment]
Cargo is the middleman here. So, I'm going to go ahead and say no until someone with the capacity to decide comes along.

**Comment by ghost** [comment]
@Snypehunter007 was this fixed?

**Comment by Snypehunter007** [comment]
> 
> 
> @Snypehunter007 was this fixed?

Not yet, I'll be able to get it this weekend.
