### ISSUE TITLE
Idea: Machine interface spell

### ISSUE THREAD

**Issue by NanakoAC** [DS-13-Dev-Team/DS13-1.0#962]
a context sensitive signal spell that interfaces with machinery and activates simple functions on them. For example:
-changing tracks on a jukebox/stereo
-opening doors (pre marker activation only)
-turning computers on and off
-flush toilets
-activate grinders and paper shredders
-open/close locker doors
-toggle floodlights
-turn on microwave

**Comment by aguyiguess** [comment]
more ideas: release a prize from an arcade, launch an unspecified item from a vending machine, produce a bottle from the chem master, disconnect a computer from the internet for a short amount of time

**Comment by KeRSedChaplain** [comment]
more ideas: turn off an APCs main breaker (likely with a high cooldown if used this way), set a status message on status displays, trigger a fire alarm and/or air alarm, activate a button, randomize a devices setting

**Comment by NanakoAC** [comment]
breakers, buttons and fire alarms are too powerful for a fun spell like this, effects shouldn't have major combat utility, this is more for spooking people. Status message is a great idea though
