### ISSUE TITLE
Hearing loss doesn't heal

### ISSUE THREAD

**Issue by NanakoAC** [DS-13-Dev-Team/DS13-1.0#973]
Getting lots of reports of explosions causing hearing loss in crewmembers, and it doesn't heal naturally

**Comment by JakeDaBoss** [comment]
Correct. I manually have to set the deafness var to 0.

It's often over 200, but instances can occur with 100 as well.

As far as I know - this happens after the player has been deafened once before, which runs out fine. Then after the second time, or more, it doesn't.
