### ISSUE TITLE
Plasma Saw punches doors

### ISSUE THREAD

**Issue by NanakoAC** [DS-13-Dev-Team/DS13-1.0#992]
attacking a door with a plasma saw causes you to punch the door instead of hitting it with the saw

But oddly, only when activated. Hitting works normally when the blade is powered down

**Comment by JakeDaBoss** [comment]
I can't find out anything from the code of the saw that would cause this behavior.

**Comment by JeserTheFox** [comment]
Saws don't have any interaction with airlocks set, aside from circular saw being able to cut wires.

Nanako said they will look at it later, so leaving this info here.
